
var BlinkInputWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkInputWasmSDK) {
  BlinkInputWasmSDK = BlinkInputWasmSDK || {};


var f;f||(f=typeof BlinkInputWasmSDK !== 'undefined' ? BlinkInputWasmSDK : {});var ba;f.ready=new Promise(function(a){ba=a});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in f)f.hasOwnProperty(da)&&(ca[da]=f[da]);var ea="./this.program";function fa(a,b){throw b;}var ha=!1,ia=!1;ha="object"===typeof window;ia="function"===typeof importScripts;var q="",ja;
if(ha||ia)ia?q=self.location.href:document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ia&&(ja=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var ka=f.print||console.log.bind(console),r=f.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(f[da]=ca[da]);ca=null;f.thisProgram&&(ea=f.thisProgram);
f.quit&&(fa=f.quit);function la(a){var b=x[ma>>2];x[ma>>2]=b+a+15&-16;return b}var na={"f64-rem":function(a,b){return a%b},"debugger":function(){}},oa=0,pa;f.wasmBinary&&(pa=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&r("no native wasm support detected");var qa,ra=new WebAssembly.Table({initial:2876,maximum:2876,element:"anyfunc"}),sa=!1,ta="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ua(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ta)return ta.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function y(a,b){return a?ua(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}
function va(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var wa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function xa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&D[c];)++c;c<<=1;if(32<c-a&&wa)return wa.decode(A.subarray(a,c));c=0;for(d="";;){var e=ya[a+2*c>>1];if(0==e||c==b/2)return d;++c;d+=String.fromCharCode(e)}}
function za(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ya[b>>1]=a.charCodeAt(e),b+=2;ya[b>>1]=0;return b-d}function Aa(a){return 2*a.length}function Ba(a,b){for(var c=0,d="";!(c>=b/4);){var e=x[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ca(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var h=a.charCodeAt(++e);g=65536+((g&1023)<<10)|h&1023}x[b>>2]=g;b+=4;if(b+4>c)break}x[b>>2]=0;return b-d}function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Ea(a){var b=va(a)+1,c=E(b);c&&B(a,I,c,b);return c}var Fa,I,A,ya,D,x,J,Ga,Ha;
function Ia(a){Fa=a;f.HEAP8=I=new Int8Array(a);f.HEAP16=ya=new Int16Array(a);f.HEAP32=x=new Int32Array(a);f.HEAPU8=A=new Uint8Array(a);f.HEAPU16=D=new Uint16Array(a);f.HEAPU32=J=new Uint32Array(a);f.HEAPF32=Ga=new Float32Array(a);f.HEAPF64=Ha=new Float64Array(a)}var ma=703984,Ja=f.INITIAL_MEMORY||209715200;if(qa=f.wasmMemory?f.wasmMemory:new WebAssembly.Memory({initial:Ja/65536,maximum:32768}))Fa=qa.buffer;Ja=Fa.byteLength;Ia(Fa);x[ma>>2]=5947072;
function Ka(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.La;"number"===typeof c?void 0===b.ia?f.dynCall_v(c):f.dynCall_vi(c,b.ia):c(void 0===b.ia?null:b.ia)}}}var La=[],Ma=[],Na=[],Oa=[],Pa=!1;function Qa(){var a=f.preRun.shift();La.unshift(a)}var Ra=0,Sa=null,Ta=null;function Ua(){Ra++;f.monitorRunDependencies&&f.monitorRunDependencies(Ra)}
function Va(){Ra--;f.monitorRunDependencies&&f.monitorRunDependencies(Ra);if(0==Ra&&(null!==Sa&&(clearInterval(Sa),Sa=null),Ta)){var a=Ta;Ta=null;a()}}f.preloadedImages={};f.preloadedAudios={};function L(a){if(f.onAbort)f.onAbort(a);a+="";ka(a);r(a);sa=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function Wa(){var a=Xa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Xa="BlinkInputWasmSDK.wasm";if(!Wa()){var Ya=Xa;Xa=f.locateFile?f.locateFile(Ya,q):q+Ya}function Za(){try{if(pa)return new Uint8Array(pa);if(ja)return ja(Xa);throw"both async and sync fetching of the wasm failed";}catch(a){L(a)}}
function $a(){return pa||!ha&&!ia||"function"!==typeof fetch?new Promise(function(a){a(Za())}):fetch(Xa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Xa+"'";return a.arrayBuffer()}).catch(function(){return Za()})}
f.asm=function(){function a(e){f.asm=e.exports;Va()}function b(e){a(e.instance)}function c(e){return $a().then(function(g){return WebAssembly.instantiate(g,d)}).then(e,function(g){r("failed to asynchronously prepare wasm: "+g);L(g)})}var d={env:ab,wasi_snapshot_preview1:ab,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:na};Ua();if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return r("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(pa||"function"!==
typeof WebAssembly.instantiateStreaming||Wa()||"function"!==typeof fetch)return c(b);fetch(Xa,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(g){r("wasm streaming compile failed: "+g);r("falling back to ArrayBuffer instantiation");c(b)})})})();return{}};
var bb=[function(a,b){a=y(a);b=y(b);throw Error(a+b);},function(a,b,c,d){a=y(a);b=y(b);c=y(c);d=y(d);throw Error(a+b+c+d);},function(a){a=y(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},function(a,b){a=y(a);b=y(b);console.log(a+b)},function(a){throw Error(y(a));},function(){throw Error("Unable to perform that operation while recognizer is in use!");}];Ma.push({La:function(){cb()}});var M={};function db(){return ea||"./this.program"}
function eb(a){if(eb.ja){var b=x[a>>2];var c=x[b>>2]}else eb.ja=!0,M.USER="web_user",M.LOGNAME="web_user",M.PATH="/",M.PWD="/",M.HOME="/home/web_user",M.LANG=("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",M._=db(),c=Pa?E(1024):la(1024),b=Pa?E(256):la(256),x[b>>2]=c,x[a>>2]=b;a=[];var d=0,e;for(e in M)if("string"===typeof M[e]){var g=e+"="+M[e];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(e=0;e<
a.length;e++){d=g=a[e];for(var h=c,l=0;l<d.length;++l)I[h++>>0]=d.charCodeAt(l);I[h>>0]=0;x[b+4*e>>2]=c;c+=g.length+1}x[b+4*a.length>>2]=0}function fb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function gb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function hb(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function ib(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function jb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=fb(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var kb=[];function lb(a,b){kb[a]={input:[],m:[],O:b};mb(a,nb)}
var nb={open:function(a){var b=kb[a.node.da];if(!b)throw new N(43);a.v=b;a.seekable=!1},close:function(a){a.v.O.flush(a.v)},flush:function(a){a.v.O.flush(a.v)},read:function(a,b,c,d){if(!a.v||!a.v.O.ya)throw new N(60);for(var e=0,g=0;g<d;g++){try{var h=a.v.O.ya(a.v)}catch(l){throw new N(29);}if(void 0===h&&0===e)throw new N(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.v||!a.v.O.la)throw new N(60);try{for(var e=0;e<d;e++)a.v.O.la(a.v,
b[c+e])}catch(g){throw new N(29);}d&&(a.node.timestamp=Date.now());return e}},pb={ya:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=ob(b,!0)}return a.input.shift()},la:function(a,b){null===b||10===b?(ka(ua(a.m,0)),a.m=[]):0!=b&&a.m.push(b)},flush:function(a){a.m&&0<a.m.length&&(ka(ua(a.m,0)),a.m=[])}},qb=
{la:function(a,b){null===b||10===b?(r(ua(a.m,0)),a.m=[]):0!=b&&a.m.push(b)},flush:function(a){a.m&&0<a.m.length&&(r(ua(a.m,0)),a.m=[])}},O={D:null,G:function(){return O.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.D||(O.D={dir:{node:{J:O.f.J,F:O.f.F,T:O.f.T,aa:O.f.aa,Da:O.f.Da,Fa:O.f.Fa,Ea:O.f.Ea,Ca:O.f.Ca,ea:O.f.ea},stream:{L:O.g.L}},file:{node:{J:O.f.J,F:O.f.F},stream:{L:O.g.L,read:O.g.read,write:O.g.write,qa:O.g.qa,za:O.g.za,
ca:O.g.ca}},link:{node:{J:O.f.J,F:O.f.F,V:O.f.V},stream:{}},ra:{node:{J:O.f.J,F:O.f.F},stream:rb}});c=sb(a,b,c,d);16384===(c.mode&61440)?(c.f=O.D.dir.node,c.g=O.D.dir.stream,c.c={}):32768===(c.mode&61440)?(c.f=O.D.file.node,c.g=O.D.file.stream,c.j=0,c.c=null):40960===(c.mode&61440)?(c.f=O.D.link.node,c.g=O.D.link.stream):8192===(c.mode&61440)&&(c.f=O.D.ra.node,c.g=O.D.ra.stream);c.timestamp=Date.now();a&&(a.c[b]=c);return c},ob:function(a){if(a.c&&a.c.subarray){for(var b=[],c=0;c<a.j;++c)b.push(a.c[c]);
return b}return a.c},pb:function(a){return a.c?a.c.subarray?a.c.subarray(0,a.j):new Uint8Array(a.c):new Uint8Array(0)},ta:function(a,b){var c=a.c?a.c.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.c,a.c=new Uint8Array(b),0<a.j&&a.c.set(c.subarray(0,a.j),0))},Za:function(a,b){if(a.j!=b)if(0==b)a.c=null,a.j=0;else{if(!a.c||a.c.subarray){var c=a.c;a.c=new Uint8Array(b);c&&a.c.set(c.subarray(0,Math.min(b,a.j)))}else if(a.c||(a.c=[]),a.c.length>b)a.c.length=b;else for(;a.c.length<
b;)a.c.push(0);a.j=b}},f:{J:function(a){var b={};b.nb=8192===(a.mode&61440)?a.id:1;b.rb=a.id;b.mode=a.mode;b.vb=1;b.uid=0;b.qb=0;b.da=a.da;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.j:40960===(a.mode&61440)?a.link.length:0;b.kb=new Date(a.timestamp);b.ub=new Date(a.timestamp);b.mb=new Date(a.timestamp);b.Ha=4096;b.lb=Math.ceil(b.size/b.Ha);return b},F:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&O.Za(a,b.size)},T:function(){throw tb[44];
},aa:function(a,b,c,d){return O.createNode(a,b,c,d)},Da:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ub(b,c)}catch(g){}if(d)for(var e in d.c)throw new N(55);}delete a.parent.c[a.name];a.name=c;b.c[c]=a;a.parent=b},Fa:function(a,b){delete a.c[b]},Ea:function(a,b){var c=ub(a,b),d;for(d in c.c)throw new N(55);delete a.c[b]},Ca:function(a){var b=[".",".."],c;for(c in a.c)a.c.hasOwnProperty(c)&&b.push(c);return b},ea:function(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},V:function(a){if(40960!==
(a.mode&61440))throw new N(28);return a.link}},g:{read:function(a,b,c,d,e){var g=a.node.c;if(e>=a.node.j)return 0;a=Math.min(a.node.j-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write:function(a,b,c,d,e,g){b.buffer===I.buffer&&(g=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.c||a.c.subarray)){if(g)return a.c=b.subarray(c,c+d),a.j=d;if(0===a.j&&0===e)return a.c=b.slice(c,c+d),a.j=d;if(e+d<=a.j)return a.c.set(b.subarray(c,c+
d),e),d}O.ta(a,e+d);if(a.c.subarray&&b.subarray)a.c.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.c[e+g]=b[c+g];a.j=Math.max(a.j,e+d);return d},L:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.j);if(0>b)throw new N(28);return b},qa:function(a,b,c){O.ta(a.node,b+c);a.node.j=Math.max(a.node.j,b+c)},za:function(a,b,c,d,e,g,h){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.c;if(h&2||a.buffer!==b.buffer){if(0<e||e+d<a.length)a=a.subarray?a.subarray(e,e+d):
Array.prototype.slice.call(a,e,e+d);e=!0;h=b.buffer==I.buffer;d=E(d);if(!d)throw new N(48);(h?I:b).set(a,d)}else e=!1,d=a.byteOffset;return{i:d,Ga:e}},ca:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);if(e&2)return 0;O.g.write(a,b,0,d,c,!1);return 0}}},vb=null,wb={},xb=[],yb=1,zb=null,Ab=!0,Bb={},N=null,tb={};
function Cb(a,b){a=jb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={wa:!0,na:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.na)throw new N(32);a=fb(a.split("/").filter(function(h){return!!h}),!1);var e=vb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;e=ub(e,a[d]);c=gb(c+"/"+a[d]);e.ba&&(!g||g&&b.wa)&&(e=e.ba.root);if(!g||b.va)for(g=0;40960===(e.mode&61440);)if(e=Db(c),c=jb(hb(c),e),e=Cb(c,{na:b.na}).node,40<g++)throw new N(32);}return{path:c,node:e}}
function Eb(a){for(var b;;){if(a===a.parent)return a=a.G.Aa,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Fb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%zb.length}function ub(a,b){var c;if(c=(c=Gb(a,"x"))?c:a.f.T?0:2)throw new N(c,a);for(c=zb[Fb(a.id,b)];c;c=c.Va){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.f.T(a,b)}function sb(a,b,c,d){a=new Hb(a,b,c,d);b=Fb(a.parent.id,a.name);a.Va=zb[b];return zb[b]=a}
var Ib={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Jb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Gb(a,b){if(Ab)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function Kb(a,b){try{return ub(a,b),20}catch(c){}return Gb(a,"wx")}
function Lb(){var a=4096;for(var b=0;b<=a;b++)if(!xb[b])return b;throw new N(33);}function Mb(a){Nb||(Nb=function(){},Nb.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new Nb,c;for(c in a)b[c]=a[c];a=b;b=Lb();a.I=b;return xb[b]=a}var rb={open:function(a){a.g=wb[a.node.da].g;a.g.open&&a.g.open(a)},L:function(){throw new N(70);}};function mb(a,b){wb[a]={g:b}}
function Ob(a,b){var c="/"===b,d=!b;if(c&&vb)throw new N(10);if(!c&&!d){var e=Cb(b,{wa:!1});b=e.path;e=e.node;if(e.ba)throw new N(10);if(16384!==(e.mode&61440))throw new N(54);}b={type:a,xb:{},Aa:b,Ua:[]};a=a.G(b);a.G=b;b.root=a;c?vb=a:e&&(e.ba=b,e.G&&e.G.Ua.push(b))}function Pb(a,b,c){var d=Cb(a,{parent:!0}).node;a=ib(a);if(!a||"."===a||".."===a)throw new N(28);var e=Kb(d,a);if(e)throw new N(e);if(!d.f.aa)throw new N(63);return d.f.aa(d,a,b,c)}function P(a){Pb(a,16895,0)}
function Qb(a,b,c){"undefined"===typeof c&&(c=b,b=438);Pb(a,b|8192,c)}function Rb(a,b){if(!jb(a))throw new N(44);var c=Cb(b,{parent:!0}).node;if(!c)throw new N(44);b=ib(b);var d=Kb(c,b);if(d)throw new N(d);if(!c.f.ea)throw new N(63);c.f.ea(c,b,a)}function Db(a){a=Cb(a).node;if(!a)throw new N(44);if(!a.f.V)throw new N(28);return jb(Eb(a.parent),a.f.V(a))}
function Sb(a,b,c){if(""===a)throw new N(44);if("string"===typeof b){var d=Ib[b];if("undefined"===typeof d)throw Error("Unknown file open mode: "+b);b=d}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var e=a;else{a=gb(a);try{e=Cb(a,{va:!(b&131072)}).node}catch(g){}}d=!1;if(b&64)if(e){if(b&128)throw new N(20);}else e=Pb(a,c,0),d=!0;if(!e)throw new N(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new N(54);if(!d&&(c=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==Jb(b)||b&512)?31:Gb(e,Jb(b)):44))throw new N(c);if(b&512){c=e;c="string"===typeof c?Cb(c,{va:!0}).node:c;if(!c.f.F)throw new N(63);if(16384===(c.mode&61440))throw new N(31);if(32768!==(c.mode&61440))throw new N(28);if(d=Gb(c,"w"))throw new N(d);c.f.F(c,{size:0,timestamp:Date.now()})}b&=-131713;e=Mb({node:e,path:Eb(e),flags:b,seekable:!0,position:0,g:e.g,jb:[],error:!1});e.g.open&&e.g.open(e);!f.logReadFiles||b&1||(Tb||(Tb={}),a in Tb||(Tb[a]=1,r("FS.trackingDelegate error on read file: "+
a)));try{Bb.onOpenFile&&(c=0,1!==(b&2097155)&&(c|=1),0!==(b&2097155)&&(c|=2),Bb.onOpenFile(a,c))}catch(g){r("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+g.message)}return e}function Ub(){N||(N=function(a,b){this.node=b;this.$a=function(c){this.S=c};this.$a(a);this.message="FS error"},N.prototype=Error(),N.prototype.constructor=N,[44].forEach(function(a){tb[a]=new N(a);tb[a].stack="<generic error, no stack>"}))}var Vb;
function Wb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function Xb(a,b,c){a=gb("/dev/"+a);var d=Wb(!!b,!!c);Yb||(Yb=64);var e=Yb++<<8|0;mb(e,{open:function(g){g.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(g,h,l,n){for(var m=0,p=0;p<n;p++){try{var u=b()}catch(w){throw new N(29);}if(void 0===u&&0===m)throw new N(6);if(null===u||void 0===u)break;m++;h[l+p]=u}m&&(g.node.timestamp=Date.now());return m},write:function(g,h,l,n){for(var m=0;m<n;m++)try{c(h[l+m])}catch(p){throw new N(29);}n&&(g.node.timestamp=Date.now());return m}});
Qb(a,d,e)}var Yb,Zb={},Nb,Tb,$b={},ac=void 0;function bc(a){a=xb[a];if(!a)throw new N(8);return a}
function cc(a,b,c){try{var d=bc(a);a=I;if(0>c||0>g)throw new N(28);if(null===d.I)throw new N(8);if(1===(d.flags&2097155))throw new N(8);if(16384===(d.node.mode&61440))throw new N(31);if(!d.g.read)throw new N(28);var e="undefined"!==typeof g;if(!e)var g=d.position;else if(!d.seekable)throw new N(70);var h=d.g.read(d,a,b,c,g);e||(d.position+=h);return h}catch(l){return"undefined"!==typeof Zb&&l instanceof N||L(l),-l.S}}
function dc(a,b,c){ac=c;try{var d=y(a);ac+=4;return Sb(d,b,x[ac-4>>2]).I}catch(e){return"undefined"!==typeof Zb&&e instanceof N||L(e),-e.S}}function ec(a,b){try{if(-1===(a|0)||0===b)var c=-28;else{var d=$b[a];if(d&&b===d.sb){var e=xb[d.I];d.yb&2&&e&&e.g.ca&&e.g.ca(e,A.slice(a,a+b),d.offset,b,d.flags);$b[a]=null;d.Ga&&Q(d.tb)}c=0}return c}catch(g){return"undefined"!==typeof Zb&&g instanceof N||L(g),-g.S}}
function fc(a){try{var b=bc(a);if(null===b.I)throw new N(8);b.Oa&&(b.Oa=null);try{b.g.close&&b.g.close(b)}catch(c){throw c;}finally{xb[b.I]=null}b.I=null;return 0}catch(c){return"undefined"!==typeof Zb&&c instanceof N||L(c),c.S}}
function gc(a,b,c,d){try{a:{for(var e=bc(a),g=a=0;g<c;g++){var h=e,l=x[b+8*g>>2],n=x[b+(8*g+4)>>2],m=void 0,p=I;if(0>n||0>m)throw new N(28);if(null===h.I)throw new N(8);if(0===(h.flags&2097155))throw new N(8);if(16384===(h.node.mode&61440))throw new N(31);if(!h.g.write)throw new N(28);if(h.seekable&&h.flags&1024){var u=h;if(null===u.I)throw new N(8);if(!u.seekable||!u.g.L)throw new N(70);u.position=u.g.L(u,0,2);u.jb=[]}u="undefined"!==typeof m;if(!u)m=h.position;else if(!h.seekable)throw new N(70);
var w=h.g.write(h,p,l,n,m,void 0);u||(h.position+=w);try{if(h.path&&Bb.onWriteToFile)Bb.onWriteToFile(h.path)}catch(z){r("FS.trackingDelegate['onWriteToFile']('"+h.path+"') threw an exception: "+z.message)}var k=w;if(0>k){var t=-1;break a}a+=k}t=a}x[d>>2]=t;return 0}catch(z){return"undefined"!==typeof Zb&&z instanceof N||L(z),z.S}}var hc={};function ic(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function jc(a){return this.fromWireType(J[a>>2])}var kc={},lc={},mc={};
function nc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function oc(a,b){a=nc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function pc(a){var b=Error,c=oc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var qc=void 0;function rc(a){throw new qc(a);}
function sc(a,b,c){function d(l){l=c(l);l.length!==a.length&&rc("Mismatched type converter count");for(var n=0;n<a.length;++n)R(a[n],l[n])}a.forEach(function(l){mc[l]=b});var e=Array(b.length),g=[],h=0;b.forEach(function(l,n){lc.hasOwnProperty(l)?e[n]=lc[l]:(g.push(l),kc.hasOwnProperty(l)||(kc[l]=[]),kc[l].push(function(){e[n]=lc[l];++h;h===g.length&&d(e)}))});0===g.length&&d(e)}
function tc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var uc=void 0;function S(a){for(var b="";A[a];)b+=uc[A[a++]];return b}var vc=void 0;function T(a){throw new vc(a);}
function R(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(lc.hasOwnProperty(a)){if(c.Sa)return;T("Cannot register type '"+d+"' twice")}lc[a]=b;delete mc[a];kc.hasOwnProperty(a)&&(b=kc[a],delete kc[a],b.forEach(function(e){e()}))}function wc(a){return{count:a.count,M:a.M,U:a.U,i:a.i,l:a.l,u:a.u,A:a.A}}
function xc(a){T(a.b.l.h.name+" instance already deleted")}var yc=!1;function zc(){}function Ac(a){--a.count.value;0===a.count.value&&(a.u?a.A.H(a.u):a.l.h.H(a.i))}function Bc(a){if("undefined"===typeof FinalizationGroup)return Bc=function(b){return b},a;yc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.i?Ac(c):console.warn("object already deleted: "+c.i)});Bc=function(b){yc.register(b,b.b,b.b);return b};zc=function(b){yc.unregister(b.b)};return Bc(a)}
var Cc=void 0,Dc=[];function Ec(){for(;Dc.length;){var a=Dc.pop();a.b.M=!1;a["delete"]()}}function Fc(){}var Gc={};function Hc(a,b,c){if(void 0===a[b].o){var d=a[b];a[b]=function(){a[b].o.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].o+")!");return a[b].o[arguments.length].apply(this,arguments)};a[b].o=[];a[b].o[d.Y]=d}}
function Ic(a,b,c){f.hasOwnProperty(a)?((void 0===c||void 0!==f[a].o&&void 0!==f[a].o[c])&&T("Cannot register public name '"+a+"' twice"),Hc(f,a,a),f.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),f[a].o[c]=b):(f[a]=b,void 0!==c&&(f[a].wb=c))}function Jc(a,b,c,d,e,g,h,l){this.name=a;this.constructor=b;this.N=c;this.H=d;this.B=e;this.Ma=g;this.X=h;this.Ja=l;this.Xa=[]}
function Kc(a,b,c){for(;b!==c;)b.X||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.X(a),b=b.B;return a}function Lc(a,b){if(null===b)return this.ka&&T("null is not a valid "+this.name),0;b.b||T('Cannot pass "'+Mc(b)+'" as a '+this.name);b.b.i||T("Cannot pass deleted object as a pointer of type "+this.name);return Kc(b.b.i,b.b.l.h,this.h)}
function Nc(a,b){if(null===b){this.ka&&T("null is not a valid "+this.name);if(this.$){var c=this.ma();null!==a&&a.push(this.H,c);return c}return 0}b.b||T('Cannot pass "'+Mc(b)+'" as a '+this.name);b.b.i||T("Cannot pass deleted object as a pointer of type "+this.name);!this.Z&&b.b.l.Z&&T("Cannot convert argument of type "+(b.b.A?b.b.A.name:b.b.l.name)+" to parameter type "+this.name);c=Kc(b.b.i,b.b.l.h,this.h);if(this.$)switch(void 0===b.b.u&&T("Passing raw pointer to smart pointer is illegal"),this.eb){case 0:b.b.A===
this?c=b.b.u:T("Cannot convert argument of type "+(b.b.A?b.b.A.name:b.b.l.name)+" to parameter type "+this.name);break;case 1:c=b.b.u;break;case 2:if(b.b.A===this)c=b.b.u;else{var d=b.clone();c=this.Ya(c,U(function(){d["delete"]()}));null!==a&&a.push(this.H,c)}break;default:T("Unsupporting sharing policy")}return c}
function Oc(a,b){if(null===b)return this.ka&&T("null is not a valid "+this.name),0;b.b||T('Cannot pass "'+Mc(b)+'" as a '+this.name);b.b.i||T("Cannot pass deleted object as a pointer of type "+this.name);b.b.l.Z&&T("Cannot convert argument of type "+b.b.l.name+" to parameter type "+this.name);return Kc(b.b.i,b.b.l.h,this.h)}function Pc(a,b,c){if(b===c)return a;if(void 0===c.B)return null;a=Pc(a,b,c.B);return null===a?null:c.Ja(a)}var Qc={};
function Rc(a,b){for(void 0===b&&T("ptr should not be undefined");a.B;)b=a.X(b),a=a.B;return Qc[b]}function Sc(a,b){b.l&&b.i||rc("makeClassHandle requires ptr and ptrType");!!b.A!==!!b.u&&rc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Bc(Object.create(a,{b:{value:b}}))}function V(a,b,c,d){this.name=a;this.h=b;this.ka=c;this.Z=d;this.$=!1;this.H=this.Ya=this.ma=this.Ba=this.eb=this.Wa=void 0;void 0!==b.B?this.toWireType=Nc:(this.toWireType=d?Lc:Oc,this.C=null)}
function Tc(a,b,c){f.hasOwnProperty(a)||rc("Replacing nonexistant public symbol");void 0!==f[a].o&&void 0!==c?f[a].o[c]=b:(f[a]=b,f[a].Y=c)}
function W(a,b){a=S(a);var c=f["dynCall_"+a];for(var d=[],e=1;e<a.length;++e)d.push("a"+e);e="return function dynCall_"+(a+"_"+b)+"("+d.join(", ")+") {\n";e+="    return dynCall(rawFunction"+(d.length?", ":"")+d.join(", ")+");\n";c=(new Function("dynCall","rawFunction",e+"};\n"))(c,b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Uc=void 0;function Vc(a){a=Wc(a);var b=S(a);Q(a);return b}
function Xc(a,b){function c(g){e[g]||lc[g]||(mc[g]?mc[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Uc(a+": "+d.map(Vc).join([", "]));}function Yc(a,b){for(var c=[],d=0;d<a;d++)c.push(x[(b>>2)+d]);return c}
function Zc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=oc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function $c(a,b,c,d,e){var g=b.length;2>g&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].C){l=!0;break}var n="void"!==b[0].name,m="",p="";for(c=0;c<g-2;++c)m+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+nc(a)+"("+m+") {\nif (arguments.length !== "+(g-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(g-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var u=l?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[T,d,e,ic,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+u+", this);\n");for(c=0;c<g-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+u+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);h&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(n?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)g=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].C&&(a+=g+"_dtor("+g+"); // "+b[c].name+"\n",m.push(g+"_dtor"),d.push(b[c].C));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return Zc(m).apply(null,d)}var ad=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function bd(a){4<a&&0===--X[a].oa&&(X[a]=void 0,ad.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=ad.length?ad.pop():X.length;X[b]={oa:1,value:a};return b}}function Mc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function cd(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ga[c>>2])};case 3:return function(c){return this.fromWireType(Ha[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function dd(a,b,c){switch(b){case 0:return c?function(d){return I[d]}:function(d){return A[d]};case 1:return c?function(d){return ya[d>>1]}:function(d){return D[d>>1]};case 2:return c?function(d){return x[d>>2]}:function(d){return J[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function ed(a){a||T("Cannot use deleted val. handle = "+a);return X[a].value}function fd(a,b){var c=lc[a];void 0===c&&T(b+" has unknown type "+Vc(a));return c}var gd={};
function hd(a){var b=gd[a];return void 0===b?S(a):b}var id=[];function jd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function kd(a){var b=id.length;id.push(a);return b}function ld(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=fd(x[(b>>2)+d],"parameter "+d);return c}var md={},nd;nd=function(){return performance.now()};function od(){return A.length}var pd=[];function Y(a,b){J[a>>2]=b;J[a+4>>2]=b/4294967296|0}var qd;
function rd(a,b,c,d,e){var g=J[a+8>>2];if(g){var h=y(g),l=a+112,n=y(l);n||(n="GET");var m=J[l+52>>2],p=J[l+56>>2],u=!!J[l+60>>2],w=J[l+68>>2],k=J[l+72>>2];g=J[l+76>>2];var t=J[l+80>>2],z=J[l+84>>2];l=J[l+88>>2];var F=!!(m&1),K=!!(m&2);m=!!(m&64);w=w?y(w):void 0;k=k?y(k):void 0;var H=t?y(t):void 0,v=new XMLHttpRequest;v.withCredentials=u;v.open(n,h,!m,w,k);m||(v.timeout=p);v.Ab=h;v.responseType="arraybuffer";t&&v.overrideMimeType(H);if(g)for(;;){n=J[g>>2];if(!n)break;h=J[g+4>>2];if(!h)break;g+=8;n=
y(n);h=y(h);v.setRequestHeader(n,h)}pd.push(v);J[a+0>>2]=pd.length;g=z&&l?A.slice(z,z+l):null;v.onload=function(G){var C=v.response?v.response.byteLength:0,Z=0,aa=0;F&&!K&&(aa=C,Z=E(aa),A.set(new Uint8Array(v.response),Z));J[a+12>>2]=Z;Y(a+16,aa);Y(a+24,0);C&&Y(a+32,C);D[a+40>>1]=v.readyState;4===v.readyState&&0===v.status&&(v.status=0<C?200:404);D[a+42>>1]=v.status;v.statusText&&B(v.statusText,A,a+44,64);200<=v.status&&300>v.status?b&&b(a,v,G):c&&c(a,v,G)};v.onerror=function(G){var C=v.status;4===
v.readyState&&0===C&&(C=404);J[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);D[a+40>>1]=v.readyState;D[a+42>>1]=C;c&&c(a,v,G)};v.ontimeout=function(G){c&&c(a,v,G)};v.onprogress=function(G){var C=F&&K&&v.response?v.response.byteLength:0,Z=0;F&&K&&(Z=E(C),A.set(new Uint8Array(v.response),Z));J[a+12>>2]=Z;Y(a+16,C);Y(a+24,G.loaded-C);Y(a+32,G.total);D[a+40>>1]=v.readyState;3<=v.readyState&&0===v.status&&0<G.loaded&&(v.status=200);D[a+42>>1]=v.status;v.statusText&&B(v.statusText,A,a+44,64);d&&d(a,v,G)};v.onreadystatechange=
function(G){D[a+40>>1]=v.readyState;2<=v.readyState&&(D[a+42>>1]=v.status);e&&e(a,v,G)};try{v.send(g)}catch(G){c&&c(a,v,G)}}else c(a,0,"no url specified!")}
function sd(a,b,c,d){var e=qd;if(e){var g=J[a+112+64>>2];g||(g=J[a+8>>2]);var h=y(g);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){D[a+40>>1]=4;D[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,h)};l.onerror=function(n){D[a+40>>1]=4;D[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function td(a,b,c){var d=qd;if(d){var e=J[a+112+64>>2];e||(e=J[a+8>>2]);e=y(e);try{var g=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);g.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,n=E(l);A.set(new Uint8Array(h),n);J[a+12>>2]=n;Y(a+16,l);Y(a+24,0);Y(a+32,l);D[a+40>>1]=4;D[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)}else D[a+40>>1]=4,D[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};g.onerror=function(h){D[a+40>>1]=4;D[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function ud(a,b,c){var d=qd;if(d){var e=J[a+112+64>>2];e||(e=J[a+8>>2]);e=y(e);try{var g=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);g.onsuccess=function(h){h=h.target.result;J[a+12>>2]=0;Y(a+16,0);Y(a+24,0);Y(a+32,0);D[a+40>>1]=4;D[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,h)};g.onerror=function(h){D[a+40>>1]=4;D[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function vd(a){if(0===a)return 0;a=y(a);if(!M.hasOwnProperty(a))return 0;vd.pa&&Q(vd.pa);vd.pa=Ea(M[a]);return vd.pa}function wd(a){return Math.log(a)/Math.LN2}function xd(){xd.R||(xd.R=[]);xd.R.push(yd());return xd.R.length-1}B("GMT",A,704064,4);
function zd(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}if(!zd.ja){zd.ja=!0;x[Ad()>>2]=60*(new Date).getTimezoneOffset();var b=(new Date).getFullYear(),c=new Date(b,0,1);b=new Date(b,6,1);x[Bd()>>2]=Number(c.getTimezoneOffset()!=b.getTimezoneOffset());var d=a(c),e=a(b);d=Ea(d);e=Ea(e);b.getTimezoneOffset()<c.getTimezoneOffset()?(x[Cd()>>2]=d,x[Cd()+4>>2]=e):(x[Cd()>>2]=e,x[Cd()+4>>2]=d)}}
function Dd(a,b){zd();a=new Date(1E3*x[a>>2]);x[b>>2]=a.getSeconds();x[b+4>>2]=a.getMinutes();x[b+8>>2]=a.getHours();x[b+12>>2]=a.getDate();x[b+16>>2]=a.getMonth();x[b+20>>2]=a.getFullYear()-1900;x[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);x[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;x[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;x[b+32>>2]=a;a=x[Cd()+(a?4:0)>>2];
x[b+40>>2]=a;return b}function Ed(a){return 0===a%4&&(0!==a%100||0===a%400)}function Fd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var Gd=[31,29,31,30,31,30,31,31,30,31,30,31],Hd=[31,28,31,30,31,30,31,31,30,31,30,31];function Id(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ed(a.getFullYear())?Gd:Hd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Jd(a,b,c,d){function e(k,t,z){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=z[0]+k;return k}function g(k,t){return e(k,t,"0")}function h(k,t){function z(K){return 0>K?-1:0<K?1:0}var F;0===(F=z(k.getFullYear()-t.getFullYear()))&&0===(F=z(k.getMonth()-t.getMonth()))&&(F=z(k.getDate()-t.getDate()));return F}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function n(k){k=Id(new Date(k.s+1900,0,1),k.ha);var t=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));t=l(t);return 0>=h(z,k)?0>=h(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var m=x[d+40>>2];d={hb:x[d>>2],gb:x[d+4>>2],fa:x[d+8>>2],W:x[d+12>>2],P:x[d+16>>2],s:x[d+20>>2],ga:x[d+24>>2],ha:x[d+28>>2],zb:x[d+32>>2],fb:x[d+36>>
2],ib:m?y(m):""};c=y(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var u="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");m={"%a":function(k){return u[k.ga].substring(0,3)},"%A":function(k){return u[k.ga]},"%b":function(k){return w[k.P].substring(0,3)},"%B":function(k){return w[k.P]},"%C":function(k){return g((k.s+1900)/100|0,2)},"%d":function(k){return g(k.W,2)},"%e":function(k){return e(k.W,2," ")},"%g":function(k){return n(k).toString().substring(2)},"%G":function(k){return n(k)},"%H":function(k){return g(k.fa,2)},
"%I":function(k){k=k.fa;0==k?k=12:12<k&&(k-=12);return g(k,2)},"%j":function(k){return g(k.W+Fd(Ed(k.s+1900)?Gd:Hd,k.P-1),3)},"%m":function(k){return g(k.P+1,2)},"%M":function(k){return g(k.gb,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.fa&&12>k.fa?"AM":"PM"},"%S":function(k){return g(k.hb,2)},"%t":function(){return"\t"},"%u":function(k){return k.ga||7},"%U":function(k){var t=new Date(k.s+1900,0,1),z=0===t.getDay()?t:Id(t,7-t.getDay());k=new Date(k.s+1900,k.P,k.W);return 0>h(z,k)?
g(Math.ceil((31-z.getDate()+(Fd(Ed(k.getFullYear())?Gd:Hd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%V":function(k){var t=new Date(k.s+1901,0,4),z=l(new Date(k.s+1900,0,4));t=l(t);var F=Id(new Date(k.s+1900,0,1),k.ha);return 0>h(F,z)?"53":0>=h(t,F)?"01":g(Math.ceil((z.getFullYear()<k.s+1900?k.ha+32-z.getDate():k.ha+1-z.getDate())/7),2)},"%w":function(k){return k.ga},"%W":function(k){var t=new Date(k.s,0,1),z=1===t.getDay()?t:Id(t,0===t.getDay()?1:7-t.getDay()+1);k=new Date(k.s+
1900,k.P,k.W);return 0>h(z,k)?g(Math.ceil((31-z.getDate()+(Fd(Ed(k.getFullYear())?Gd:Hd,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%y":function(k){return(k.s+1900).toString().substring(2)},"%Y":function(k){return k.s+1900},"%z":function(k){k=k.fb;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.ib},"%%":function(){return"%"}};for(p in m)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),m[p](d)));p=ob(c,!1);if(p.length>
b)return 0;I.set(p,a);return p.length-1}function Hb(a,b,c,d){a||(a=this);this.parent=a;this.G=a.G;this.ba=null;this.id=yb++;this.name=b;this.mode=c;this.f={};this.g={};this.da=d}Object.defineProperties(Hb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});Ub();zb=Array(4096);Ob(O,"/");P("/tmp");P("/home");P("/home/web_user");
(function(){P("/dev");mb(259,{read:function(){return 0},write:function(c,d,e,g){return g}});Qb("/dev/null",259);lb(1280,pb);lb(1536,qb);Qb("/dev/tty",1280);Qb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}b||(b=function(){L("random_device")});Xb("random",b);Xb("urandom",b);P("/dev/shm");P("/dev/shm/tmp")})();P("/proc");P("/proc/self");P("/proc/self/fd");
Ob({G:function(){var a=sb("/proc/self","fd",16895,73);a.f={T:function(b,c){var d=xb[+c];if(!d)throw new N(8);b={parent:null,G:{Aa:"fake"},f:{V:function(){return d.path}}};return b.parent=b}};return a}},"/proc/self/fd");qc=f.InternalError=pc("InternalError");for(var Kd=Array(256),Ld=0;256>Ld;++Ld)Kd[Ld]=String.fromCharCode(Ld);uc=Kd;vc=f.BindingError=pc("BindingError");
Fc.prototype.isAliasOf=function(a){if(!(this instanceof Fc&&a instanceof Fc))return!1;var b=this.b.l.h,c=this.b.i,d=a.b.l.h;for(a=a.b.i;b.B;)c=b.X(c),b=b.B;for(;d.B;)a=d.X(a),d=d.B;return b===d&&c===a};Fc.prototype.clone=function(){this.b.i||xc(this);if(this.b.U)return this.b.count.value+=1,this;var a=Bc(Object.create(Object.getPrototypeOf(this),{b:{value:wc(this.b)}}));a.b.count.value+=1;a.b.M=!1;return a};
Fc.prototype["delete"]=function(){this.b.i||xc(this);this.b.M&&!this.b.U&&T("Object already scheduled for deletion");zc(this);Ac(this.b);this.b.U||(this.b.u=void 0,this.b.i=void 0)};Fc.prototype.isDeleted=function(){return!this.b.i};Fc.prototype.deleteLater=function(){this.b.i||xc(this);this.b.M&&!this.b.U&&T("Object already scheduled for deletion");Dc.push(this);1===Dc.length&&Cc&&Cc(Ec);this.b.M=!0;return this};V.prototype.Na=function(a){this.Ba&&(a=this.Ba(a));return a};
V.prototype.sa=function(a){this.H&&this.H(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=jc;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.$?Sc(this.h.N,{l:this.Wa,i:c,A:this,u:a}):Sc(this.h.N,{l:this,i:a})}var c=this.Na(a);if(!c)return this.sa(a),null;var d=Rc(this.h,c);if(void 0!==d){if(0===d.b.count.value)return d.b.i=c,d.b.u=a,d.clone();d=d.clone();this.sa(a);return d}d=this.h.Ma(c);d=Gc[d];if(!d)return b.call(this);d=this.Z?d.Ia:d.pointerType;var e=Pc(c,this.h,d.h);return null===e?b.call(this):this.$?Sc(d.h.N,{l:d,i:e,A:this,u:a}):Sc(d.h.N,{l:d,i:e})};
f.getInheritedInstanceCount=function(){return Object.keys(Qc).length};f.getLiveInheritedInstances=function(){var a=[],b;for(b in Qc)Qc.hasOwnProperty(b)&&a.push(Qc[b]);return a};f.flushPendingDeletes=Ec;f.setDelayFunction=function(a){Cc=a;Dc.length&&Cc&&Cc(Ec)};Uc=f.UnboundTypeError=pc("UnboundTypeError");f.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};f.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){qd=a;Va()},function(){qd=!1;Va()});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Ua();
function ob(a,b){var c=Array(va(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var ab={___buildEnvironment:eb,___map_file:function(){x[Md()>>2]=63;return-1},___sys_munmap:ec,___sys_open:dc,___sys_read:cc,___syscall3:function(a,b,c){return cc(a,b,c)},___syscall5:function(a,b,c){return dc(a,b,c)},___syscall91:function(a,b){return ec(a,b)},___wasi_fd_close:function(a){return fc(a)},___wasi_fd_write:function(a,b,c,d){return gc(a,b,c,d)},__addDays:Id,__arraySum:Fd,__embind_finalize_value_object:function(a){var b=hc[a];delete hc[a];var c=b.ma,d=b.H,e=b.ua,g=e.map(function(h){return h.Ra}).concat(e.map(function(h){return h.bb}));
sc([a],g,function(h){var l={};e.forEach(function(n,m){var p=h[m],u=n.Pa,w=n.Qa,k=h[m+e.length],t=n.ab,z=n.cb;l[n.Ka]={read:function(F){return p.fromWireType(u(w,F))},write:function(F,K){var H=[];t(z,F,k.toWireType(H,K));ic(H)}}});return[{name:b.name,fromWireType:function(n){var m={},p;for(p in l)m[p]=l[p].read(n);d(n);return m},toWireType:function(n,m){for(var p in l)if(!(p in m))throw new TypeError("Missing field");var u=c();for(p in l)l[p].write(u,m[p]);null!==n&&n.push(d,u);return u},argPackAdvance:8,
readValueFromPointer:jc,C:d}]})},__embind_register_bool:function(a,b,c,d,e){var g=tc(c);b=S(b);R(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=I;else if(2===c)l=ya;else if(4===c)l=x;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>g])},C:null})},__embind_register_class:function(a,b,c,d,e,g,h,l,n,m,p,u,w){p=S(p);g=W(e,g);l&&(l=W(h,l));m&&(m=W(n,m));w=W(u,w);
var k=nc(p);Ic(k,function(){Xc("Cannot construct "+p+" due to unbound types",[d])});sc([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var z=t.h;var F=z.N}else F=Fc.prototype;t=oc(k,function(){if(Object.getPrototypeOf(this)!==K)throw new vc("Use 'new' to construct "+p);if(void 0===H.K)throw new vc(p+" has no accessible constructor");var G=H.K[arguments.length];if(void 0===G)throw new vc("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(H.K).toString()+
") parameters instead!");return G.apply(this,arguments)});var K=Object.create(F,{constructor:{value:t}});t.prototype=K;var H=new Jc(p,t,K,w,z,g,l,m);z=new V(p,H,!0,!1);F=new V(p+"*",H,!1,!1);var v=new V(p+" const*",H,!1,!0);Gc[a]={pointerType:F,Ia:v};Tc(k,t);return[z,F,v]})},__embind_register_class_constructor:function(a,b,c,d,e,g){0<b||L("Assertion failed: undefined");var h=Yc(b,c);e=W(d,e);var l=[g],n=[];sc([],[a],function(m){m=m[0];var p="constructor "+m.name;void 0===m.h.K&&(m.h.K=[]);if(void 0!==
m.h.K[b-1])throw new vc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.h.K[b-1]=function(){Xc("Cannot construct "+m.name+" due to unbound types",h)};sc([],h,function(u){m.h.K[b-1]=function(){arguments.length!==b-1&&T(p+" called with "+arguments.length+" arguments, expected "+(b-1));n.length=0;l.length=b;for(var w=1;w<b;++w)l[w]=u[w].toWireType(n,
arguments[w-1]);w=e.apply(null,l);ic(n);return u[0].fromWireType(w)};return[]});return[]})},__embind_register_class_function:function(a,b,c,d,e,g,h,l){var n=Yc(c,d);b=S(b);g=W(e,g);sc([],[a],function(m){function p(){Xc("Cannot call "+u+" due to unbound types",n)}m=m[0];var u=m.name+"."+b;l&&m.h.Xa.push(b);var w=m.h.N,k=w[b];void 0===k||void 0===k.o&&k.className!==m.name&&k.Y===c-2?(p.Y=c-2,p.className=m.name,w[b]=p):(Hc(w,b,u),w[b].o[c-2]=p);sc([],n,function(t){t=$c(u,t,m,g,h);void 0===w[b].o?(t.Y=
c-2,w[b]=t):w[b].o[c-2]=t;return[]});return[]})},__embind_register_emval:function(a,b){b=S(b);R(a,{name:b,fromWireType:function(c){var d=X[c].value;bd(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:jc,C:null})},__embind_register_float:function(a,b,c){c=tc(c);b=S(b);R(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Mc(e)+'" to '+this.name);return e},argPackAdvance:8,
readValueFromPointer:cd(b,c),C:null})},__embind_register_function:function(a,b,c,d,e,g){var h=Yc(b,c);a=S(a);e=W(d,e);Ic(a,function(){Xc("Cannot call "+a+" due to unbound types",h)},b-1);sc([],h,function(l){Tc(a,$c(a,[l[0],null].concat(l.slice(1)),null,e,g),b-1);return[]})},__embind_register_integer:function(a,b,c,d,e){function g(m){return m}b=S(b);-1===e&&(e=4294967295);var h=tc(c);if(0===d){var l=32-8*c;g=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");R(a,{name:b,fromWireType:g,toWireType:function(m,
p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Mc(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Mc(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:dd(b,h,0!==d),C:null})},__embind_register_memory_view:function(a,b,c){function d(g){g>>=2;var h=J;return new e(Fa,h[g+1],h[g])}var e=[Int8Array,Uint8Array,Int16Array,
Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);R(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Sa:!0})},__embind_register_std_string:function(a,b){b=S(b);var c="std::string"===b;R(a,{name:b,fromWireType:function(d){var e=J[d>>2];if(c)for(var g=d+4,h=0;h<=e;++h){var l=d+4+h;if(0==A[l]||h==e){g=y(g,l-g);if(void 0===n)var n=g;else n+=String.fromCharCode(0),n+=g;g=l+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(A[d+4+h]);n=n.join("")}Q(d);return n},
toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var g="string"===typeof e;g||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=(c&&g?function(){return va(e)}:function(){return e.length})(),l=E(4+h+1);J[l>>2]=h;if(c&&g)B(e,A,l+4,h+1);else if(g)for(g=0;g<h;++g){var n=e.charCodeAt(g);255<n&&(Q(l),T("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+g]=n}else for(g=0;g<h;++g)A[l+4+g]=
e[g];null!==d&&d.push(Q,l);return l},argPackAdvance:8,readValueFromPointer:jc,C:function(d){Q(d)}})},__embind_register_std_wstring:function(a,b,c){c=S(c);if(2===b){var d=xa;var e=za;var g=Aa;var h=function(){return D};var l=1}else 4===b&&(d=Ba,e=Ca,g=Da,h=function(){return J},l=2);R(a,{name:c,fromWireType:function(n){for(var m=J[n>>2],p=h(),u,w=n+4,k=0;k<=m;++k){var t=n+4+k*b;if(0==p[t>>l]||k==m)w=d(w,t-w),void 0===u?u=w:(u+=String.fromCharCode(0),u+=w),w=t+b}Q(n);return u},toWireType:function(n,
m){"string"!==typeof m&&T("Cannot pass non-string to C++ string type "+c);var p=g(m),u=E(4+p+b);J[u>>2]=p>>l;e(m,u+4,p+b);null!==n&&n.push(Q,u);return u},argPackAdvance:8,readValueFromPointer:jc,C:function(n){Q(n)}})},__embind_register_value_object:function(a,b,c,d,e,g){hc[a]={name:S(b),ma:W(c,d),H:W(e,g),ua:[]}},__embind_register_value_object_field:function(a,b,c,d,e,g,h,l,n,m){hc[a].ua.push({Ka:S(b),Ra:c,Pa:W(d,e),Qa:g,bb:h,ab:W(l,n),cb:m})},__embind_register_void:function(a,b){b=S(b);R(a,{Ta:!0,
name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},__emscripten_fetch_free:function(a){delete pd[a-1]},__emscripten_get_fetch_work_queue:function(){return 704160},__emval_addMethodCaller:kd,__emval_allocateDestructors:function(a){var b=[];x[a>>2]=U(b);return b},__emval_as:function(a,b,c){a=ed(a);b=fd(b,"emval::as");var d=[],e=U(d);x[c>>2]=e;return b.toWireType(d,a)},__emval_call_void_method:function(a,b,c,d){a=id[a];b=ed(b);c=hd(c);a(b,c,null,d)},__emval_decref:bd,__emval_get_global:function(a){if(0===
a)return U(jd());a=hd(a);return U(jd()[a])},__emval_get_method_caller:function(a,b){b=ld(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],g=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),g.push(b[1+l]);d="return function "+nc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var n=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=b[l+1].argPackAdvance;d+=
"    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Ta||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Zc(e).apply(null,g);return kd(a)},__emval_get_module_property:function(a){a=hd(a);return U(f[a])},__emval_get_property:function(a,b){a=ed(a);b=ed(b);return U(a[b])},__emval_incref:function(a){4<a&&(X[a].oa+=1)},__emval_lookupTypes:ld,__emval_new:function(a,b,c,d){a=ed(a);var e=md[b];if(!e){e=
"";for(var g=0;g<b;++g)e+=(0!==g?", ":"")+"arg"+g;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(g=0;g<b;++g)h+="var argType"+g+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+g+'], "parameter '+g+'");\nvar arg'+g+" = argType"+g+".readValueFromPointer(args);\nargs += argType"+g+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(fd,
f,U);md[b]=e}return e(a,c,d)},__emval_new_array:function(){return U([])},__emval_new_cstring:function(a){return U(hd(a))},__emval_new_object:function(){return U({})},__emval_register:U,__emval_run_destructors:function(a){ic(X[a].value);bd(a)},__emval_set_property:function(a,b,c){a=ed(a);b=ed(b);c=ed(c);a[b]=c},__emval_take_value:function(a,b){a=fd(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},__getExecutableName:db,__isLeapYear:Ed,__memory_base:1024,__table_base:0,_abort:function(){L()},
_clock_gettime:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=nd();else return x[Md()>>2]=28,-1;x[b>>2]=a/1E3|0;x[b+4>>2]=a%1E3*1E6|0;return 0},_embind_repr:Mc,_emscripten_asm_const_i:function(a){return bb[a]()},_emscripten_asm_const_ii:function(a,b){return bb[a](b)},_emscripten_asm_const_iii:function(a,b,c){return bb[a](b,c)},_emscripten_asm_const_iiiii:function(a,b,c,d,e){return bb[a](b,c,d,e)},_emscripten_asm_const_int:function(){},_emscripten_get_heap_size:od,_emscripten_get_now:nd,
_emscripten_is_main_browser_thread:function(){return!ia},_emscripten_memcpy_big:function(a,b,c){A.copyWithin(a,b,b+c)},_emscripten_resize_heap:function(a){a>>>=0;var b=od();if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(16777216,a,d);0<d%65536&&(d+=65536-d%65536);a:{try{qa.grow(Math.min(2147483648,d)-Fa.byteLength+65535>>>16);Ia(qa.buffer);var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},_emscripten_start_fetch:function(a,b,c,d,e){function g(C){rd(C,
h,m,p,n)}function h(C,Z){sd(C,Z.response,function(aa){t?Nd(t,aa):b&&b(aa)},function(aa){t?Nd(t,aa):b&&b(aa)})}function l(C){rd(C,u,m,p,n)}function n(C){K?Nd(K,C):e&&e(C)}function m(C){z?Nd(z,C):c&&c(C)}function p(C){F?Nd(F,C):d&&d(C)}function u(C){t?Nd(t,C):b&&b(C)}"undefined"!==typeof noExitRuntime&&(noExitRuntime=!0);var w=a+112,k=y(w),t=J[w+36>>2],z=J[w+40>>2],F=J[w+44>>2],K=J[w+48>>2],H=J[w+52>>2],v=!!(H&4),G=!!(H&32);H=!!(H&16);if("EM_IDB_STORE"===k)k=J[w+84>>2],sd(a,A.slice(k,k+J[w+88>>2]),
u,m);else if("EM_IDB_DELETE"===k)ud(a,u,m);else if(H){if(G)return 0;rd(a,v?h:u,m,p,n)}else td(a,u,G?m:v?g:l);return a},_exit:function(a){if(!noExitRuntime&&(sa=!0,f.onExit))f.onExit(a);fa(a,new Od(a))},_fd_close:fc,_fd_write:gc,_getUserAgent:function(){var a=self.navigator.userAgent,b=va(a)+1,c=E(b);B(a,A,c,b);return c},_getenv:vd,_llvm_log2_f32:wd,_llvm_log2_f64:function(a){return wd(a)},_llvm_stackrestore:function(a){var b=xd.R[a];xd.R.splice(a,1);Pd(b)},_llvm_stacksave:xd,_llvm_trap:function(){L("trap!")},
_localtime:function(a){return Dd(a,704016)},_localtime_r:Dd,_mktime:function(a){zd();var b=new Date(x[a+20>>2]+1900,x[a+16>>2],x[a+12>>2],x[a+8>>2],x[a+4>>2],x[a>>2],0),c=x[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),g=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,g);0>c?x[a+32>>2]=Number(g!=h&&l==d):0<c!=(l==d)&&(g=Math.max(h,g),b.setTime(b.getTime()+6E4*((0<c?l:g)-d)));x[a+24>>2]=b.getDay();x[a+28>>2]=(b.getTime()-e.getTime())/864E5|
0;return b.getTime()/1E3|0},_pthread_mutexattr_destroy:function(){},_pthread_mutexattr_init:function(){},_pthread_mutexattr_settype:function(){},_strftime:Jd,_strftime_l:function(a,b,c,d){return Jd(a,b,c,d)},_tzset:zd,abort:L,getTempRet0:function(){return oa},memory:qa,setTempRet0:function(a){oa=a},table:ra,tempDoublePtr:704176},Qd=f.asm({},ab,Fa);f.asm=Qd;f.__ZSt18uncaught_exceptionv=function(){return f.asm.__ZSt18uncaught_exceptionv.apply(null,arguments)};
f.___em_js__getUserAgent=function(){return f.asm.___em_js__getUserAgent.apply(null,arguments)};f.___embind_register_native_and_builtin_types=function(){return f.asm.___embind_register_native_and_builtin_types.apply(null,arguments)};var Md=f.___errno_location=function(){return f.asm.___errno_location.apply(null,arguments)},Wc=f.___getTypeName=function(){return f.asm.___getTypeName.apply(null,arguments)},Bd=f.__get_daylight=function(){return f.asm.__get_daylight.apply(null,arguments)};
f.__get_environ=function(){return f.asm.__get_environ.apply(null,arguments)};var Ad=f.__get_timezone=function(){return f.asm.__get_timezone.apply(null,arguments)},Cd=f.__get_tzname=function(){return f.asm.__get_tzname.apply(null,arguments)};f._emscripten_get_sbrk_ptr=function(){return f.asm._emscripten_get_sbrk_ptr.apply(null,arguments)};f._emscripten_main_thread_process_queued_calls=function(){return f.asm._emscripten_main_thread_process_queued_calls.apply(null,arguments)};
f._emscripten_replace_memory=function(){return f.asm._emscripten_replace_memory.apply(null,arguments)};var Q=f._free=function(){return f.asm._free.apply(null,arguments)};f._llvm_bswap_i32=function(){return f.asm._llvm_bswap_i32.apply(null,arguments)};f._llvm_nearbyint_f32=function(){return f.asm._llvm_nearbyint_f32.apply(null,arguments)};f._llvm_round_f32=function(){return f.asm._llvm_round_f32.apply(null,arguments)};var E=f._malloc=function(){return f.asm._malloc.apply(null,arguments)};
f._memalign=function(){return f.asm._memalign.apply(null,arguments)};f._memcpy=function(){return f.asm._memcpy.apply(null,arguments)};f._memmove=function(){return f.asm._memmove.apply(null,arguments)};f._memset=function(){return f.asm._memset.apply(null,arguments)};f._realloc=function(){return f.asm._realloc.apply(null,arguments)};f._rintf=function(){return f.asm._rintf.apply(null,arguments)};var cb=f.globalCtors=function(){return f.asm.globalCtors.apply(null,arguments)};
f.stackAlloc=function(){return f.asm.stackAlloc.apply(null,arguments)};var Pd=f.stackRestore=function(){return f.asm.stackRestore.apply(null,arguments)},yd=f.stackSave=function(){return f.asm.stackSave.apply(null,arguments)};f.dynCall_di=function(){return f.asm.dynCall_di.apply(null,arguments)};f.dynCall_dii=function(){return f.asm.dynCall_dii.apply(null,arguments)};f.dynCall_diii=function(){return f.asm.dynCall_diii.apply(null,arguments)};
f.dynCall_fi=function(){return f.asm.dynCall_fi.apply(null,arguments)};f.dynCall_fii=function(){return f.asm.dynCall_fii.apply(null,arguments)};f.dynCall_fiiiii=function(){return f.asm.dynCall_fiiiii.apply(null,arguments)};f.dynCall_i=function(){return f.asm.dynCall_i.apply(null,arguments)};f.dynCall_ii=function(){return f.asm.dynCall_ii.apply(null,arguments)};f.dynCall_iii=function(){return f.asm.dynCall_iii.apply(null,arguments)};f.dynCall_iiii=function(){return f.asm.dynCall_iiii.apply(null,arguments)};
f.dynCall_iiiii=function(){return f.asm.dynCall_iiiii.apply(null,arguments)};f.dynCall_iiiiid=function(){return f.asm.dynCall_iiiiid.apply(null,arguments)};f.dynCall_iiiiii=function(){return f.asm.dynCall_iiiiii.apply(null,arguments)};f.dynCall_iiiiiid=function(){return f.asm.dynCall_iiiiiid.apply(null,arguments)};f.dynCall_iiiiiii=function(){return f.asm.dynCall_iiiiiii.apply(null,arguments)};f.dynCall_iiiiiiii=function(){return f.asm.dynCall_iiiiiiii.apply(null,arguments)};
f.dynCall_iiiiiiiii=function(){return f.asm.dynCall_iiiiiiiii.apply(null,arguments)};f.dynCall_iiiiij=function(){return f.asm.dynCall_iiiiij.apply(null,arguments)};f.dynCall_jiji=function(){return f.asm.dynCall_jiji.apply(null,arguments)};f.dynCall_v=function(){return f.asm.dynCall_v.apply(null,arguments)};var Nd=f.dynCall_vi=function(){return f.asm.dynCall_vi.apply(null,arguments)};f.dynCall_vid=function(){return f.asm.dynCall_vid.apply(null,arguments)};
f.dynCall_vidii=function(){return f.asm.dynCall_vidii.apply(null,arguments)};f.dynCall_vif=function(){return f.asm.dynCall_vif.apply(null,arguments)};f.dynCall_vifff=function(){return f.asm.dynCall_vifff.apply(null,arguments)};f.dynCall_vii=function(){return f.asm.dynCall_vii.apply(null,arguments)};f.dynCall_viidi=function(){return f.asm.dynCall_viidi.apply(null,arguments)};f.dynCall_viif=function(){return f.asm.dynCall_viif.apply(null,arguments)};
f.dynCall_viii=function(){return f.asm.dynCall_viii.apply(null,arguments)};f.dynCall_viiid=function(){return f.asm.dynCall_viiid.apply(null,arguments)};f.dynCall_viiii=function(){return f.asm.dynCall_viiii.apply(null,arguments)};f.dynCall_viiiid=function(){return f.asm.dynCall_viiiid.apply(null,arguments)};f.dynCall_viiiii=function(){return f.asm.dynCall_viiiii.apply(null,arguments)};f.dynCall_viiiiii=function(){return f.asm.dynCall_viiiiii.apply(null,arguments)};
f.dynCall_viiiiiii=function(){return f.asm.dynCall_viiiiiii.apply(null,arguments)};f.dynCall_viiiiiiiddi=function(){return f.asm.dynCall_viiiiiiiddi.apply(null,arguments)};f.dynCall_viiiiiiii=function(){return f.asm.dynCall_viiiiiiii.apply(null,arguments)};f.dynCall_viiiiiiiii=function(){return f.asm.dynCall_viiiiiiiii.apply(null,arguments)};f.dynCall_viiiiiiiiii=function(){return f.asm.dynCall_viiiiiiiiii.apply(null,arguments)};
f.dynCall_viiiiiiiiiiddi=function(){return f.asm.dynCall_viiiiiiiiiiddi.apply(null,arguments)};f.dynCall_viiiiiiiiiii=function(){return f.asm.dynCall_viiiiiiiiiii.apply(null,arguments)};f.dynCall_viijii=function(){return f.asm.dynCall_viijii.apply(null,arguments)};f.__ZZN2MB6Embind16RecognizerRunner4pingEN2mb13Recognizer_v26Result5StateEE14requestHeaders=66200;f.__ZZNKSt3__27num_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEE6do_putES4_RNS_8ios_baseEwPKvE5__fmt=115308;
f.__ZZNKSt3__27num_putIwNS_19ostreambuf_iteratorIwNS_11char_traitsIwEEEEE6do_putES4_RNS_8ios_baseEwmE5__fmt=115319;f._glb_1=65976;f.asm=Qd;var Rd;function Od(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Ta=function Sd(){Rd||Td();Rd||(Ta=Sd)};
function Td(){function a(){if(!Rd&&(Rd=!0,f.calledRun=!0,!sa)){Pa=!0;f.noFSInit||Vb||(Vb=!0,Ub(),f.stdin=f.stdin,f.stdout=f.stdout,f.stderr=f.stderr,f.stdin?Xb("stdin",f.stdin):Rb("/dev/tty","/dev/stdin"),f.stdout?Xb("stdout",null,f.stdout):Rb("/dev/tty","/dev/stdout"),f.stderr?Xb("stderr",null,f.stderr):Rb("/dev/tty1","/dev/stderr"),Sb("/dev/stdin","r"),Sb("/dev/stdout","w"),Sb("/dev/stderr","w"));Ka(Ma);Ab=!1;Ka(Na);ba(f);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(f.postRun)for("function"==
typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();Oa.unshift(b)}Ka(Oa)}}if(!(0<Ra)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Qa();Ka(La);0<Ra||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);a()},1)):a())}}f.run=Td;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();noExitRuntime=!0;Td();


  return BlinkInputWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = BlinkInputWasmSDK;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return BlinkInputWasmSDK; });
    else if (typeof exports === 'object')
      exports["BlinkInputWasmSDK"] = BlinkInputWasmSDK;
    