
var BlinkInputWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkInputWasmSDK) {
  BlinkInputWasmSDK = BlinkInputWasmSDK || {};


function g(){n.buffer!=r&&aa(n.buffer);return ba}function u(){n.buffer!=r&&aa(n.buffer);return ca}function da(){n.buffer!=r&&aa(n.buffer);return ea}function v(){n.buffer!=r&&aa(n.buffer);return fa}function A(){n.buffer!=r&&aa(n.buffer);return ha}function B(){n.buffer!=r&&aa(n.buffer);return ia}function ja(){n.buffer!=r&&aa(n.buffer);return ka}function la(){n.buffer!=r&&aa(n.buffer);return ma}var D;D||(D=typeof BlinkInputWasmSDK !== 'undefined' ? BlinkInputWasmSDK : {});var na,oa;
D.ready=new Promise(function(a,b){na=a;oa=b});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},pa;pa=D.allowedThreads&&0<D.allowedThreads?D.allowedThreads-1:navigator.hardwareConcurrency-1;var ra=0,sa;0<pa&&(D.threadWorkersReadyPromise=new Promise(function(a){sa=a}));D.preRun||(D.preRun=[]);D.preRun.push(function(a){function b(){ra++;ra==pa&&sa()}var c=a.PThread.hc;a.PThread.hc=function(d){c(d,b)}});var ta={},ua;
for(ua in D)D.hasOwnProperty(ua)&&(ta[ua]=D[ua]);var va="./this.program";function wa(a,b){throw b;}var xa=!1,ya=!1,za=!1;xa="object"===typeof window;ya="function"===typeof importScripts;za="object"===typeof process&&"object"===typeof process.Bd&&"string"===typeof process.Bd.node;var F=D.ENVIRONMENT_IS_PTHREAD||!1;F&&(r=D.buffer);var Aa="";function Ba(a){return D.locateFile?D.locateFile(a,Aa):Aa+a}var Ca;
if(xa||ya)ya?Aa=self.location.href:"undefined"!==typeof document&&document.currentScript&&(Aa=document.currentScript.src),_scriptDir&&(Aa=_scriptDir),Aa=0!==Aa.indexOf("blob:")?Aa.substr(0,Aa.lastIndexOf("/")+1):"",ya&&(Ca=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var Da=D.print||console.log.bind(console),G=D.printErr||console.warn.bind(console);for(ua in ta)ta.hasOwnProperty(ua)&&(D[ua]=ta[ua]);ta=null;
D.thisProgram&&(va=D.thisProgram);D.quit&&(wa=D.quit);var Ea,Fa;D.wasmBinary&&(Fa=D.wasmBinary);var noExitRuntime=D.noExitRuntime||!0;"object"!==typeof WebAssembly&&I("no native wasm support detected");var n,Ga,Ha=!1;function Ia(a,b){a||I("Assertion failed: "+b)}
function Ja(a,b,c){c=b+c;for(var d="";!(b>=c);){var e=a[b++];if(!e)break;if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function J(a,b){return a?Ja(u(),a,b):""}
function Ka(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function L(a,b,c){Ka(a,u(),b,c)}
function La(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function Ma(a,b){for(var c="",d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Na(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}
function Oa(a){return 2*a.length}function Pa(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Qa(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}
function Ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Sa(a){var b=La(a)+1,c=M(b);c&&Ka(a,g(),c,b);return c}function Ta(a,b){g().set(a,b)}var r,ba,ca,ea,fa,ha,ia,ka,ma;function aa(a){r=a;D.HEAP8=ba=new Int8Array(a);D.HEAP16=ea=new Int16Array(a);D.HEAP32=ha=new Int32Array(a);D.HEAPU8=ca=new Uint8Array(a);D.HEAPU16=fa=new Uint16Array(a);D.HEAPU32=ia=new Uint32Array(a);D.HEAPF32=ka=new Float32Array(a);D.HEAPF64=ma=new Float64Array(a)}
var Ua=D.INITIAL_MEMORY||209715200;
if(F)n=D.wasmMemory,r=D.buffer;else if(D.wasmMemory)n=D.wasmMemory;else if(n=new WebAssembly.Memory({initial:Ua/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw G("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),za&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),Error("bad memory");
n&&(r=n.buffer);Ua=r.byteLength;aa(r);var N,Va=[],Wa=[],Xa=[],Ya=[];F||Wa.push({Pc:function(){Za()}});function $a(){F||(D.noFSInit||ab||(ab=!0,bb(),D.stdin=D.stdin,D.stdout=D.stdout,D.stderr=D.stderr,D.stdin?cb("stdin",D.stdin):db("/dev/tty","/dev/stdin"),D.stdout?cb("stdout",null,D.stdout):db("/dev/tty","/dev/stdout"),D.stderr?cb("stderr",null,D.stderr):db("/dev/tty1","/dev/stderr"),eb("/dev/stdin",0),eb("/dev/stdout",1),eb("/dev/stderr",1)),fb(Wa))}
function gb(){var a=D.preRun.shift();Va.unshift(a)}var hb=0,ib=null,jb=null;function kb(){Ia(!F,"addRunDependency cannot be used in a pthread worker");hb++;D.monitorRunDependencies&&D.monitorRunDependencies(hb)}function lb(){hb--;D.monitorRunDependencies&&D.monitorRunDependencies(hb);if(0==hb&&(null!==ib&&(clearInterval(ib),ib=null),jb)){var a=jb;jb=null;a()}}D.preloadedImages={};D.preloadedAudios={};
function I(a){if(D.onAbort)D.onAbort(a);F&&console.error("Pthread aborting at "+Error().stack);a+="";G(a);Ha=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");oa(a);throw a;}function mb(){var a=nb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var nb="BlinkInputWasmSDK.wasm";mb()||(nb=Ba(nb));
function ob(){var a=nb;try{if(a==nb&&Fa)return new Uint8Array(Fa);if(Ca)return Ca(a);throw"both async and sync fetching of the wasm failed";}catch(b){I(b)}}function pb(){return Fa||!xa&&!ya||"function"!==typeof fetch?Promise.resolve().then(function(){return ob()}):fetch(nb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+nb+"'";return a.arrayBuffer()}).catch(function(){return ob()})}
var qb,rb,tb={125634:function(a,b){a=J(a);b=J(b);throw Error(a+b);},125744:function(a,b,c,d){a=J(a);b=J(b);c=J(c);d=J(d);throw Error(a+b+c+d);},125960:function(a){a=J(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},126096:function(a,b){a=J(a);b=J(b);console.log(a+b)},126194:function(a){throw Error(J(a));},126237:function(){throw"Canceled!";},126255:function(a,b){setTimeout(function(){sb(a,b)},0)},126334:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},126417:function(){throw Error("Unable to perform that operation while recognizer is in use!");},126500:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function fb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(D);else{var c=b.Pc;"number"===typeof c?void 0===b.Gb?N.get(c)():N.get(c)(b.Gb):c(void 0===b.Gb?null:b.Gb)}}}
function ub(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),vb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),vb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}D._emscripten_futex_wake=ub;
function wb(a){if(F)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=O.ob[a];b&&(A()[a+12>>2]=0,O.Xb(b.worker))}
var O={tb:[],vb:[],Od:function(){},Yc:function(){for(var a=M(228),b=0;57>b;++b)B()[a/4+b]=0;A()[a+12>>2]=a;b=a+152;A()[b>>2]=b;var c=M(512);for(b=0;128>b;++b)B()[c/4+b]=0;Atomics.store(B(),a+100>>2,c);Atomics.store(B(),a+40>>2,a);xb(a,!ya,1);yb(a)},Zc:function(){O.receiveObjectTransfer=O.gd;O.setThreadStatus=O.md;O.threadCancel=O.td;O.threadExit=O.ud},ob:{},Zb:[],md:function(){},jd:function(){for(;0<O.Zb.length;)O.Zb.pop()();F&&zb()&&Ab()},Fc:function(a,b){Atomics.store(B(),a+56>>2,1);Atomics.store(B(),
a+60>>2,0);O.jd();Atomics.store(B(),a+4>>2,b);Atomics.store(B(),a+0>>2,1);ub(a+0,2147483647);xb(0,0,0)},ud:function(a){var b=zb();b&&(O.Fc(b,a),F&&postMessage({cmd:"exit"}))},td:function(){O.Fc(zb(),-1);postMessage({cmd:"cancelDone"})},sd:function(){for(var a in O.ob){var b=O.ob[a];b&&b.worker&&O.Xb(b.worker)}O.ob={};for(a=0;a<O.tb.length;++a){var c=O.tb[a];c.terminate()}O.tb=[];for(a=0;a<O.vb.length;++a)c=O.vb[a],b=c.jb,O.dc(b),c.terminate();O.vb=[]},dc:function(a){if(a){if(a.qb){var b=A()[a.qb+
100>>2];A()[a.qb+100>>2]=0;Q(b);Q(a.qb)}a.qb=0;a.cc&&a.yb&&Q(a.yb);a.yb=0;a.worker&&(a.worker.jb=null)}},Xb:function(a){O.kd(function(){delete O.ob[a.jb.qb];O.tb.push(a);O.vb.splice(O.vb.indexOf(a),1);O.dc(a.jb);a.jb=void 0})},kd:function(a){A()[Bb>>2]=0;try{a()}finally{A()[Bb>>2]=1}},gd:function(){},hc:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.jb&&(O.Lc=a.jb.qb);if(d.targetThread&&d.targetThread!=zb()){var f=O.ob[d.Yd];f?f.worker.postMessage(c.data,d.transferList):console.error('Internal error! Worker sent a message "'+
e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Cb();else if("spawnThread"===e)Db(c.data);else if("cleanupThread"===e)wb(d.thread);else if("killThread"===e){c=d.thread;if(F)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+12>>2]=0;c=O.ob[c];c.worker.terminate();O.dc(c);O.vb.splice(O.vb.indexOf(c.worker),1);c.worker.jb=
void 0}else if("cancelThread"===e){c=d.thread;if(F)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";O.ob[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.Kb&&(a.Kb(),delete a.Kb);else if("print"===e)Da("Thread "+d.threadId+": "+d.text);else if("printErr"===e)G("Thread "+d.threadId+": "+d.text);else if("alert"===e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===
e)a.jb&&Atomics.load(B(),a.jb.qb+64>>2)&&O.Xb(a);else if("exitProcess"===e)try{Eb(d.returnCode)}catch(h){if(h instanceof Fb)return;throw h;}else"cancelDone"===e?O.Xb(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):G("worker sent an unknown command "+e));O.Lc=void 0};a.onerror=function(c){G("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message)};a.postMessage({cmd:"load",urlOrBlob:D.mainScriptUrlOrBlob||_scriptDir,wasmMemory:n,wasmModule:Ga})},Hc:function(){var a=
Ba("BlinkInputWasmSDK.worker.js");O.tb.push(new Worker(a))},Rc:function(){0==O.tb.length&&(O.Hc(),O.hc(O.tb[0]));return 0<O.tb.length?O.tb.pop():null},Fd:function(a){for(a=performance.now()+a;performance.now()<a;);}};D.establishStackSpace=function(a,b){Gb(a,b);Hb(a)};D.getNoExitRuntime=function(){return noExitRuntime};D.invokeEntryPoint=function(a,b){return N.get(a)(b)};var Ib;Ib=F?function(){return performance.now()-D.__performance_now_clock_drift}:function(){return performance.now()};
function Jb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(F)return Kb(2,1);if(!Jb.Jc){Jb.Jc=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Lb()>>2]=60*f;A()[Mb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Sa(c);d=Sa(d);e<b?(A()[Nb()>>2]=c,A()[Nb()+4>>2]=d):(A()[Nb()>>2]=d,A()[Nb()+4>>2]=c)}}var Ob={};function Pb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}
function Qb(a){return this.fromWireType(B()[a>>2])}var Rb={},Sb={},Tb={};function Ub(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Vb(a,b){a=Ub(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Wb(a){var b=Error,c=Vb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Xb=void 0;function Yb(a){throw new Xb(a);}
function Zb(a,b,c){function d(l){l=c(l);l.length!==a.length&&Yb("Mismatched type converter count");for(var m=0;m<a.length;++m)$b(a[m],l[m])}a.forEach(function(l){Tb[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){Sb.hasOwnProperty(l)?e[m]=Sb[l]:(f.push(l),Rb.hasOwnProperty(l)||(Rb[l]=[]),Rb[l].push(function(){e[m]=Sb[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function ac(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var bc=void 0;function R(a){for(var b="";u()[a];)b+=bc[u()[a++]];return b}var cc=void 0;function S(a){throw new cc(a);}
function $b(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||S('type "'+d+'" must have a positive integer typeid pointer');if(Sb.hasOwnProperty(a)){if(c.Wc)return;S("Cannot register type '"+d+"' twice")}Sb[a]=b;delete Tb[a];Rb.hasOwnProperty(a)&&(b=Rb[a],delete Rb[a],b.forEach(function(e){e()}))}function dc(a){return{count:a.count,zb:a.zb,Ib:a.Ib,ab:a.ab,cb:a.cb,hb:a.hb,kb:a.kb}}
function ec(a){S(a.Wa.cb.$a.name+" instance already deleted")}var fc=!1;function gc(){}function hc(a){--a.count.value;0===a.count.value&&(a.hb?a.kb.sb(a.hb):a.cb.$a.sb(a.ab))}
function ic(a){if("undefined"===typeof FinalizationGroup)return ic=function(b){return b},a;fc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.ab?hc(c):console.warn("object already deleted: "+c.ab)});ic=function(b){fc.register(b,b.Wa,b.Wa);return b};gc=function(b){fc.unregister(b.Wa)};return ic(a)}var jc=void 0,kc=[];function lc(){for(;kc.length;){var a=kc.pop();a.Wa.zb=!1;a["delete"]()}}function mc(){}var nc={};
function oc(a,b,c){if(void 0===a[b].fb){var d=a[b];a[b]=function(){a[b].fb.hasOwnProperty(arguments.length)||S("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].fb+")!");return a[b].fb[arguments.length].apply(this,arguments)};a[b].fb=[];a[b].fb[d.Pb]=d}}
function pc(a,b,c){D.hasOwnProperty(a)?((void 0===c||void 0!==D[a].fb&&void 0!==D[a].fb[c])&&S("Cannot register public name '"+a+"' twice"),oc(D,a,a),D.hasOwnProperty(c)&&S("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),D[a].fb[c]=b):(D[a]=b,void 0!==c&&(D[a].Ud=c))}function qc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Cb=c;this.sb=d;this.lb=e;this.Qc=f;this.Mb=h;this.Mc=l;this.ed=[]}
function rc(a,b,c){for(;b!==c;)b.Mb||S("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Mb(a),b=b.lb;return a}function sc(a,b){if(null===b)return this.fc&&S("null is not a valid "+this.name),0;b.Wa||S('Cannot pass "'+tc(b)+'" as a '+this.name);b.Wa.ab||S("Cannot pass deleted object as a pointer of type "+this.name);return rc(b.Wa.ab,b.Wa.cb.$a,this.$a)}
function uc(a,b){if(null===b){this.fc&&S("null is not a valid "+this.name);if(this.Sb){var c=this.jc();null!==a&&a.push(this.sb,c);return c}return 0}b.Wa||S('Cannot pass "'+tc(b)+'" as a '+this.name);b.Wa.ab||S("Cannot pass deleted object as a pointer of type "+this.name);!this.Rb&&b.Wa.cb.Rb&&S("Cannot convert argument of type "+(b.Wa.kb?b.Wa.kb.name:b.Wa.cb.name)+" to parameter type "+this.name);c=rc(b.Wa.ab,b.Wa.cb.$a,this.$a);if(this.Sb)switch(void 0===b.Wa.hb&&S("Passing raw pointer to smart pointer is illegal"),
this.qd){case 0:b.Wa.kb===this?c=b.Wa.hb:S("Cannot convert argument of type "+(b.Wa.kb?b.Wa.kb.name:b.Wa.cb.name)+" to parameter type "+this.name);break;case 1:c=b.Wa.hb;break;case 2:if(b.Wa.kb===this)c=b.Wa.hb;else{var d=b.clone();c=this.fd(c,U(function(){d["delete"]()}));null!==a&&a.push(this.sb,c)}break;default:S("Unsupporting sharing policy")}return c}
function vc(a,b){if(null===b)return this.fc&&S("null is not a valid "+this.name),0;b.Wa||S('Cannot pass "'+tc(b)+'" as a '+this.name);b.Wa.ab||S("Cannot pass deleted object as a pointer of type "+this.name);b.Wa.cb.Rb&&S("Cannot convert argument of type "+b.Wa.cb.name+" to parameter type "+this.name);return rc(b.Wa.ab,b.Wa.cb.$a,this.$a)}function wc(a,b,c){if(b===c)return a;if(void 0===c.lb)return null;a=wc(a,b,c.lb);return null===a?null:c.Mc(a)}var xc={};
function yc(a,b){for(void 0===b&&S("ptr should not be undefined");a.lb;)b=a.Mb(b),a=a.lb;return xc[b]}function zc(a,b){b.cb&&b.ab||Yb("makeClassHandle requires ptr and ptrType");!!b.kb!==!!b.hb&&Yb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return ic(Object.create(a,{Wa:{value:b}}))}
function Ac(a,b,c,d){this.name=a;this.$a=b;this.fc=c;this.Rb=d;this.Sb=!1;this.sb=this.fd=this.jc=this.Bc=this.qd=this.dd=void 0;void 0!==b.lb?this.toWireType=uc:(this.toWireType=d?sc:vc,this.mb=null)}function Bc(a,b,c){D.hasOwnProperty(a)||Yb("Replacing nonexistant public symbol");void 0!==D[a].fb&&void 0!==c?D[a].fb[c]=b:(D[a]=b,D[a].Pb=c)}
function Cc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=D["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=N.get(b).apply(null,c);return d}}function V(a,b){a=R(a);var c=-1!=a.indexOf("j")?Cc(a,b):N.get(b);"function"!==typeof c&&S("unknown function pointer with signature "+a+": "+b);return c}var Dc=void 0;function Ec(a){a=Fc(a);var b=R(a);Q(a);return b}
function Gc(a,b){function c(f){e[f]||Sb[f]||(Tb[f]?Tb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Dc(a+": "+d.map(Ec).join([", "]));}function Hc(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Ic(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Vb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Jc(a,b,c,d,e){var f=b.length;2>f&&S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].mb){l=!0;break}var m="void"!==b[0].name,p="",q="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+Ub(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var y=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[S,d,e,Pb,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+y+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+y+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].mb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].mb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return Ic(p).apply(null,d)}var Kc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Lc(a){4<a&&0===--W[a].lc&&(W[a]=void 0,Kc.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Kc.length?Kc.pop():W.length;W[b]={lc:1,value:a};return b}}function tc(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Mc(a,b){switch(b){case 2:return function(c){return this.fromWireType(ja()[c>>2])};case 3:return function(c){return this.fromWireType(la()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Nc(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return u()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return v()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return B()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Oc(a){a||S("Cannot use deleted val. handle = "+a);return W[a].value}function Pc(a,b){var c=Sb[a];void 0===c&&S(b+" has unknown type "+Ec(a));return c}var Qc={};
function Rc(a){var b=Qc[a];return void 0===b?R(a):b}var Sc=[];function Tc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Uc(a){var b=Sc.length;Sc.push(a);return b}function Vc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Pc(A()[(b>>2)+d],"parameter "+d);return c}var Wc={};
function Xc(){ya||(Ea||(Ea={}),Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ea["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,G("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function Yc(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(xa){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),vb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),vb>>2,0),-73;d=Atomics.exchange(A(),vb>>2,0);if(0==d)break;Cb();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),vb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Kb(a,b){for(var c=arguments.length-2,d=Zc(),e=$c(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];la()[f+h]=l}c=ad(a,c,e,b);Hb(d);return c}var bd=[],cd=[],dd=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function ed(a){a=2<a?J(a):a;return dd[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function fd(a,b,c){var d=ed(a);if(!d)return-4;d.Qb&&(A()[d.Qb>>2]=b,A()[d.Qb+4>>2]=c);if(d.zc||!d.Hd)d.zc&&(d=d.zc),a=!1,d.Ob&&d.Ob.Nb&&(a=d.Ob.Nb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Ob.Nb.viewport(0,0,b,c);else{if(d.Qb){d=A()[d.Qb+8>>2];a=a?J(a):"";var e=Zc(),f=$c(12),h=0;if(a){h=La(a)+1;var l=M(h);L(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;gd(0,d,657457152,0,h,f);Hb(e);return 1}return-4}return 0}
function hd(a,b,c){return F?Kb(3,1,a,b,c):fd(a,b,c)}var id=[];function X(a,b){B()[a>>2]=b;B()[a+4>>2]=b/4294967296|0}function jd(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var kd;
function ld(a,b,c,d,e){function f(C){var T=0,P=0;C&&(P=w.response?w.response.byteLength:0,T=M(P),u().set(new Uint8Array(w.response),T));B()[a+12>>2]=T;X(a+16,P)}var h=B()[a+8>>2];if(h){var l=J(h),m=a+112,p=J(m);p||(p="GET");B();var q=B()[m+52>>2],y=B()[m+56>>2],x=!!B()[m+60>>2];B();var k=B()[m+68>>2],t=B()[m+72>>2],z=B()[m+76>>2],E=B()[m+80>>2];h=B()[m+84>>2];m=B()[m+88>>2];var H=!!(q&1),K=!!(q&2);q=!!(q&64);k=k?J(k):void 0;t=t?J(t):void 0;var qa=E?J(E):void 0,w=new XMLHttpRequest;w.withCredentials=
x;w.open(p,l,!q,k,t);q||(w.timeout=y);w.$d=l;w.responseType="arraybuffer";E&&w.overrideMimeType(qa);if(z)for(;;){p=B()[z>>2];if(!p)break;l=B()[z+4>>2];if(!l)break;z+=8;p=J(p);l=J(l);w.setRequestHeader(p,l)}id.push(w);z=id.length;B()[a+0>>2]=z;h=h&&m?u().slice(h,h+m):null;w.onload=function(C){f(H&&!K);var T=w.response?w.response.byteLength:0;X(a+24,0);T&&X(a+32,T);v()[a+40>>1]=w.readyState;v()[a+42>>1]=w.status;w.statusText&&L(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,C):c&&c(a,w,
C)};w.onerror=function(C){f(H);var T=w.status;X(a+24,0);X(a+32,w.response?w.response.byteLength:0);v()[a+40>>1]=w.readyState;v()[a+42>>1]=T;c&&c(a,w,C)};w.ontimeout=function(C){c&&c(a,w,C)};w.onprogress=function(C){var T=H&&K&&w.response?w.response.byteLength:0,P=0;H&&K&&(P=M(T),u().set(new Uint8Array(w.response),P));B()[a+12>>2]=P;X(a+16,T);X(a+24,C.loaded-T);X(a+32,C.total);v()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<C.loaded&&(w.status=200);v()[a+42>>1]=w.status;w.statusText&&L(w.statusText,
a+44,64);d&&d(a,w,C);P&&Q(P)};w.onreadystatechange=function(C){v()[a+40>>1]=w.readyState;2<=w.readyState&&(v()[a+42>>1]=w.status);e&&e(a,w,C)};try{w.send(h)}catch(C){c&&c(a,w,C)}}else c(a,0,"no url specified!")}
function md(a,b,c,d){var e=kd;if(e){var f=a+112;(f=B()[f+64>>2])||(f=B()[a+8>>2]);var h=J(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){v()[a+40>>1]=4;v()[a+42>>1]=200;L("OK",a+44,64);c(a,0,h)};l.onerror=function(m){v()[a+40>>1]=4;v()[a+42>>1]=413;L("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function nd(a,b,c){var d=kd;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=J(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=M(l);u().set(new Uint8Array(h),m);B()[a+12>>2]=m;X(a+16,l);X(a+24,0);X(a+32,l);v()[a+40>>1]=4;v()[a+42>>1]=200;L("OK",a+44,64);b(a,0,h)}else v()[a+40>>1]=4,v()[a+42>>1]=404,L("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){v()[a+40>>1]=
4;v()[a+42>>1]=404;L("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function od(a,b,c){var d=kd;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=J(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;B()[a+12>>2]=0;X(a+16,0);X(a+24,0);X(a+32,0);v()[a+40>>1]=4;v()[a+42>>1]=200;L("OK",a+44,64);b(a,0,h)};f.onerror=function(h){v()[a+40>>1]=4;v()[a+42>>1]=404;L("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function pd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function qd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function rd(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function sd(a){a||(a=td);if(!a.Xc){a.Xc=!0;var b=a.Nb;pd(b);qd(b);rd(b);b.Kd=b.getExtension("EXT_disjoint_timer_query");b.Sd=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var td,ud=["default","low-power","high-performance"],vd={};
function wd(){if(!xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:va||"./this.program"},b;for(b in vd)a[b]=vd[b];var c=[];for(b in a)c.push(b+"="+a[b]);xd=c}return xd}var xd;
function yd(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function zd(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=yd(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ad(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Bd(a){if("/"===a)return"/";a=zd(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Cd(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){I("randomDevice")}}
function Dd(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=yd(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Ed=[];function Fd(a,b){Ed[a]={input:[],eb:[],Db:b};Gd(a,Hd)}
var Hd={open:function(a){var b=Ed[a.node.Wb];if(!b)throw new Y(43);a.ib=b;a.seekable=!1},close:function(a){a.ib.Db.flush(a.ib)},flush:function(a){a.ib.Db.flush(a.ib)},read:function(a,b,c,d){if(!a.ib||!a.ib.Db.vc)throw new Y(60);for(var e=0,f=0;f<d;f++){try{var h=a.ib.Db.vc(a.ib)}catch(l){throw new Y(29);}if(void 0===h&&0===e)throw new Y(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.ib||!a.ib.Db.ic)throw new Y(60);try{for(var e=
0;e<d;e++)a.ib.Db.ic(a.ib,b[c+e])}catch(f){throw new Y(29);}d&&(a.node.timestamp=Date.now());return e}},Jd={vc:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Id(b,!0)}return a.input.shift()},ic:function(a,b){null===b||10===b?(Da(Ja(a.eb,0)),a.eb=[]):0!=b&&a.eb.push(b)},flush:function(a){a.eb&&0<a.eb.length&&
(Da(Ja(a.eb,0)),a.eb=[])}},Kd={ic:function(a,b){null===b||10===b?(G(Ja(a.eb,0)),a.eb=[]):0!=b&&a.eb.push(b)},flush:function(a){a.eb&&0<a.eb.length&&(G(Ja(a.eb,0)),a.eb=[])}},Z={nb:null,rb:function(){return Z.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Y(63);Z.nb||(Z.nb={dir:{node:{ub:Z.Ya.ub,pb:Z.Ya.pb,Hb:Z.Ya.Hb,Tb:Z.Ya.Tb,Dc:Z.Ya.Dc,Gc:Z.Ya.Gc,Ec:Z.Ya.Ec,Cc:Z.Ya.Cc,Yb:Z.Ya.Yb},stream:{xb:Z.Za.xb}},file:{node:{ub:Z.Ya.ub,pb:Z.Ya.pb},
stream:{xb:Z.Za.xb,read:Z.Za.read,write:Z.Za.write,mc:Z.Za.mc,wc:Z.Za.wc,yc:Z.Za.yc}},link:{node:{ub:Z.Ya.ub,pb:Z.Ya.pb,Jb:Z.Ya.Jb},stream:{}},nc:{node:{ub:Z.Ya.ub,pb:Z.Ya.pb},stream:Ld}});c=Md(a,b,c,d);16384===(c.mode&61440)?(c.Ya=Z.nb.dir.node,c.Za=Z.nb.dir.stream,c.Xa={}):32768===(c.mode&61440)?(c.Ya=Z.nb.file.node,c.Za=Z.nb.file.stream,c.bb=0,c.Xa=null):40960===(c.mode&61440)?(c.Ya=Z.nb.link.node,c.Za=Z.nb.link.stream):8192===(c.mode&61440)&&(c.Ya=Z.nb.nc.node,c.Za=Z.nb.nc.stream);c.timestamp=
Date.now();a&&(a.Xa[b]=c,a.timestamp=c.timestamp);return c},Ld:function(a){return a.Xa?a.Xa.subarray?a.Xa.subarray(0,a.bb):new Uint8Array(a.Xa):new Uint8Array(0)},rc:function(a,b){var c=a.Xa?a.Xa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.Xa,a.Xa=new Uint8Array(b),0<a.bb&&a.Xa.set(c.subarray(0,a.bb),0))},hd:function(a,b){if(a.bb!=b)if(0==b)a.Xa=null,a.bb=0;else{var c=a.Xa;a.Xa=new Uint8Array(b);c&&a.Xa.set(c.subarray(0,Math.min(b,a.bb)));a.bb=b}},Ya:{ub:function(a){var b=
{};b.Jd=8192===(a.mode&61440)?a.id:1;b.Pd=a.id;b.mode=a.mode;b.Td=1;b.uid=0;b.Md=0;b.Wb=a.Wb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.bb:40960===(a.mode&61440)?a.link.length:0;b.Dd=new Date(a.timestamp);b.Rd=new Date(a.timestamp);b.Id=new Date(a.timestamp);b.Ic=4096;b.Ed=Math.ceil(b.size/b.Ic);return b},pb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Z.hd(a,b.size)},Hb:function(){throw Nd[44];},Tb:function(a,b,c,
d){return Z.createNode(a,b,c,d)},Dc:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Od(b,c)}catch(f){}if(d)for(var e in d.Xa)throw new Y(55);}delete a.parent.Xa[a.name];a.parent.timestamp=Date.now();a.name=c;b.Xa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Gc:function(a,b){delete a.Xa[b];a.timestamp=Date.now()},Ec:function(a,b){var c=Od(a,b),d;for(d in c.Xa)throw new Y(55);delete a.Xa[b];a.timestamp=Date.now()},Cc:function(a){var b=[".",".."],c;for(c in a.Xa)a.Xa.hasOwnProperty(c)&&b.push(c);
return b},Yb:function(a,b,c){a=Z.createNode(a,b,41471,0);a.link=c;return a},Jb:function(a){if(40960!==(a.mode&61440))throw new Y(28);return a.link}},Za:{read:function(a,b,c,d,e){var f=a.node.Xa;if(e>=a.node.bb)return 0;a=Math.min(a.node.bb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Xa||a.Xa.subarray)){if(f)return a.Xa=b.subarray(c,
c+d),a.bb=d;if(0===a.bb&&0===e)return a.Xa=b.slice(c,c+d),a.bb=d;if(e+d<=a.bb)return a.Xa.set(b.subarray(c,c+d),e),d}Z.rc(a,e+d);if(a.Xa.subarray&&b.subarray)a.Xa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.Xa[e+f]=b[c+f];a.bb=Math.max(a.bb,e+d);return d},xb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.bb);if(0>b)throw new Y(28);return b},mc:function(a,b,c){Z.rc(a.node,b+c);a.node.bb=Math.max(a.node.bb,b+c)},wc:function(a,b,c,d,e,f){if(0!==b)throw new Y(28);
if(32768!==(a.node.mode&61440))throw new Y(43);a=a.node.Xa;if(f&2||a.buffer!==r){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=M(f);c<f;)g()[b+c++]=0;c=b;if(!c)throw new Y(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{ab:c,Cd:d}},yc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Y(43);if(e&2)return 0;Z.Za.write(a,b,0,d,c,!1);return 0}}},Pd=null,Qd={},Rd=[],Sd=1,Td=null,Ud=!0,Vd={},Y=null,Nd={};
function Wd(a,b){a=Dd("/",a);b=b||{};if(!a)return{path:"",node:null};var c={uc:!0,kc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.kc)throw new Y(32);a=yd(a.split("/").filter(function(h){return!!h}),!1);var e=Pd;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Od(e,a[d]);c=zd(c+"/"+a[d]);e.Ub&&(!f||f&&b.uc)&&(e=e.Ub.root);if(!f||b.tc)for(f=0;40960===(e.mode&61440);)if(e=Xd(c),c=Dd(Ad(c),e),e=Wd(c,{kc:b.kc}).node,40<f++)throw new Y(32);}return{path:c,node:e}}
function Yd(a){for(var b;;){if(a===a.parent)return a=a.rb.xc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Zd(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Td.length}function Od(a,b){var c;if(c=(c=$d(a,"x"))?c:a.Ya.Hb?0:2)throw new Y(c,a);for(c=Td[Zd(a.id,b)];c;c=c.cd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Ya.Hb(a,b)}
function Md(a,b,c,d){a=new ae(a,b,c,d);b=Zd(a.parent.id,a.name);a.cd=Td[b];return Td[b]=a}var be={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function ce(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function $d(a,b){if(Ud)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function de(a,b){try{return Od(a,b),20}catch(c){}return $d(a,"wx")}
function ee(){var a=4096;for(var b=0;b<=a;b++)if(!Rd[b])return b;throw new Y(33);}function fe(a){ge||(ge=function(){},ge.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new ge,c;for(c in a)b[c]=a[c];a=b;b=ee();a.Bb=b;return Rd[b]=a}var Ld={open:function(a){a.Za=Qd[a.node.Wb].Za;a.Za.open&&a.Za.open(a)},xb:function(){throw new Y(70);}};function Gd(a,b){Qd[a]={Za:b}}
function he(a,b){var c="/"===b,d=!b;if(c&&Pd)throw new Y(10);if(!c&&!d){var e=Wd(b,{uc:!1});b=e.path;e=e.node;if(e.Ub)throw new Y(10);if(16384!==(e.mode&61440))throw new Y(54);}b={type:a,Vd:{},xc:b,bd:[]};a=a.rb(b);a.rb=b;b.root=a;c?Pd=a:e&&(e.Ub=b,e.rb&&e.rb.bd.push(b))}function ie(a,b,c){var d=Wd(a,{parent:!0}).node;a=Bd(a);if(!a||"."===a||".."===a)throw new Y(28);var e=de(d,a);if(e)throw new Y(e);if(!d.Ya.Tb)throw new Y(63);return d.Ya.Tb(d,a,b,c)}function je(a){return ie(a,16895,0)}
function ke(a,b,c){"undefined"===typeof c&&(c=b,b=438);ie(a,b|8192,c)}function db(a,b){if(!Dd(a))throw new Y(44);var c=Wd(b,{parent:!0}).node;if(!c)throw new Y(44);b=Bd(b);var d=de(c,b);if(d)throw new Y(d);if(!c.Ya.Yb)throw new Y(63);c.Ya.Yb(c,b,a)}function Xd(a){a=Wd(a).node;if(!a)throw new Y(44);if(!a.Ya.Jb)throw new Y(28);return Dd(Yd(a.parent),a.Ya.Jb(a))}
function eb(a,b){if(""===a)throw new Y(44);if("string"===typeof b){var c=be[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=zd(a);try{e=Wd(a,{tc:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new Y(20);}else e=ie(a,d,0),c=!0;if(!e)throw new Y(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Y(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==ce(b)||b&512)?31:$d(e,ce(b)):44))throw new Y(d);if(b&512){d=e;d="string"===typeof d?Wd(d,{tc:!0}).node:d;if(!d.Ya.pb)throw new Y(63);if(16384===(d.mode&61440))throw new Y(31);if(32768!==(d.mode&61440))throw new Y(28);if(c=$d(d,"w"))throw new Y(c);d.Ya.pb(d,{size:0,timestamp:Date.now()})}b&=-131713;e=fe({node:e,path:Yd(e),flags:b,seekable:!0,position:0,Za:e.Za,Ad:[],error:!1});e.Za.open&&e.Za.open(e);!D.logReadFiles||b&1||(le||(le={}),a in le||(le[a]=1,G("FS.trackingDelegate error on read file: "+
a)));try{Vd.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Vd.onOpenFile(a,e))}catch(f){G("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}}function me(a,b,c){if(null===a.Bb)throw new Y(8);if(!a.seekable||!a.Za.xb)throw new Y(70);if(0!=c&&1!=c&&2!=c)throw new Y(28);a.position=a.Za.xb(a,b,c);a.Ad=[]}
function bb(){Y||(Y=function(a,b){this.node=b;this.ld=function(c){this.Ab=c};this.ld(a);this.message="FS error"},Y.prototype=Error(),Y.prototype.constructor=Y,[44].forEach(function(a){Nd[a]=new Y(a);Nd[a].stack="<generic error, no stack>"}))}var ab;function ne(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function cb(a,b,c){a=zd("/dev/"+a);var d=ne(!!b,!!c);oe||(oe=64);var e=oe++<<8|0;Gd(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,m){for(var p=0,q=0;q<m;q++){try{var y=b()}catch(x){throw new Y(29);}if(void 0===y&&0===p)throw new Y(6);if(null===y||void 0===y)break;p++;h[l+q]=y}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{c(h[l+p])}catch(q){throw new Y(29);}m&&(f.node.timestamp=Date.now());return p}});
ke(a,d,e)}var oe,pe={},ge,le;function qe(a){a=Rd[a];if(!a)throw new Y(8);return a}function re(a,b){if(F)return Kb(4,1,a,b);try{var c=0;wd().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof pe&&d instanceof Y||I(d),d.Ab}}
function se(a,b){if(F)return Kb(5,1,a,b);try{var c=wd();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}catch(e){return"undefined"!==typeof pe&&e instanceof Y||I(e),e.Ab}}function te(a){if(F)return Kb(6,1,a);try{var b=qe(a);if(null===b.Bb)throw new Y(8);b.ec&&(b.ec=null);try{b.Za.close&&b.Za.close(b)}catch(c){throw c;}finally{Rd[b.Bb]=null}b.Bb=null;return 0}catch(c){return"undefined"!==typeof pe&&c instanceof Y||I(c),c.Ab}}
function ue(a,b,c,d){if(F)return Kb(7,1,a,b,c,d);try{a:{for(var e=qe(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,p=g(),q=h,y=l,x=void 0;if(0>y||0>x)throw new Y(28);if(null===m.Bb)throw new Y(8);if(1===(m.flags&2097155))throw new Y(8);if(16384===(m.node.mode&61440))throw new Y(31);if(!m.Za.read)throw new Y(28);var k="undefined"!==typeof x;if(!k)x=m.position;else if(!m.seekable)throw new Y(70);var t=m.Za.read(m,p,q,y,x);k||(m.position+=t);var z=t;if(0>z){var E=-1;break a}a+=z;if(z<
l)break}E=a}A()[d>>2]=E;return 0}catch(H){return"undefined"!==typeof pe&&H instanceof Y||I(H),H.Ab}}
function ve(a,b,c,d,e){if(F)return Kb(8,1,a,b,c,d,e);try{var f=qe(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;me(f,a,d);rb=[f.position>>>0,(qb=f.position,1<=+Math.abs(qb)?0<qb?(Math.min(+Math.floor(qb/4294967296),4294967295)|0)>>>0:~~+Math.ceil((qb-+(~~qb>>>0))/4294967296)>>>0:0)];A()[e>>2]=rb[0];A()[e+4>>2]=rb[1];f.ec&&0===a&&0===d&&(f.ec=null);return 0}catch(h){return"undefined"!==typeof pe&&h instanceof Y||I(h),h.Ab}}
function we(a,b,c,d){if(F)return Kb(9,1,a,b,c,d);try{a:{for(var e=qe(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,p=g(),q=h,y=l,x=void 0;if(0>y||0>x)throw new Y(28);if(null===m.Bb)throw new Y(8);if(0===(m.flags&2097155))throw new Y(8);if(16384===(m.node.mode&61440))throw new Y(31);if(!m.Za.write)throw new Y(28);m.seekable&&m.flags&1024&&me(m,0,2);var k="undefined"!==typeof x;if(!k)x=m.position;else if(!m.seekable)throw new Y(70);var t=m.Za.write(m,p,q,y,x,void 0);k||(m.position+=
t);try{if(m.path&&Vd.onWriteToFile)Vd.onWriteToFile(m.path)}catch(H){G("FS.trackingDelegate['onWriteToFile']('"+m.path+"') threw an exception: "+H.message)}var z=t;if(0>z){var E=-1;break a}a+=z}E=a}A()[d>>2]=E;return 0}catch(H){return"undefined"!==typeof pe&&H instanceof Y||I(H),H.Ab}}function xe(a,b){xe.Ac||(xe.Ac=Cd());for(var c=0;c<b;c++)g()[a+c>>0]=xe.Ac();return 0}
function Db(a){if(F)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=O.Rc();if(void 0!==b.jb)throw"Internal error!";if(!a.Vb)throw"Internal error, no pthread ptr!";O.vb.push(b);for(var c=M(512),d=0;128>d;++d)A()[c+4*d>>2]=0;var e=a.yb+a.Eb;d=O.ob[a.Vb]={worker:b,yb:a.yb,Eb:a.Eb,cc:a.cc,qb:a.Vb};var f=d.qb>>2;Atomics.store(B(),f+16,a.pc);Atomics.store(B(),f+25,c);Atomics.store(B(),f+10,d.qb);Atomics.store(B(),f+20,a.Eb);Atomics.store(B(),f+19,e);Atomics.store(B(),
f+26,a.Eb);Atomics.store(B(),f+28,e);Atomics.store(B(),f+29,a.pc);c=ye()+40;Atomics.store(B(),f+43,c);b.jb=d;var h={cmd:"run",start_routine:a.rd,arg:a.Gb,threadInfoStruct:a.Vb,stackBase:a.yb,stackSize:a.Eb};b.Kb=function(){h.time=performance.now();b.postMessage(h,a.zd)};b.loaded&&(b.Kb(),delete b.Kb)}
function ze(a,b){if(!a)return G("pthread_join attempted on a null thread pointer!"),71;if(F&&zb()==a)return G("PThread "+a+" is attempting to join to itself!"),16;if(!F&&Ae()==a)return G("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+12>>2]!==a)return G("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(B(),a+64>>2))return G("Attempted to join thread "+a+", which was already detached!"),28;for(Xc();;){var c=
Atomics.load(B(),a+0>>2);if(1==c)return c=Atomics.load(B(),a+4>>2),b&&(A()[b>>2]=c),Atomics.store(B(),a+64>>2,1),F?postMessage({cmd:"cleanupThread",thread:a}):wb(a),0;if(F){var d=zb();if(d&&!Atomics.load(B(),d+56>>2)&&2==Atomics.load(B(),d+0>>2))throw"Canceled!";}F||Cb();Yc(a+0,c,F?100:1)}}function Be(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ce(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var De=[31,29,31,30,31,30,31,31,30,31,30,31],Ee=[31,28,31,30,31,30,31,31,30,31,30,31];
function Fe(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Be(a.getFullYear())?De:Ee)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ge(a,b,c,d){function e(k,t,z){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=z[0]+k;return k}function f(k,t){return e(k,t,"0")}function h(k,t){function z(H){return 0>H?-1:0<H?1:0}var E;0===(E=z(k.getFullYear()-t.getFullYear()))&&0===(E=z(k.getMonth()-t.getMonth()))&&(E=z(k.getDate()-t.getDate()));return E}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Fe(new Date(k.gb+1900,0,1),k.bc);var t=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));t=l(t);return 0>=h(z,k)?0>=h(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=A()[d+40>>2];d={xd:A()[d>>2],wd:A()[d+4>>2],$b:A()[d+8>>2],Lb:A()[d+12>>2],Fb:A()[d+16>>2],gb:A()[d+20>>2],ac:A()[d+24>>2],bc:A()[d+28>>2],Zd:A()[d+
32>>2],vd:A()[d+36>>2],yd:p?J(p):""};c=J(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var y="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
x="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return y[k.ac].substring(0,3)},"%A":function(k){return y[k.ac]},"%b":function(k){return x[k.Fb].substring(0,3)},"%B":function(k){return x[k.Fb]},"%C":function(k){return f((k.gb+1900)/100|0,2)},"%d":function(k){return f(k.Lb,2)},"%e":function(k){return e(k.Lb,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.$b,
2)},"%I":function(k){k=k.$b;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.Lb+Ce(Be(k.gb+1900)?De:Ee,k.Fb-1),3)},"%m":function(k){return f(k.Fb+1,2)},"%M":function(k){return f(k.wd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.$b&&12>k.$b?"AM":"PM"},"%S":function(k){return f(k.xd,2)},"%t":function(){return"\t"},"%u":function(k){return k.ac||7},"%U":function(k){var t=new Date(k.gb+1900,0,1),z=0===t.getDay()?t:Fe(t,7-t.getDay());k=new Date(k.gb+1900,k.Fb,k.Lb);return 0>
h(z,k)?f(Math.ceil((31-z.getDate()+(Ce(Be(k.getFullYear())?De:Ee,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%V":function(k){var t=new Date(k.gb+1901,0,4),z=l(new Date(k.gb+1900,0,4));t=l(t);var E=Fe(new Date(k.gb+1900,0,1),k.bc);return 0>h(E,z)?"53":0>=h(t,E)?"01":f(Math.ceil((z.getFullYear()<k.gb+1900?k.bc+32-z.getDate():k.bc+1-z.getDate())/7),2)},"%w":function(k){return k.ac},"%W":function(k){var t=new Date(k.gb,0,1),z=1===t.getDay()?t:Fe(t,0===t.getDay()?1:7-t.getDay()+1);k=
new Date(k.gb+1900,k.Fb,k.Lb);return 0>h(z,k)?f(Math.ceil((31-z.getDate()+(Ce(Be(k.getFullYear())?De:Ee,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%y":function(k){return(k.gb+1900).toString().substring(2)},"%Y":function(k){return k.gb+1900},"%z":function(k){k=k.vd;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.yd},"%%":function(){return"%"}};for(q in p)0<=c.indexOf(q)&&(c=c.replace(new RegExp(q,"g"),p[q](d)));q=
Id(c,!1);if(q.length>b)return 0;Ta(q,a);return q.length-1}Xb=D.InternalError=Wb("InternalError");for(var He=Array(256),Ie=0;256>Ie;++Ie)He[Ie]=String.fromCharCode(Ie);bc=He;cc=D.BindingError=Wb("BindingError");mc.prototype.isAliasOf=function(a){if(!(this instanceof mc&&a instanceof mc))return!1;var b=this.Wa.cb.$a,c=this.Wa.ab,d=a.Wa.cb.$a;for(a=a.Wa.ab;b.lb;)c=b.Mb(c),b=b.lb;for(;d.lb;)a=d.Mb(a),d=d.lb;return b===d&&c===a};
mc.prototype.clone=function(){this.Wa.ab||ec(this);if(this.Wa.Ib)return this.Wa.count.value+=1,this;var a=ic(Object.create(Object.getPrototypeOf(this),{Wa:{value:dc(this.Wa)}}));a.Wa.count.value+=1;a.Wa.zb=!1;return a};mc.prototype["delete"]=function(){this.Wa.ab||ec(this);this.Wa.zb&&!this.Wa.Ib&&S("Object already scheduled for deletion");gc(this);hc(this.Wa);this.Wa.Ib||(this.Wa.hb=void 0,this.Wa.ab=void 0)};mc.prototype.isDeleted=function(){return!this.Wa.ab};
mc.prototype.deleteLater=function(){this.Wa.ab||ec(this);this.Wa.zb&&!this.Wa.Ib&&S("Object already scheduled for deletion");kc.push(this);1===kc.length&&jc&&jc(lc);this.Wa.zb=!0;return this};Ac.prototype.Sc=function(a){this.Bc&&(a=this.Bc(a));return a};Ac.prototype.oc=function(a){this.sb&&this.sb(a)};Ac.prototype.argPackAdvance=8;Ac.prototype.readValueFromPointer=Qb;Ac.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Ac.prototype.fromWireType=function(a){function b(){return this.Sb?zc(this.$a.Cb,{cb:this.dd,ab:c,kb:this,hb:a}):zc(this.$a.Cb,{cb:this,ab:a})}var c=this.Sc(a);if(!c)return this.oc(a),null;var d=yc(this.$a,c);if(void 0!==d){if(0===d.Wa.count.value)return d.Wa.ab=c,d.Wa.hb=a,d.clone();d=d.clone();this.oc(a);return d}d=this.$a.Qc(c);d=nc[d];if(!d)return b.call(this);d=this.Rb?d.Kc:d.pointerType;var e=wc(c,this.$a,d.$a);return null===e?b.call(this):this.Sb?zc(d.$a.Cb,{cb:d,ab:e,kb:this,hb:a}):zc(d.$a.Cb,
{cb:d,ab:e})};D.getInheritedInstanceCount=function(){return Object.keys(xc).length};D.getLiveInheritedInstances=function(){var a=[],b;for(b in xc)xc.hasOwnProperty(b)&&a.push(xc[b]);return a};D.flushPendingDeletes=lc;D.setDelayFunction=function(a){jc=a;kc.length&&jc&&jc(lc)};Dc=D.UnboundTypeError=Wb("UnboundTypeError");D.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};D.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
F||(jd(function(a){kd=a;lb()},function(){kd=!1;lb()}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||kb());function ae(a,b,c,d){a||(a=this);this.parent=a;this.rb=a.rb;this.Ub=null;this.id=Sd++;this.name=b;this.mode=c;this.Ya={};this.Za={};this.Wb=d}
Object.defineProperties(ae.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});bb();Td=Array(4096);he(Z,"/");je("/tmp");je("/home");je("/home/web_user");
(function(){je("/dev");Gd(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ke("/dev/null",259);Fd(1280,Jd);Fd(1536,Kd);ke("/dev/tty",1280);ke("/dev/tty1",1536);var a=Cd();cb("random",a);cb("urandom",a);je("/dev/shm");je("/dev/shm/tmp")})();
(function(){je("/proc");var a=je("/proc/self");je("/proc/self/fd");he({rb:function(){var b=Md(a,"fd",16895,73);b.Ya={Hb:function(c,d){var e=Rd[+d];if(!e)throw new Y(8);c={parent:null,rb:{xc:"fake"},Ya:{Jb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Je=[null,function(a,b){if(F)return Kb(1,1,a,b)},Jb,hd,re,se,te,ue,ve,we];function Id(a,b){var c=Array(La(a)+1);a=Ka(a,c,0,c.length);b&&(c.length=a);return c}
var Me={i:function(a,b,c,d){I("Assertion failed: "+J(a)+", at: "+[b?J(b):"unknown filename",c,d?J(d):"unknown function"])},Y:function(a,b){Jb();a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),
6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Nb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},c:function(a){var b=Ob[a];delete Ob[a];var c=b.jc,d=b.sb,e=b.sc,f=e.map(function(h){return h.Vc}).concat(e.map(function(h){return h.od}));Zb([a],f,function(h){var l={};e.forEach(function(m,p){var q=h[p],y=m.Tc,x=m.Uc,k=h[p+e.length],t=m.nd,z=m.pd;l[m.Oc]={read:function(E){return q.fromWireType(y(x,E))},write:function(E,H){var K=[];t(z,E,
k.toWireType(K,H));Pb(K)}}});return[{name:b.name,fromWireType:function(m){var p={},q;for(q in l)p[q]=l[q].read(m);d(m);return p},toWireType:function(m,p){for(var q in l)if(!(q in p))throw new TypeError('Missing field:  "'+q+'"');var y=c();for(q in l)l[q].write(y,p[q]);null!==m&&m.push(d,y);return y},argPackAdvance:8,readValueFromPointer:Qb,mb:d}]})},ca:function(a,b,c,d,e){var f=ac(c);b=R(b);$b(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===
c)var l=g();else if(2===c)l=da();else if(4===c)l=A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},mb:null})},o:function(a,b,c,d,e,f,h,l,m,p,q,y,x){q=R(q);f=V(e,f);l&&(l=V(h,l));p&&(p=V(m,p));x=V(y,x);var k=Ub(q);pc(k,function(){Gc("Cannot construct "+q+" due to unbound types",[d])});Zb([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var z=t.$a;var E=z.Cb}else E=mc.prototype;t=Vb(k,function(){if(Object.getPrototypeOf(this)!==H)throw new cc("Use 'new' to construct "+
q);if(void 0===K.wb)throw new cc(q+" has no accessible constructor");var w=K.wb[arguments.length];if(void 0===w)throw new cc("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(K.wb).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(E,{constructor:{value:t}});t.prototype=H;var K=new qc(q,t,H,x,z,f,l,p);z=new Ac(q,K,!0,!1);E=new Ac(q+"*",K,!1,!1);var qa=new Ac(q+" const*",K,!1,!0);nc[a]={pointerType:E,
Kc:qa};Bc(k,t);return[z,E,qa]})},r:function(a,b,c,d,e,f){Ia(0<b);var h=Hc(b,c);e=V(d,e);var l=[f],m=[];Zb([],[a],function(p){p=p[0];var q="constructor "+p.name;void 0===p.$a.wb&&(p.$a.wb=[]);if(void 0!==p.$a.wb[b-1])throw new cc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+p.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");p.$a.wb[b-1]=function(){Gc("Cannot construct "+p.name+" due to unbound types",
h)};Zb([],h,function(y){p.$a.wb[b-1]=function(){arguments.length!==b-1&&S(q+" called with "+arguments.length+" arguments, expected "+(b-1));m.length=0;l.length=b;for(var x=1;x<b;++x)l[x]=y[x].toWireType(m,arguments[x-1]);x=e.apply(null,l);Pb(m);return y[0].fromWireType(x)};return[]});return[]})},e:function(a,b,c,d,e,f,h,l){var m=Hc(c,d);b=R(b);f=V(e,f);Zb([],[a],function(p){function q(){Gc("Cannot call "+y+" due to unbound types",m)}p=p[0];var y=p.name+"."+b;l&&p.$a.ed.push(b);var x=p.$a.Cb,k=x[b];
void 0===k||void 0===k.fb&&k.className!==p.name&&k.Pb===c-2?(q.Pb=c-2,q.className=p.name,x[b]=q):(oc(x,b,y),x[b].fb[c-2]=q);Zb([],m,function(t){t=Jc(y,t,p,f,h);void 0===x[b].fb?(t.Pb=c-2,x[b]=t):x[b].fb[c-2]=t;return[]});return[]})},ba:function(a,b){b=R(b);$b(a,{name:b,fromWireType:function(c){var d=W[c].value;Lc(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:Qb,mb:null})},D:function(a,b,c){c=ac(c);b=R(b);$b(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,
e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+tc(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Mc(b,c),mb:null})},w:function(a,b,c,d,e,f){var h=Hc(b,c);a=R(a);e=V(d,e);pc(a,function(){Gc("Cannot call "+a+" due to unbound types",h)},b-1);Zb([],h,function(l){Bc(a,Jc(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},h:function(a,b,c,d,e){function f(p){return p}b=R(b);-1===e&&(e=4294967295);var h=ac(c);if(0===d){var l=32-8*c;f=
function(p){return p<<l>>>l}}var m=-1!=b.indexOf("unsigned");$b(a,{name:b,fromWireType:f,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+tc(q)+'" to '+this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+tc(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Nc(b,h,0!==d),mb:null})},f:function(a,b,c){function d(f){f>>=
2;var h=B();return new e(r,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=R(c);$b(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Wc:!0})},E:function(a,b){b=R(b);var c="std::string"===b;$b(a,{name:b,fromWireType:function(d){var e=B()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==u()[l]){f=J(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=
String.fromCharCode(u()[d+4+h]);m=m.join("")}Q(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||S("Cannot pass non-string to std::string");var h=(c&&f?function(){return La(e)}:function(){return e.length})(),l=M(4+h+1);B()[l>>2]=h;if(c&&f)L(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(Q(l),S("String has UTF-16 code units that do not fit in 8 bits"));
u()[l+4+f]=m}else for(f=0;f<h;++f)u()[l+4+f]=e[f];null!==d&&d.push(Q,l);return l},argPackAdvance:8,readValueFromPointer:Qb,mb:function(d){Q(d)}})},u:function(a,b,c){c=R(c);if(2===b){var d=Ma;var e=Na;var f=Oa;var h=function(){return v()};var l=1}else 4===b&&(d=Pa,e=Qa,f=Ra,h=function(){return B()},l=2);$b(a,{name:c,fromWireType:function(m){for(var p=B()[m>>2],q=h(),y,x=m+4,k=0;k<=p;++k){var t=m+4+k*b;if(k==p||0==q[t>>l])x=d(x,t-x),void 0===y?y=x:(y+=String.fromCharCode(0),y+=x),x=t+b}Q(m);return y},
toWireType:function(m,p){"string"!==typeof p&&S("Cannot pass non-string to C++ string type "+c);var q=f(p),y=M(4+q+b);B()[y>>2]=q>>l;e(p,y+4,q+b);null!==m&&m.push(Q,y);return y},argPackAdvance:8,readValueFromPointer:Qb,mb:function(m){Q(m)}})},d:function(a,b,c,d,e,f){Ob[a]={name:R(b),jc:V(c,d),sb:V(e,f),sc:[]}},b:function(a,b,c,d,e,f,h,l,m,p){Ob[a].sc.push({Oc:R(b),Vc:c,Tc:V(d,e),Uc:f,od:h,nd:V(l,m),pd:p})},da:function(a,b){b=R(b);$b(a,{$c:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},
$:function(a){delete id[a-1]},T:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(F)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=O.ob[a])&&a.worker;if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},l:function(a,b,c){a=Oc(a);b=Pc(b,"emval::as");var d=[],e=U(d);A()[c>>2]=e;return b.toWireType(d,a)},q:function(a,b,c,d){a=Sc[a];b=Oc(b);c=Rc(c);a(b,c,null,d)},x:Lc,ka:function(a){if(0===a)return U(Tc());a=Rc(a);return U(Tc()[a])},p:function(a,
b){b=Vc(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+Ub("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+=
"    argType"+l+".deleteObject(arg"+l+");\n");c.$c||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Ic(e).apply(null,f);return Uc(a)},na:function(a){a=Rc(a);return U(D[a])},m:function(a,b){a=Oc(a);b=Oc(b);return U(a[b])},I:function(a){4<a&&(W[a].lc+=1)},v:function(a,b,c,d){a=Oc(a);var e=Wc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+
f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Pc,D,U);Wc[b]=e}return e(a,c,d)},ia:function(){return U([])},ma:function(a){return U(Rc(a))},ja:function(){return U({})},la:function(a){Pb(W[a].value);Lc(a)},t:function(a,b,c){a=Oc(a);b=Oc(b);c=Oc(c);a[b]=c},k:function(a,b){a=Pc(a,
"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},H:function(){I()},pa:function(){var a=D.allowedThreads;return a?a:navigator.hardwareConcurrency},y:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=Ib();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0},g:function(a,b,c){cd.length=0;var d;for(c>>=2;d=u()[b++];)(d=105>d)&&c&1&&c++,cd.push(d?la()[c++>>1]:A()[c]),++c;return tb[a].apply(null,cd)},V:Xc,A:function(){},n:Yc,j:ub,s:Ib,oa:function(){return"undefined"!==
typeof SharedArrayBuffer},M:function(a,b,c){u().copyWithin(a,b,b+c)},Q:function(a,b,c){bd.length=b;c>>=3;for(var d=0;d<b;d++)bd[d]=la()[c+d];return(0>a?tb[-a-1]:Je[a]).apply(null,bd)},N:function(a){var b=u().length;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-r.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},R:function(a,
b,c){return ed(a)?fd(a,b,c):hd(a,b,c)},z:function(){},aa:function(a,b,c,d,e){function f(C){ld(C,h,p,q,m)}function h(C,T){md(C,T.response,function(P){t?N.get(t)(P):b&&b(P)},function(P){t?N.get(t)(P):b&&b(P)})}function l(C){ld(C,y,p,q,m)}function m(C){H?N.get(H)(C):e&&e(C)}function p(C){z?N.get(z)(C):c&&c(C)}function q(C){E?N.get(E)(C):d&&d(C)}function y(C){t?N.get(t)(C):b&&b(C)}noExitRuntime=!0;var x=a+112,k=J(x),t=B()[x+36>>2],z=B()[x+40>>2],E=B()[x+44>>2],H=B()[x+48>>2],K=B()[x+52>>2],qa=!!(K&4),
w=!!(K&32);K=!!(K&16);if("EM_IDB_STORE"===k)k=B()[x+84>>2],md(a,u().slice(k,k+B()[x+88>>2]),y,p);else if("EM_IDB_DELETE"===k)od(a,y,p);else if(K){if(w)return 0;ld(a,qa?h:y,p,q,m)}else nd(a,y,w?p:qa?f:l);return a},S:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:ud[c],failIfMajorPerformanceCaveat:!!A()[b+7],ad:A()[b+8],Qd:A()[b+9],qc:A()[b+10],Nc:A()[b+11],
Wd:A()[b+12],Xd:A()[b+13]};a=ed(a);if(!a||b.Nc)b=0;else if(a=a.getContext("webgl",b)){c=M(8);A()[c+4>>2]=zb();var d={Nd:c,attributes:b,version:b.ad,Nb:a};a.canvas&&(a.canvas.Ob=d);("undefined"===typeof b.qc||b.qc)&&sd(d);b=c}else b=0;return b},W:re,X:se,ha:function(a){Eb(a)},_:te,Z:ue,J:ve,C:we,fa:function(){var a=self.navigator.userAgent,b=La(a)+1,c=M(b);L(a,c,b);return c},O:xe,L:function(){O.Yc()},a:n||D.wasmMemory,ga:function(a){Jb();var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+
8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();
return b.getTime()/1E3|0},U:function(a){var b=O.Zb.pop();a&&b()},B:function(a,b){O.Zb.push(function(){N.get(a)(b)})},F:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return G("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return G("pthread_create called with a null thread pointer!"),28;var e=[];if(F&&0===e.length)return Ke(687865856,a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;
(b=0==f)?f=Le(16,l):(f-=l,Ia(0<f));for(var m=M(228),p=0;57>p;++p)B()[(m>>2)+p]=0;A()[a>>2]=m;A()[m+12>>2]=m;a=m+152;A()[a>>2]=a;c={yb:f,Eb:l,cc:b,pc:h,rd:c,Vb:m,Gb:d,zd:e};F?(c.Gd="spawnThread",postMessage(c,e)):Db(c);return 0},ea:function(a,b){return ze(a,b)},K:function(){},G:Ge,P:function(a,b,c,d){return Ge(a,b,c,d)}};
(function(){function a(e,f){D.asm=e.exports;N=D.asm.Qa;Ga=f;F||lb()}function b(e){a(e.instance,e.module)}function c(e){return pb().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){G("failed to asynchronously prepare wasm: "+f);I(f)})}var d={a:Me};F||kb();if(D.instantiateWasm)try{return D.instantiateWasm(d,a)}catch(e){return G("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Fa||"function"!==typeof WebAssembly.instantiateStreaming||mb()||"function"!==
typeof fetch?c(b):fetch(nb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){G("wasm streaming compile failed: "+f);G("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(oa);return{}})();
var Za=D.___wasm_call_ctors=function(){return(Za=D.___wasm_call_ctors=D.asm.qa).apply(null,arguments)},Q=D._free=function(){return(Q=D._free=D.asm.ra).apply(null,arguments)},M=D._malloc=function(){return(M=D._malloc=D.asm.sa).apply(null,arguments)},zb=D._pthread_self=function(){return(zb=D._pthread_self=D.asm.ta).apply(null,arguments)},Fc=D.___getTypeName=function(){return(Fc=D.___getTypeName=D.asm.ua).apply(null,arguments)};
D.___embind_register_native_and_builtin_types=function(){return(D.___embind_register_native_and_builtin_types=D.asm.va).apply(null,arguments)};
var ye=D._emscripten_get_global_libc=function(){return(ye=D._emscripten_get_global_libc=D.asm.wa).apply(null,arguments)},Nb=D.__get_tzname=function(){return(Nb=D.__get_tzname=D.asm.xa).apply(null,arguments)},Mb=D.__get_daylight=function(){return(Mb=D.__get_daylight=D.asm.ya).apply(null,arguments)},Lb=D.__get_timezone=function(){return(Lb=D.__get_timezone=D.asm.za).apply(null,arguments)},Ae=D._emscripten_main_browser_thread_id=function(){return(Ae=D._emscripten_main_browser_thread_id=D.asm.Aa).apply(null,
arguments)},Ab=D.___pthread_tsd_run_dtors=function(){return(Ab=D.___pthread_tsd_run_dtors=D.asm.Ba).apply(null,arguments)},Cb=D._emscripten_main_thread_process_queued_calls=function(){return(Cb=D._emscripten_main_thread_process_queued_calls=D.asm.Ca).apply(null,arguments)};D._emscripten_current_thread_process_queued_calls=function(){return(D._emscripten_current_thread_process_queued_calls=D.asm.Da).apply(null,arguments)};
var yb=D._emscripten_register_main_browser_thread_id=function(){return(yb=D._emscripten_register_main_browser_thread_id=D.asm.Ea).apply(null,arguments)},sb=D.__emscripten_do_dispatch_to_thread=function(){return(sb=D.__emscripten_do_dispatch_to_thread=D.asm.Fa).apply(null,arguments)},Ke=D._emscripten_sync_run_in_main_thread_4=function(){return(Ke=D._emscripten_sync_run_in_main_thread_4=D.asm.Ga).apply(null,arguments)},ad=D._emscripten_run_in_main_runtime_thread_js=function(){return(ad=D._emscripten_run_in_main_runtime_thread_js=
D.asm.Ha).apply(null,arguments)},gd=D.__emscripten_call_on_thread=function(){return(gd=D.__emscripten_call_on_thread=D.asm.Ia).apply(null,arguments)};D._emscripten_tls_init=function(){return(D._emscripten_tls_init=D.asm.Ja).apply(null,arguments)};
var xb=D.__emscripten_thread_init=function(){return(xb=D.__emscripten_thread_init=D.asm.Ka).apply(null,arguments)},Zc=D.stackSave=function(){return(Zc=D.stackSave=D.asm.La).apply(null,arguments)},Hb=D.stackRestore=function(){return(Hb=D.stackRestore=D.asm.Ma).apply(null,arguments)},$c=D.stackAlloc=function(){return($c=D.stackAlloc=D.asm.Na).apply(null,arguments)},Gb=D._emscripten_stack_set_limits=function(){return(Gb=D._emscripten_stack_set_limits=D.asm.Oa).apply(null,arguments)},Le=D._memalign=function(){return(Le=
D._memalign=D.asm.Pa).apply(null,arguments)};D.dynCall_jiji=function(){return(D.dynCall_jiji=D.asm.Ra).apply(null,arguments)};D.dynCall_viijii=function(){return(D.dynCall_viijii=D.asm.Sa).apply(null,arguments)};D.dynCall_iiiiiijj=function(){return(D.dynCall_iiiiiijj=D.asm.Ta).apply(null,arguments)};D.dynCall_iiiiij=function(){return(D.dynCall_iiiiij=D.asm.Ua).apply(null,arguments)};D.dynCall_iiiiijj=function(){return(D.dynCall_iiiiijj=D.asm.Va).apply(null,arguments)};
var Bb=D.__emscripten_allow_main_runtime_queued_calls=124964,vb=D.__emscripten_main_thread_futex=711448;D.PThread=O;D.PThread=O;D.wasmMemory=n;D.ExitStatus=Fb;var Ne;function Fb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}jb=function Oe(){Ne||Pe();Ne||(jb=Oe)};
function Pe(){function a(){if(!Ne&&(Ne=!0,D.calledRun=!0,!Ha)){$a();F||(Ud=!1,fb(Xa));na(D);if(D.onRuntimeInitialized)D.onRuntimeInitialized();if(!F){if(D.postRun)for("function"==typeof D.postRun&&(D.postRun=[D.postRun]);D.postRun.length;){var b=D.postRun.shift();Ya.unshift(b)}fb(Ya)}}}if(!(0<hb))if(F)na(D),$a(),postMessage({cmd:"loaded"});else{if(!F){if(D.preRun)for("function"==typeof D.preRun&&(D.preRun=[D.preRun]);D.preRun.length;)gb();fb(Va)}0<hb||(D.setStatus?(D.setStatus("Running..."),setTimeout(function(){setTimeout(function(){D.setStatus("")},
1);a()},1)):a())}}D.run=Pe;function Eb(a){if(F)throw postMessage({cmd:"exitProcess",returnCode:a}),new Fb(a);if(!noExitRuntime){O.sd();if(D.onExit)D.onExit(a);Ha=!0}wa(a,new Fb(a))}if(D.preInit)for("function"==typeof D.preInit&&(D.preInit=[D.preInit]);0<D.preInit.length;)D.preInit.pop()();F&&(noExitRuntime=!1,O.Zc());Pe();


  return BlinkInputWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkInputWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkInputWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkInputWasmSDK"] = BlinkInputWasmSDK;
