
var BlinkInputWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkInputWasmSDK) {
  BlinkInputWasmSDK = BlinkInputWasmSDK || {};


function g(){n.buffer!=r&&aa(n.buffer);return ba}function u(){n.buffer!=r&&aa(n.buffer);return ca}function da(){n.buffer!=r&&aa(n.buffer);return ea}function v(){n.buffer!=r&&aa(n.buffer);return fa}function A(){n.buffer!=r&&aa(n.buffer);return ha}function B(){n.buffer!=r&&aa(n.buffer);return ia}function ja(){n.buffer!=r&&aa(n.buffer);return ka}var C;C||(C=typeof BlinkInputWasmSDK !== 'undefined' ? BlinkInputWasmSDK : {});var la,ma;C.ready=new Promise(function(a,b){la=a;ma=b});
var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},na;na=C.allowedThreads&&0<C.allowedThreads?C.allowedThreads-1:navigator.hardwareConcurrency-1;var oa=0,pa;0<na&&(C.threadWorkersReadyPromise=new Promise(function(a){pa=a}));C.preRun||(C.preRun=[]);C.preRun.push(function(a){function b(){oa++;oa==na&&pa()}var c=a.PThread.kc;a.PThread.kc=function(d){c(d,b)}});var ra={},sa;for(sa in C)C.hasOwnProperty(sa)&&(ra[sa]=C[sa]);var ta="./this.program";
function ua(a,b){throw b;}var va="object"===typeof window,wa="function"===typeof importScripts,xa="object"===typeof process&&"object"===typeof process.Cd&&"string"===typeof process.Cd.node,E=C.ENVIRONMENT_IS_PTHREAD||!1,ya="";function za(a){return C.locateFile?C.locateFile(a,ya):ya+a}var Aa;
if(va||wa)wa?ya=self.location.href:"undefined"!==typeof document&&document.currentScript&&(ya=document.currentScript.src),_scriptDir&&(ya=_scriptDir),ya=0!==ya.indexOf("blob:")?ya.substr(0,ya.lastIndexOf("/")+1):"",wa&&(Aa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var Ba=C.print||console.log.bind(console),F=C.printErr||console.warn.bind(console);for(sa in ra)ra.hasOwnProperty(sa)&&(C[sa]=ra[sa]);ra=null;
C.thisProgram&&(ta=C.thisProgram);C.quit&&(ua=C.quit);var Ca,Da;C.wasmBinary&&(Da=C.wasmBinary);var noExitRuntime=C.noExitRuntime||!0;"object"!==typeof WebAssembly&&I("no native wasm support detected");var n,Ea,Fa=!1,Ga;function Ha(a){a||I("Assertion failed: undefined")}function Ia(a){var b=new TextDecoder(a);this.decode=function(c){c.buffer instanceof SharedArrayBuffer&&(c=new Uint8Array(c));return b.decode.call(b,c)}}var Ja="undefined"!==typeof TextDecoder?new Ia("utf8"):void 0;
function Ka(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function J(a,b){return a?Ka(u(),a,b):""}
function La(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var h=a.charCodeAt(f);if(55296<=h&&57343>=h){var l=a.charCodeAt(++f);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-e}function K(a,b,c){La(a,u(),b,c)}
function Ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var Na="undefined"!==typeof TextDecoder?new Ia("utf-16le"):void 0;function Oa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&v()[c];)++c;c<<=1;if(32<c-a&&Na)return Na.decode(u().subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=da()[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function Pa(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);da()[b>>1]=f;b+=2}da()[b>>1]=0;return b-d}function Ra(a){return 2*a.length}function Sa(a,b){for(var c=0,d="";!(c>=b/4);){var e=A()[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ta(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var h=a.charCodeAt(++e);f=65536+((f&1023)<<10)|h&1023}A()[b>>2]=f;b+=4;if(b+4>c)break}A()[b>>2]=0;return b-d}function Ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Va(a){var b=Ma(a)+1,c=O(b);c&&La(a,g(),c,b);return c}function Wa(a,b){g().set(a,b)}var r,ba,ca,ea,fa,ha,ia,Xa,ka;E&&(r=C.buffer);
function aa(a){r=a;C.HEAP8=ba=new Int8Array(a);C.HEAP16=ea=new Int16Array(a);C.HEAP32=ha=new Int32Array(a);C.HEAPU8=ca=new Uint8Array(a);C.HEAPU16=fa=new Uint16Array(a);C.HEAPU32=ia=new Uint32Array(a);C.HEAPF32=Xa=new Float32Array(a);C.HEAPF64=ka=new Float64Array(a)}var Ya=C.INITIAL_MEMORY||209715200;
if(E)n=C.wasmMemory,r=C.buffer;else if(C.wasmMemory)n=C.wasmMemory;else if(n=new WebAssembly.Memory({initial:Ya/65536,maximum:12800,shared:!0}),!(n.buffer instanceof SharedArrayBuffer))throw F("requested a shared WebAssembly.Memory but the returned buffer is not a SharedArrayBuffer, indicating that while the browser has SharedArrayBuffer it does not have WebAssembly threads support - you may need to set a flag"),xa&&console.log("(on node you may need: --experimental-wasm-threads --experimental-wasm-bulk-memory and also use a recent version)"),
Error("bad memory");n&&(r=n.buffer);Ya=r.byteLength;aa(r);var P,Za=[],$a=[],ab=[],bb=0;function cb(){return noExitRuntime||0<bb}function db(){E||(C.noFSInit||eb||(eb=!0,fb(),C.stdin=C.stdin,C.stdout=C.stdout,C.stderr=C.stderr,C.stdin?gb("stdin",C.stdin):hb("/dev/tty","/dev/stdin"),C.stdout?gb("stdout",null,C.stdout):hb("/dev/tty","/dev/stdout"),C.stderr?gb("stderr",null,C.stderr):hb("/dev/tty1","/dev/stderr"),ib("/dev/stdin",0),ib("/dev/stdout",1),ib("/dev/stderr",1)),jb=!1,kb($a))}
function lb(){var a=C.preRun.shift();Za.unshift(a)}var mb=0,nb=null,ob=null;function pb(){mb++;C.monitorRunDependencies&&C.monitorRunDependencies(mb)}function qb(){mb--;C.monitorRunDependencies&&C.monitorRunDependencies(mb);if(0==mb&&(null!==nb&&(clearInterval(nb),nb=null),ob)){var a=ob;ob=null;a()}}C.preloadedImages={};C.preloadedAudios={};
function I(a){if(C.onAbort)C.onAbort(a);Ha(!E);a+="";F(a);Fa=!0;Ga=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ma(a);throw a;}function rb(){return sb.startsWith("data:application/octet-stream;base64,")}var sb;sb="BlinkInputWasmSDK.wasm";rb()||(sb=za(sb));function tb(){var a=sb;try{if(a==sb&&Da)return new Uint8Array(Da);if(Aa)return Aa(a);throw"both async and sync fetching of the wasm failed";}catch(b){I(b)}}
function ub(){return Da||!va&&!wa||"function"!==typeof fetch?Promise.resolve().then(function(){return tb()}):fetch(sb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+sb+"'";return a.arrayBuffer()}).catch(function(){return tb()})}
var vb,wb,xb={128320:function(a){a=J(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},128456:function(a,b,c,d){a=J(a);b=J(b);c=J(c);d=J(d);throw Error(a+b+c+d);},128672:function(a,b){a=J(a);b=J(b);throw Error(a+b);},128782:function(a,b){a=J(a);b=J(b);console.log(a+b)},128880:function(a){throw Error(J(a));},128923:function(){throw Error("Unable to perform that operation while recognizer is in use!");},129006:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},129089:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function kb(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(C);else{var c=b.Ld;"number"===typeof c?void 0===b.Jb?P.get(c)():P.get(c)(b.Jb):c(void 0===b.Jb?null:b.Jb)}}}
function yb(a,b){if(0>=a||a>g().length||a&1||0>b)return-28;if(0==b)return 0;2147483647<=b&&(b=Infinity);var c=Atomics.load(A(),zb>>2),d=0;if(c==a&&Atomics.compareExchange(A(),zb>>2,c,0)==c&&(--b,d=1,0>=b))return 1;a=Atomics.notify(A(),a>>2,b);if(0<=a)return a+d;throw"Atomics.notify returned an unexpected value "+a;}C._emscripten_futex_wake=yb;
function Ab(a){if(E)throw"Internal Error! cleanupThread() can only ever be called from main application thread!";if(!a)throw"Internal Error! Null pthread_ptr in cleanupThread!";var b=Q.ob[a];b&&(A()[a+8>>2]=0,Q.ac(b.worker))}function Bb(a){if(!(a instanceof Cb||"unwind"===a))throw a&&"object"===typeof a&&a.stack&&F("exception thrown: "+[a,a.stack]),a;}
var Q={zb:[],yb:[],qc:[],Pd:function(){},bd:function(a){Db(a,!wa,1)},cd:function(){Q.receiveObjectTransfer=Q.ld;Q.threadInit=Q.vd;Q.setExitStatus=Q.pd},ob:{},pc:[],Kc:function(){for(;0<Q.pc.length;)Q.pc.pop()();Eb()},pd:function(a){Ga=a},Lc:function(){for(var a in Q.ob){var b=Q.ob[a];b&&b.worker&&Q.ac(b.worker)}Q.ob={};for(a=0;a<Q.zb.length;++a){var c=Q.zb[a];c.terminate()}Q.zb=[];for(a=0;a<Q.yb.length;++a)c=Q.yb[a],b=c.nb,Q.hc(b),c.terminate();Q.yb=[]},hc:function(a){if(a){if(a.ub){var b=A()[a.ub+
96>>2];A()[a.ub+96>>2]=0;R(b);R(a.ub)}a.ub=0;a.fc&&a.Cb&&R(a.Cb);a.Cb=0;a.worker&&(a.worker.nb=null)}},ac:function(a){Q.nd(function(){delete Q.ob[a.nb.ub];Q.zb.push(a);Q.yb.splice(Q.yb.indexOf(a),1);Q.hc(a.nb);a.nb=void 0})},nd:function(a){A()[Fb>>2]=0;try{a()}finally{A()[Fb>>2]=1}},ld:function(){},vd:function(){for(var a in Q.qc)Q.qc[a]()},kc:function(a,b){a.onmessage=function(c){var d=c.data,e=d.cmd;a.nb&&(Q.Qc=a.nb.ub);if(d.targetThread&&d.targetThread!=Gb()){var f=Q.ob[d.Zd];f?f.worker.postMessage(c.data,
d.transferList):F('Internal error! Worker sent a message "'+e+'" to target pthread '+d.targetThread+", but that thread no longer exists!")}else if("processQueuedMainThreadWork"===e)Hb();else if("spawnThread"===e)Ib(c.data);else if("cleanupThread"===e)Ab(d.thread);else if("killThread"===e){c=d.thread;if(E)throw"Internal Error! killThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in killThread!";A()[c+8>>2]=0;d=Q.ob[c];delete Q.ob[c];d.worker.terminate();
Q.hc(d);Q.yb.splice(Q.yb.indexOf(d.worker),1);d.worker.nb=void 0}else if("cancelThread"===e){c=d.thread;if(E)throw"Internal Error! cancelThread() can only ever be called from main application thread!";if(!c)throw"Internal Error! Null pthread_ptr in cancelThread!";Q.ob[c].worker.postMessage({cmd:"cancel"})}else if("loaded"===e)a.loaded=!0,b&&b(a),a.Nb&&(a.Nb(),delete a.Nb);else if("print"===e)Ba("Thread "+d.threadId+": "+d.text);else if("printErr"===e)F("Thread "+d.threadId+": "+d.text);else if("alert"===
e)alert("Thread "+d.threadId+": "+d.text);else if("exit"===e)a.nb&&Atomics.load(B(),a.nb.ub+60>>2)&&Q.ac(a);else if("exitProcess"===e)try{Jb(d.returnCode)}catch(h){Bb(h)}else"cancelDone"===e?Q.ac(a):"objectTransfer"!==e&&("setimmediate"===c.data.target?a.postMessage(c.data):F("worker sent an unknown command "+e));Q.Qc=void 0};a.onerror=function(c){F("pthread sent an error! "+c.filename+":"+c.lineno+": "+c.message);throw c;};a.postMessage({cmd:"load",urlOrBlob:C.mainScriptUrlOrBlob||_scriptDir,wasmMemory:n,
wasmModule:Ea})},Nc:function(){var a=za("BlinkInputWasmSDK.worker.js");Q.zb.push(new Worker(a))},Vc:function(){0==Q.zb.length&&(Q.Nc(),Q.kc(Q.zb[0]));return Q.zb.pop()}};C.establishStackSpace=function(a,b){Kb(a,b);Lb(a)};C.invokeEntryPoint=function(a,b){return P.get(a)(b)};var Mb;Mb=E?function(){return performance.now()-C.__performance_now_clock_drift}:function(){return performance.now()};
function Nb(){function a(h){return(h=h.toTimeString().match(/\(([A-Za-z ]+)\)$/))?h[1]:"GMT"}if(E)return Ob(2,1);var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);A()[Pb()>>2]=60*f;A()[Qb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Va(c);d=Va(d);e<b?(A()[Rb()>>2]=c,A()[Rb()+4>>2]=d):(A()[Rb()>>2]=d,A()[Rb()+4>>2]=c)}var Sb;function Tb(a,b){u().fill(0,a,a+b)}
function Ib(a){if(E)throw"Internal Error! spawnThread() can only ever be called from main application thread!";var b=Q.Vc();if(!b)return 6;if(void 0!==b.nb)throw"Internal error!";if(!a.Zb)throw"Internal error, no pthread ptr!";Q.yb.push(b);var c=O(512);Tb(c,512);var d=a.Cb+a.Hb,e=Q.ob[a.Zb]={worker:b,Cb:a.Cb,Hb:a.Hb,fc:a.fc,ub:a.Zb},f=e.ub>>2;Atomics.store(B(),f+15,a.detached);Atomics.store(B(),f+24,c);Atomics.store(B(),f+9,e.ub);Atomics.store(B(),f+19,a.Hb);Atomics.store(B(),f+18,d);Atomics.store(B(),
f+25,a.Hb);Atomics.store(B(),f+27,d);Atomics.store(B(),f+28,a.detached);c=Ub()+40;Atomics.store(B(),f+42,c);b.nb=e;var h={cmd:"run",start_routine:a.ud,arg:a.Jb,threadInfoStruct:a.Zb,stackBase:a.Cb,stackSize:a.Hb};b.Nb=function(){h.time=performance.now();b.postMessage(h,a.Ad)};b.loaded&&(b.Nb(),delete b.Nb);return 0}
function Vb(a,b,c){if(0>=a||a>g().length||a&1)return-28;if(va){if(Atomics.load(A(),a>>2)!=b)return-6;var d=performance.now();c=d+c;for(Atomics.exchange(A(),zb>>2,a);;){d=performance.now();if(d>c)return Atomics.exchange(A(),zb>>2,0),-73;d=Atomics.exchange(A(),zb>>2,0);if(0==d)break;Hb();if(Atomics.load(A(),a>>2)!=b)return-6;Atomics.exchange(A(),zb>>2,a)}return 0}a=Atomics.wait(A(),a>>2,b,c);if("timed-out"===a)return-73;if("not-equal"===a)return-6;if("ok"===a)return 0;throw"Atomics.wait returned an unexpected value "+
a;}function Wb(){wa||(Ca||(Ca={}),Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]||(Ca["Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"]=1,F("Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread")))}
function Xb(a,b){if(!a)return F("pthread_join attempted on a null thread pointer!"),71;if(E&&Gb()==a)return F("PThread "+a+" is attempting to join to itself!"),16;if(!E&&Yb()==a)return F("Main thread "+a+" is attempting to join to itself!"),16;if(A()[a+8>>2]!==a)return F("pthread_join attempted on thread "+a+", which does not point to a valid thread, or does not exist anymore!"),71;if(Atomics.load(B(),a+60>>2))return F("Attempted to join thread "+a+", which was already detached!"),28;for(Wb();;){var c=
Atomics.load(B(),a+0>>2);if(1==c)return b&&(c=Atomics.load(B(),a+88>>2),A()[b>>2]=c),Atomics.store(B(),a+60>>2,1),E?postMessage({cmd:"cleanupThread",thread:a}):Ab(a),0;Zb();E||Hb();Vb(a+0,c,E?100:1)}}var $b={};function ac(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function bc(a){return this.fromWireType(B()[a>>2])}var cc={},dc={},ec={};function fc(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}
function gc(a,b){a=fc(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}function hc(a){var b=Error,c=gc(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}
var ic=void 0;function jc(a){throw new ic(a);}function kc(a,b,c){function d(l){l=c(l);l.length!==a.length&&jc("Mismatched type converter count");for(var m=0;m<a.length;++m)lc(a[m],l[m])}a.forEach(function(l){ec[l]=b});var e=Array(b.length),f=[],h=0;b.forEach(function(l,m){dc.hasOwnProperty(l)?e[m]=dc[l]:(f.push(l),cc.hasOwnProperty(l)||(cc[l]=[]),cc[l].push(function(){e[m]=dc[l];++h;h===f.length&&d(e)}))});0===f.length&&d(e)}
function mc(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var nc=void 0;function S(a){for(var b="";u()[a];)b+=nc[u()[a++]];return b}var oc=void 0;function T(a){throw new oc(a);}
function lc(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||T('type "'+d+'" must have a positive integer typeid pointer');if(dc.hasOwnProperty(a)){if(c.$c)return;T("Cannot register type '"+d+"' twice")}dc[a]=b;delete ec[a];cc.hasOwnProperty(a)&&(b=cc[a],delete cc[a],b.forEach(function(e){e()}))}function pc(a){T(a.$a.hb.eb.name+" instance already deleted")}var qc=!1;function rc(){}
function sc(a){--a.count.value;0===a.count.value&&(a.lb?a.pb.wb(a.lb):a.hb.eb.wb(a.fb))}function tc(a){if("undefined"===typeof FinalizationGroup)return tc=function(b){return b},a;qc=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.fb?sc(c):console.warn("object already deleted: "+c.fb)});tc=function(b){qc.register(b,b.$a,b.$a);return b};rc=function(b){qc.unregister(b.$a)};return tc(a)}var uc=void 0,vc=[];
function wc(){for(;vc.length;){var a=vc.pop();a.$a.Db=!1;a["delete"]()}}function xc(){}var yc={};function zc(a,b,c){if(void 0===a[b].jb){var d=a[b];a[b]=function(){a[b].jb.hasOwnProperty(arguments.length)||T("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].jb+")!");return a[b].jb[arguments.length].apply(this,arguments)};a[b].jb=[];a[b].jb[d.Sb]=d}}
function Ac(a,b,c){C.hasOwnProperty(a)?((void 0===c||void 0!==C[a].jb&&void 0!==C[a].jb[c])&&T("Cannot register public name '"+a+"' twice"),zc(C,a,a),C.hasOwnProperty(c)&&T("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),C[a].jb[c]=b):(C[a]=b,void 0!==c&&(C[a].Vd=c))}function Bc(a,b,c,d,e,f,h,l){this.name=a;this.constructor=b;this.Fb=c;this.wb=d;this.qb=e;this.Uc=f;this.Pb=h;this.Rc=l;this.jd=[]}
function Cc(a,b,c){for(;b!==c;)b.Pb||T("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Pb(a),b=b.qb;return a}function Dc(a,b){if(null===b)return this.jc&&T("null is not a valid "+this.name),0;b.$a||T('Cannot pass "'+Ec(b)+'" as a '+this.name);b.$a.fb||T("Cannot pass deleted object as a pointer of type "+this.name);return Cc(b.$a.fb,b.$a.hb.eb,this.eb)}
function Fc(a,b){if(null===b){this.jc&&T("null is not a valid "+this.name);if(this.Wb){var c=this.mc();null!==a&&a.push(this.wb,c);return c}return 0}b.$a||T('Cannot pass "'+Ec(b)+'" as a '+this.name);b.$a.fb||T("Cannot pass deleted object as a pointer of type "+this.name);!this.Vb&&b.$a.hb.Vb&&T("Cannot convert argument of type "+(b.$a.pb?b.$a.pb.name:b.$a.hb.name)+" to parameter type "+this.name);c=Cc(b.$a.fb,b.$a.hb.eb,this.eb);if(this.Wb)switch(void 0===b.$a.lb&&T("Passing raw pointer to smart pointer is illegal"),
this.td){case 0:b.$a.pb===this?c=b.$a.lb:T("Cannot convert argument of type "+(b.$a.pb?b.$a.pb.name:b.$a.hb.name)+" to parameter type "+this.name);break;case 1:c=b.$a.lb;break;case 2:if(b.$a.pb===this)c=b.$a.lb;else{var d=b.clone();c=this.kd(c,U(function(){d["delete"]()}));null!==a&&a.push(this.wb,c)}break;default:T("Unsupporting sharing policy")}return c}
function Gc(a,b){if(null===b)return this.jc&&T("null is not a valid "+this.name),0;b.$a||T('Cannot pass "'+Ec(b)+'" as a '+this.name);b.$a.fb||T("Cannot pass deleted object as a pointer of type "+this.name);b.$a.hb.Vb&&T("Cannot convert argument of type "+b.$a.hb.name+" to parameter type "+this.name);return Cc(b.$a.fb,b.$a.hb.eb,this.eb)}function Hc(a,b,c){if(b===c)return a;if(void 0===c.qb)return null;a=Hc(a,b,c.qb);return null===a?null:c.Rc(a)}var Ic={};
function Jc(a,b){for(void 0===b&&T("ptr should not be undefined");a.qb;)b=a.Pb(b),a=a.qb;return Ic[b]}function Kc(a,b){b.hb&&b.fb||jc("makeClassHandle requires ptr and ptrType");!!b.pb!==!!b.lb&&jc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return tc(Object.create(a,{$a:{value:b}}))}
function Lc(a,b,c,d){this.name=a;this.eb=b;this.jc=c;this.Vb=d;this.Wb=!1;this.wb=this.kd=this.mc=this.Gc=this.td=this.hd=void 0;void 0!==b.qb?this.toWireType=Fc:(this.toWireType=d?Dc:Gc,this.rb=null)}function Mc(a,b,c){C.hasOwnProperty(a)||jc("Replacing nonexistant public symbol");void 0!==C[a].jb&&void 0!==c?C[a].jb[c]=b:(C[a]=b,C[a].Sb=c)}
function Nc(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=C["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=P.get(b).apply(null,c);return d}}function V(a,b){a=S(a);var c=a.includes("j")?Nc(a,b):P.get(b);"function"!==typeof c&&T("unknown function pointer with signature "+a+": "+b);return c}var Oc=void 0;function Pc(a){a=Qc(a);var b=S(a);R(a);return b}
function Rc(a,b){function c(f){e[f]||dc[f]||(ec[f]?ec[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Oc(a+": "+d.map(Pc).join([", "]));}function Sc(a,b){for(var c=[],d=0;d<a;d++)c.push(A()[(b>>2)+d]);return c}
function Tc(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=gc(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Uc(a,b,c,d,e){var f=b.length;2>f&&T("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].rb){l=!0;break}var m="void"!==b[0].name,p="",q="";for(c=0;c<f-2;++c)p+=(0!==c?", ":"")+"arg"+c,q+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+fc(a)+"("+p+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var x=l?"destructors":"null";p="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[T,d,e,ac,b[0],b[1]];h&&(a+="var thisWired = classParam.toWireType("+x+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+x+", arg"+c+"); // "+b[c+2].name+"\n",p.push("argType"+c),d.push(b[c+2]);h&&(q="thisWired"+(0<q.length?", ":"")+q);a+=(m?"var rv = ":"")+"invoker(fn"+(0<q.length?", ":"")+q+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=h?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].rb&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",p.push(f+"_dtor"),d.push(b[c].rb));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");p.push(a+"}\n");return Tc(p).apply(null,d)}var Vc=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Wc(a){4<a&&0===--W[a].oc&&(W[a]=void 0,Vc.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Vc.length?Vc.pop():W.length;W[b]={oc:1,value:a};return b}}function Ec(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Xc(a,b){switch(b){case 2:return function(c){var d=this.fromWireType;n.buffer!=r&&aa(n.buffer);return d.call(this,Xa[c>>2])};case 3:return function(c){return this.fromWireType(ja()[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Yc(a,b,c){switch(b){case 0:return c?function(d){return g()[d]}:function(d){return u()[d]};case 1:return c?function(d){return da()[d>>1]}:function(d){return v()[d>>1]};case 2:return c?function(d){return A()[d>>2]}:function(d){return B()[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Zc(a){a||T("Cannot use deleted val. handle = "+a);return W[a].value}function $c(a,b){var c=dc[a];void 0===c&&T(b+" has unknown type "+Pc(a));return c}var ad={};
function bd(a){var b=ad[a];return void 0===b?S(a):b}var cd=[];function dd(){return"object"===typeof globalThis?globalThis:Function("return this")()}function ed(a){var b=cd.length;cd.push(a);return b}function fd(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=$c(A()[(b>>2)+d],"parameter "+d);return c}var gd={};function hd(){if(E)return Ob(3,1);I()}var jd=[];function Ob(a,b){for(var c=arguments.length-2,d=kd(),e=ld(8*c),f=e>>3,h=0;h<c;h++){var l=arguments[2+h];ja()[f+h]=l}c=md(a,c,e,b);Lb(d);return c}
var nd=[],od=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function pd(a){a=2<a?J(a):a;return od[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function qd(a,b,c){var d=pd(a);if(!d)return-4;d.Tb&&(A()[d.Tb>>2]=b,A()[d.Tb+4>>2]=c);if(d.Ec||!d.Hd)d.Ec&&(d=d.Ec),a=!1,d.Rb&&d.Rb.Qb&&(a=d.Rb.Qb.getParameter(2978),a=0===a[0]&&0===a[1]&&a[2]===d.width&&a[3]===d.height),d.width=b,d.height=c,a&&d.Rb.Qb.viewport(0,0,b,c);else{if(d.Tb){d=A()[d.Tb+8>>2];a=a?J(a):"";var e=kd(),f=ld(12),h=0;if(a){h=Ma(a)+1;var l=O(h);K(a,l,h);h=l}A()[f>>2]=h;A()[f+4>>2]=b;A()[f+8>>2]=c;rd(0,d,657457152,0,h,f);Lb(e);return 1}return-4}return 0}
function sd(a,b,c){return E?Ob(4,1,a,b,c):qd(a,b,c)}function td(a,b){if(!Fa)if(b)a();else try{if(a(),E&&!cb())try{E?ud(Ga):Jb(Ga)}catch(c){Bb(c)}}catch(c){Bb(c)}}var vd=[];function X(a,b){B()[a>>2]=b;B()[a+4>>2]=b/4294967296|0}
function wd(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}}var xd;
function yd(a,b,c,d,e){function f(L){var M=0,G=0;L&&(G=w.response?w.response.byteLength:0,M=O(G),u().set(new Uint8Array(w.response),M));B()[a+12>>2]=M;X(a+16,G)}var h=B()[a+8>>2];if(h){var l=J(h),m=a+112,p=J(m);p||(p="GET");B();var q=B()[m+52>>2],x=B()[m+56>>2],y=!!B()[m+60>>2];B();var k=B()[m+68>>2],t=B()[m+72>>2],z=B()[m+76>>2],D=B()[m+80>>2];h=B()[m+84>>2];m=B()[m+88>>2];var H=!!(q&1),N=!!(q&2);q=!!(q&64);k=k?J(k):void 0;t=t?J(t):void 0;var qa=D?J(D):void 0,w=new XMLHttpRequest;w.withCredentials=
y;w.open(p,l,!q,k,t);q||(w.timeout=x);w.ae=l;w.responseType="arraybuffer";D&&w.overrideMimeType(qa);if(z)for(;;){p=B()[z>>2];if(!p)break;l=B()[z+4>>2];if(!l)break;z+=8;p=J(p);l=J(l);w.setRequestHeader(p,l)}vd.push(w);z=vd.length;B()[a+0>>2]=z;h=h&&m?u().slice(h,h+m):null;w.onload=function(L){f(H&&!N);var M=w.response?w.response.byteLength:0;X(a+24,0);M&&X(a+32,M);v()[a+40>>1]=w.readyState;v()[a+42>>1]=w.status;w.statusText&&K(w.statusText,a+44,64);200<=w.status&&300>w.status?b&&b(a,w,L):c&&c(a,w,
L)};w.onerror=function(L){f(H);var M=w.status;X(a+24,0);X(a+32,w.response?w.response.byteLength:0);v()[a+40>>1]=w.readyState;v()[a+42>>1]=M;c&&c(a,w,L)};w.ontimeout=function(L){c&&c(a,w,L)};w.onprogress=function(L){var M=H&&N&&w.response?w.response.byteLength:0,G=0;H&&N&&(G=O(M),u().set(new Uint8Array(w.response),G));B()[a+12>>2]=G;X(a+16,M);X(a+24,L.loaded-M);X(a+32,L.total);v()[a+40>>1]=w.readyState;3<=w.readyState&&0===w.status&&0<L.loaded&&(w.status=200);v()[a+42>>1]=w.status;w.statusText&&K(w.statusText,
a+44,64);d&&d(a,w,L);G&&R(G)};w.onreadystatechange=function(L){v()[a+40>>1]=w.readyState;2<=w.readyState&&(v()[a+42>>1]=w.status);e&&e(a,w,L)};try{w.send(h)}catch(L){c&&c(a,w,L)}}else c(a,0,"no url specified!")}
function zd(a,b,c,d){var e=xd;if(e){var f=a+112;(f=B()[f+64>>2])||(f=B()[a+8>>2]);var h=J(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,h);l.onsuccess=function(){v()[a+40>>1]=4;v()[a+42>>1]=200;K("OK",a+44,64);c(a,0,h)};l.onerror=function(m){v()[a+40>>1]=4;v()[a+42>>1]=413;K("Payload Too Large",a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function Ad(a,b,c){var d=xd;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=J(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(h){if(h.target.result){h=h.target.result;var l=h.byteLength||h.length,m=O(l);u().set(new Uint8Array(h),m);B()[a+12>>2]=m;X(a+16,l);X(a+24,0);X(a+32,l);v()[a+40>>1]=4;v()[a+42>>1]=200;K("OK",a+44,64);b(a,0,h)}else v()[a+40>>1]=4,v()[a+42>>1]=404,K("Not Found",a+44,64),c(a,0,"no data")};f.onerror=function(h){v()[a+40>>1]=
4;v()[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Bd(a,b,c){var d=xd;if(d){var e=a+112;(e=B()[e+64>>2])||(e=B()[a+8>>2]);e=J(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(h){h=h.target.result;B()[a+12>>2]=0;X(a+16,0);X(a+24,0);X(a+32,0);v()[a+40>>1]=4;v()[a+42>>1]=200;K("OK",a+44,64);b(a,0,h)};f.onerror=function(h){v()[a+40>>1]=4;v()[a+42>>1]=404;K("Not Found",a+44,64);c(a,0,h)}}catch(h){c(a,0,h)}}else c(a,0,"IndexedDB not available!")}
function Cd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,f){b.drawArraysInstancedANGLE(c,d,e,f)},a.drawElementsInstanced=function(c,d,e,f,h){b.drawElementsInstancedANGLE(c,d,e,f,h)})}
function Dd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ed(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}
function Fd(a,b){a.zc||(a.zc=a.getContext,a.getContext=function(d,e){e=a.zc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Gd(c,b):0}function Gd(a,b){var c=O(8);A()[c+4>>2]=Gb();var d={Od:c,attributes:b,version:b.ed,Qb:a};a.canvas&&(a.canvas.Rb=d);("undefined"===typeof b.uc||b.uc)&&Hd(d);return c}
function Hd(a){a||(a=Id);if(!a.ad){a.ad=!0;var b=a.Qb;Cd(b);Dd(b);Ed(b);b.Kd=b.getExtension("EXT_disjoint_timer_query");b.Td=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var Id,Jd=["default","low-power","high-performance"],Kd={};
function Ld(){if(!Md){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ta||"./this.program"},b;for(b in Kd)void 0===Kd[b]?delete a[b]:a[b]=Kd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Md=c}return Md}var Md;
function Nd(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Od(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Nd(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Pd(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Qd(a){if("/"===a)return"/";a=Od(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function Rd(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){I("randomDevice")}}
function Sd(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Nd(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Td=[];function Ud(a,b){Td[a]={input:[],ib:[],Gb:b};Vd(a,Wd)}
var Wd={open:function(a){var b=Td[a.node.$b];if(!b)throw new Y(43);a.mb=b;a.seekable=!1},close:function(a){a.mb.Gb.flush(a.mb)},flush:function(a){a.mb.Gb.flush(a.mb)},read:function(a,b,c,d){if(!a.mb||!a.mb.Gb.Ac)throw new Y(60);for(var e=0,f=0;f<d;f++){try{var h=a.mb.Gb.Ac(a.mb)}catch(l){throw new Y(29);}if(void 0===h&&0===e)throw new Y(6);if(null===h||void 0===h)break;e++;b[c+f]=h}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.mb||!a.mb.Gb.lc)throw new Y(60);try{for(var e=
0;e<d;e++)a.mb.Gb.lc(a.mb,b[c+e])}catch(f){throw new Y(29);}d&&(a.node.timestamp=Date.now());return e}},Yd={Ac:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Xd(b,!0)}return a.input.shift()},lc:function(a,b){null===b||10===b?(Ba(Ka(a.ib,0)),a.ib=[]):0!=b&&a.ib.push(b)},flush:function(a){a.ib&&0<a.ib.length&&
(Ba(Ka(a.ib,0)),a.ib=[])}},Zd={lc:function(a,b){null===b||10===b?(F(Ka(a.ib,0)),a.ib=[]):0!=b&&a.ib.push(b)},flush:function(a){a.ib&&0<a.ib.length&&(F(Ka(a.ib,0)),a.ib=[])}},Z={sb:null,vb:function(){return Z.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new Y(63);Z.sb||(Z.sb={dir:{node:{xb:Z.bb.xb,tb:Z.bb.tb,Kb:Z.bb.Kb,Xb:Z.bb.Xb,Ic:Z.bb.Ic,Mc:Z.bb.Mc,Jc:Z.bb.Jc,Hc:Z.bb.Hc,bc:Z.bb.bc},stream:{Bb:Z.cb.Bb}},file:{node:{xb:Z.bb.xb,tb:Z.bb.tb},
stream:{Bb:Z.cb.Bb,read:Z.cb.read,write:Z.cb.write,rc:Z.cb.rc,Bc:Z.cb.Bc,Dc:Z.cb.Dc}},link:{node:{xb:Z.bb.xb,tb:Z.bb.tb,Mb:Z.bb.Mb},stream:{}},sc:{node:{xb:Z.bb.xb,tb:Z.bb.tb},stream:$d}});c=ae(a,b,c,d);16384===(c.mode&61440)?(c.bb=Z.sb.dir.node,c.cb=Z.sb.dir.stream,c.ab={}):32768===(c.mode&61440)?(c.bb=Z.sb.file.node,c.cb=Z.sb.file.stream,c.gb=0,c.ab=null):40960===(c.mode&61440)?(c.bb=Z.sb.link.node,c.cb=Z.sb.link.stream):8192===(c.mode&61440)&&(c.bb=Z.sb.sc.node,c.cb=Z.sb.sc.stream);c.timestamp=
Date.now();a&&(a.ab[b]=c,a.timestamp=c.timestamp);return c},Md:function(a){return a.ab?a.ab.subarray?a.ab.subarray(0,a.gb):new Uint8Array(a.ab):new Uint8Array(0)},vc:function(a,b){var c=a.ab?a.ab.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ab,a.ab=new Uint8Array(b),0<a.gb&&a.ab.set(c.subarray(0,a.gb),0))},md:function(a,b){if(a.gb!=b)if(0==b)a.ab=null,a.gb=0;else{var c=a.ab;a.ab=new Uint8Array(b);c&&a.ab.set(c.subarray(0,Math.min(b,a.gb)));a.gb=b}},bb:{xb:function(a){var b=
{};b.Jd=8192===(a.mode&61440)?a.id:1;b.Qd=a.id;b.mode=a.mode;b.Ud=1;b.uid=0;b.Nd=0;b.$b=a.$b;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.gb:40960===(a.mode&61440)?a.link.length:0;b.Ed=new Date(a.timestamp);b.Sd=new Date(a.timestamp);b.Id=new Date(a.timestamp);b.Oc=4096;b.Fd=Math.ceil(b.size/b.Oc);return b},tb:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Z.md(a,b.size)},Kb:function(){throw be[44];},Xb:function(a,b,c,
d){return Z.createNode(a,b,c,d)},Ic:function(a,b,c){if(16384===(a.mode&61440)){try{var d=ce(b,c)}catch(f){}if(d)for(var e in d.ab)throw new Y(55);}delete a.parent.ab[a.name];a.parent.timestamp=Date.now();a.name=c;b.ab[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Mc:function(a,b){delete a.ab[b];a.timestamp=Date.now()},Jc:function(a,b){var c=ce(a,b),d;for(d in c.ab)throw new Y(55);delete a.ab[b];a.timestamp=Date.now()},Hc:function(a){var b=[".",".."],c;for(c in a.ab)a.ab.hasOwnProperty(c)&&b.push(c);
return b},bc:function(a,b,c){a=Z.createNode(a,b,41471,0);a.link=c;return a},Mb:function(a){if(40960!==(a.mode&61440))throw new Y(28);return a.link}},cb:{read:function(a,b,c,d,e){var f=a.node.ab;if(e>=a.node.gb)return 0;a=Math.min(a.node.gb-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===g().buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ab||a.ab.subarray)){if(f)return a.ab=b.subarray(c,
c+d),a.gb=d;if(0===a.gb&&0===e)return a.ab=b.slice(c,c+d),a.gb=d;if(e+d<=a.gb)return a.ab.set(b.subarray(c,c+d),e),d}Z.vc(a,e+d);if(a.ab.subarray&&b.subarray)a.ab.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ab[e+f]=b[c+f];a.gb=Math.max(a.gb,e+d);return d},Bb:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.gb);if(0>b)throw new Y(28);return b},rc:function(a,b,c){Z.vc(a.node,b+c);a.node.gb=Math.max(a.node.gb,b+c)},Bc:function(a,b,c,d,e,f){if(0!==b)throw new Y(28);
if(32768!==(a.node.mode&61440))throw new Y(43);a=a.node.ab;if(f&2||a.buffer!==r){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=65536*Math.ceil(c/65536);(f=de(65536,c))?(Tb(f,c),c=f):c=0;if(!c)throw new Y(48);g().set(a,c)}else d=!1,c=a.byteOffset;return{fb:c,Dd:d}},Dc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new Y(43);if(e&2)return 0;Z.cb.write(a,b,0,d,c,!1);return 0}}},ee=null,fe={},ge=[],he=1,ie=null,jb=!0,je={},Y=null,be={};
function ke(a,b){a=Sd("/",a);b=b||{};if(!a)return{path:"",node:null};var c={yc:!0,nc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.nc)throw new Y(32);a=Nd(a.split("/").filter(function(h){return!!h}),!1);var e=ee;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=ce(e,a[d]);c=Od(c+"/"+a[d]);e.Yb&&(!f||f&&b.yc)&&(e=e.Yb.root);if(!f||b.xc)for(f=0;40960===(e.mode&61440);)if(e=le(c),c=Sd(Pd(c),e),e=ke(c,{nc:b.nc}).node,40<f++)throw new Y(32);}return{path:c,node:e}}
function me(a){for(var b;;){if(a===a.parent)return a=a.vb.Cc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function ne(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%ie.length}function ce(a,b){var c;if(c=(c=oe(a,"x"))?c:a.bb.Kb?0:2)throw new Y(c,a);for(c=ie[ne(a.id,b)];c;c=c.gd){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.bb.Kb(a,b)}
function ae(a,b,c,d){a=new pe(a,b,c,d);b=ne(a.parent.id,a.name);a.gd=ie[b];return ie[b]=a}var qe={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function re(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function oe(a,b){if(jb)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function se(a,b){try{return ce(a,b),20}catch(c){}return oe(a,"wx")}
function te(){var a=4096;for(var b=0;b<=a;b++)if(!ge[b])return b;throw new Y(33);}function ue(a){ve||(ve=function(){},ve.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new ve,c;for(c in a)b[c]=a[c];a=b;b=te();a.Eb=b;return ge[b]=a}var $d={open:function(a){a.cb=fe[a.node.$b].cb;a.cb.open&&a.cb.open(a)},Bb:function(){throw new Y(70);}};function Vd(a,b){fe[a]={cb:b}}
function we(a,b){var c="/"===b,d=!b;if(c&&ee)throw new Y(10);if(!c&&!d){var e=ke(b,{yc:!1});b=e.path;e=e.node;if(e.Yb)throw new Y(10);if(16384!==(e.mode&61440))throw new Y(54);}b={type:a,Wd:{},Cc:b,fd:[]};a=a.vb(b);a.vb=b;b.root=a;c?ee=a:e&&(e.Yb=b,e.vb&&e.vb.fd.push(b))}function xe(a,b,c){var d=ke(a,{parent:!0}).node;a=Qd(a);if(!a||"."===a||".."===a)throw new Y(28);var e=se(d,a);if(e)throw new Y(e);if(!d.bb.Xb)throw new Y(63);return d.bb.Xb(d,a,b,c)}function ye(a){return xe(a,16895,0)}
function ze(a,b,c){"undefined"===typeof c&&(c=b,b=438);xe(a,b|8192,c)}function hb(a,b){if(!Sd(a))throw new Y(44);var c=ke(b,{parent:!0}).node;if(!c)throw new Y(44);b=Qd(b);var d=se(c,b);if(d)throw new Y(d);if(!c.bb.bc)throw new Y(63);c.bb.bc(c,b,a)}function le(a){a=ke(a).node;if(!a)throw new Y(44);if(!a.bb.Mb)throw new Y(28);return Sd(me(a.parent),a.bb.Mb(a))}
function ib(a,b){if(""===a)throw new Y(44);if("string"===typeof b){var c=qe[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=Od(a);try{e=ke(a,{xc:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new Y(20);}else e=xe(a,d,0),c=!0;if(!e)throw new Y(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new Y(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==re(b)||b&512)?31:oe(e,re(b)):44))throw new Y(d);if(b&512){d=e;d="string"===typeof d?ke(d,{xc:!0}).node:d;if(!d.bb.tb)throw new Y(63);if(16384===(d.mode&61440))throw new Y(31);if(32768!==(d.mode&61440))throw new Y(28);if(c=oe(d,"w"))throw new Y(c);d.bb.tb(d,{size:0,timestamp:Date.now()})}b&=-131713;e=ue({node:e,path:me(e),flags:b,seekable:!0,position:0,cb:e.cb,Bd:[],error:!1});e.cb.open&&e.cb.open(e);!C.logReadFiles||b&1||(Ae||(Ae={}),a in Ae||(Ae[a]=1,F("FS.trackingDelegate error on read file: "+
a)));try{je.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),je.onOpenFile(a,e))}catch(f){F("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}}function Be(a,b,c){if(null===a.Eb)throw new Y(8);if(!a.seekable||!a.cb.Bb)throw new Y(70);if(0!=c&&1!=c&&2!=c)throw new Y(28);a.position=a.cb.Bb(a,b,c);a.Bd=[]}
function fb(){Y||(Y=function(a,b){this.node=b;this.od=function(c){this.Ub=c};this.od(a);this.message="FS error"},Y.prototype=Error(),Y.prototype.constructor=Y,[44].forEach(function(a){be[a]=new Y(a);be[a].stack="<generic error, no stack>"}))}var eb;function Ce(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function gb(a,b,c){a=Od("/dev/"+a);var d=Ce(!!b,!!c);De||(De=64);var e=De++<<8|0;Vd(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,h,l,m){for(var p=0,q=0;q<m;q++){try{var x=b()}catch(y){throw new Y(29);}if(void 0===x&&0===p)throw new Y(6);if(null===x||void 0===x)break;p++;h[l+q]=x}p&&(f.node.timestamp=Date.now());return p},write:function(f,h,l,m){for(var p=0;p<m;p++)try{c(h[l+p])}catch(q){throw new Y(29);}m&&(f.node.timestamp=Date.now());return p}});
ze(a,d,e)}var De,Ee={},ve,Ae;function Fe(a){a=ge[a];if(!a)throw new Y(8);return a}function Ge(a,b){if(E)return Ob(5,1,a,b);var c=0;Ld().forEach(function(d,e){var f=b+c;e=A()[a+4*e>>2]=f;for(f=0;f<d.length;++f)g()[e++>>0]=d.charCodeAt(f);g()[e>>0]=0;c+=d.length+1});return 0}function He(a,b){if(E)return Ob(6,1,a,b);var c=Ld();A()[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});A()[b>>2]=d;return 0}
function Ie(a){if(E)return Ob(7,1,a);try{var b=Fe(a);if(null===b.Eb)throw new Y(8);b.ic&&(b.ic=null);try{b.cb.close&&b.cb.close(b)}catch(c){throw c;}finally{ge[b.Eb]=null}b.Eb=null;return 0}catch(c){return"undefined"!==typeof Ee&&c instanceof Y||I(c),c.Ub}}
function Je(a,b,c,d){if(E)return Ob(8,1,a,b,c,d);try{a:{for(var e=Fe(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,p=g(),q=h,x=l,y=void 0;if(0>x||0>y)throw new Y(28);if(null===m.Eb)throw new Y(8);if(1===(m.flags&2097155))throw new Y(8);if(16384===(m.node.mode&61440))throw new Y(31);if(!m.cb.read)throw new Y(28);var k="undefined"!==typeof y;if(!k)y=m.position;else if(!m.seekable)throw new Y(70);var t=m.cb.read(m,p,q,x,y);k||(m.position+=t);var z=t;if(0>z){var D=-1;break a}a+=z;if(z<
l)break}D=a}A()[d>>2]=D;return 0}catch(H){return"undefined"!==typeof Ee&&H instanceof Y||I(H),H.Ub}}
function Ke(a,b,c,d,e){if(E)return Ob(9,1,a,b,c,d,e);try{var f=Fe(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;Be(f,a,d);wb=[f.position>>>0,(vb=f.position,1<=+Math.abs(vb)?0<vb?(Math.min(+Math.floor(vb/4294967296),4294967295)|0)>>>0:~~+Math.ceil((vb-+(~~vb>>>0))/4294967296)>>>0:0)];A()[e>>2]=wb[0];A()[e+4>>2]=wb[1];f.ic&&0===a&&0===d&&(f.ic=null);return 0}catch(h){return"undefined"!==typeof Ee&&h instanceof Y||I(h),h.Ub}}
function Le(a,b,c,d){if(E)return Ob(10,1,a,b,c,d);try{a:{for(var e=Fe(a),f=a=0;f<c;f++){var h=A()[b+8*f>>2],l=A()[b+(8*f+4)>>2],m=e,p=g(),q=h,x=l,y=void 0;if(0>x||0>y)throw new Y(28);if(null===m.Eb)throw new Y(8);if(0===(m.flags&2097155))throw new Y(8);if(16384===(m.node.mode&61440))throw new Y(31);if(!m.cb.write)throw new Y(28);m.seekable&&m.flags&1024&&Be(m,0,2);var k="undefined"!==typeof y;if(!k)y=m.position;else if(!m.seekable)throw new Y(70);var t=m.cb.write(m,p,q,x,y,void 0);k||(m.position+=
t);try{if(m.path&&je.onWriteToFile)je.onWriteToFile(m.path)}catch(H){F("FS.trackingDelegate['onWriteToFile']('"+m.path+"') threw an exception: "+H.message)}var z=t;if(0>z){var D=-1;break a}a+=z}D=a}A()[d>>2]=D;return 0}catch(H){return"undefined"!==typeof Ee&&H instanceof Y||I(H),H.Ub}}function Me(a,b){Me.Fc||(Me.Fc=Rd());for(var c=0;c<b;c++)g()[a+c>>0]=Me.Fc();return 0}function Ne(a){return 0===a%4&&(0!==a%100||0===a%400)}function Oe(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Pe=[31,29,31,30,31,30,31,31,30,31,30,31],Qe=[31,28,31,30,31,30,31,31,30,31,30,31];function Re(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Ne(a.getFullYear())?Pe:Qe)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Se(a,b,c,d){function e(k,t,z){for(k="number"===typeof k?k.toString():k||"";k.length<t;)k=z[0]+k;return k}function f(k,t){return e(k,t,"0")}function h(k,t){function z(H){return 0>H?-1:0<H?1:0}var D;0===(D=z(k.getFullYear()-t.getFullYear()))&&0===(D=z(k.getMonth()-t.getMonth()))&&(D=z(k.getDate()-t.getDate()));return D}function l(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){k=Re(new Date(k.kb+1900,0,1),k.ec);var t=new Date(k.getFullYear()+1,0,4),z=l(new Date(k.getFullYear(),0,4));t=l(t);return 0>=h(z,k)?0>=h(t,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var p=A()[d+40>>2];d={yd:A()[d>>2],xd:A()[d+4>>2],cc:A()[d+8>>2],Ob:A()[d+12>>2],Ib:A()[d+16>>2],kb:A()[d+20>>2],dc:A()[d+24>>2],ec:A()[d+28>>2],$d:A()[d+
32>>2],wd:A()[d+36>>2],zd:p?J(p):""};c=J(c);p={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var q in p)c=c.replace(new RegExp(q,"g"),p[q]);var x="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
y="January February March April May June July August September October November December".split(" ");p={"%a":function(k){return x[k.dc].substring(0,3)},"%A":function(k){return x[k.dc]},"%b":function(k){return y[k.Ib].substring(0,3)},"%B":function(k){return y[k.Ib]},"%C":function(k){return f((k.kb+1900)/100|0,2)},"%d":function(k){return f(k.Ob,2)},"%e":function(k){return e(k.Ob,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.cc,
2)},"%I":function(k){k=k.cc;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){return f(k.Ob+Oe(Ne(k.kb+1900)?Pe:Qe,k.Ib-1),3)},"%m":function(k){return f(k.Ib+1,2)},"%M":function(k){return f(k.xd,2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.cc&&12>k.cc?"AM":"PM"},"%S":function(k){return f(k.yd,2)},"%t":function(){return"\t"},"%u":function(k){return k.dc||7},"%U":function(k){var t=new Date(k.kb+1900,0,1),z=0===t.getDay()?t:Re(t,7-t.getDay());k=new Date(k.kb+1900,k.Ib,k.Ob);return 0>
h(z,k)?f(Math.ceil((31-z.getDate()+(Oe(Ne(k.getFullYear())?Pe:Qe,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%V":function(k){var t=new Date(k.kb+1901,0,4),z=l(new Date(k.kb+1900,0,4));t=l(t);var D=Re(new Date(k.kb+1900,0,1),k.ec);return 0>h(D,z)?"53":0>=h(t,D)?"01":f(Math.ceil((z.getFullYear()<k.kb+1900?k.ec+32-z.getDate():k.ec+1-z.getDate())/7),2)},"%w":function(k){return k.dc},"%W":function(k){var t=new Date(k.kb,0,1),z=1===t.getDay()?t:Re(t,0===t.getDay()?1:7-t.getDay()+1);k=
new Date(k.kb+1900,k.Ib,k.Ob);return 0>h(z,k)?f(Math.ceil((31-z.getDate()+(Oe(Ne(k.getFullYear())?Pe:Qe,k.getMonth()-1)-31)+k.getDate())/7),2):0===h(z,t)?"01":"00"},"%y":function(k){return(k.kb+1900).toString().substring(2)},"%Y":function(k){return k.kb+1900},"%z":function(k){k=k.wd;var t=0<=k;k=Math.abs(k)/60;return(t?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.zd},"%%":function(){return"%"}};for(q in p)c.includes(q)&&(c=c.replace(new RegExp(q,"g"),p[q](d)));q=Xd(c,
!1);if(q.length>b)return 0;Wa(q,a);return q.length-1}ic=C.InternalError=hc("InternalError");for(var Te=Array(256),Ue=0;256>Ue;++Ue)Te[Ue]=String.fromCharCode(Ue);nc=Te;oc=C.BindingError=hc("BindingError");xc.prototype.isAliasOf=function(a){if(!(this instanceof xc&&a instanceof xc))return!1;var b=this.$a.hb.eb,c=this.$a.fb,d=a.$a.hb.eb;for(a=a.$a.fb;b.qb;)c=b.Pb(c),b=b.qb;for(;d.qb;)a=d.Pb(a),d=d.qb;return b===d&&c===a};
xc.prototype.clone=function(){this.$a.fb||pc(this);if(this.$a.Lb)return this.$a.count.value+=1,this;var a=tc,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.$a;a=a(c.call(b,d,{$a:{value:{count:e.count,Db:e.Db,Lb:e.Lb,fb:e.fb,hb:e.hb,lb:e.lb,pb:e.pb}}}));a.$a.count.value+=1;a.$a.Db=!1;return a};xc.prototype["delete"]=function(){this.$a.fb||pc(this);this.$a.Db&&!this.$a.Lb&&T("Object already scheduled for deletion");rc(this);sc(this.$a);this.$a.Lb||(this.$a.lb=void 0,this.$a.fb=void 0)};
xc.prototype.isDeleted=function(){return!this.$a.fb};xc.prototype.deleteLater=function(){this.$a.fb||pc(this);this.$a.Db&&!this.$a.Lb&&T("Object already scheduled for deletion");vc.push(this);1===vc.length&&uc&&uc(wc);this.$a.Db=!0;return this};Lc.prototype.Wc=function(a){this.Gc&&(a=this.Gc(a));return a};Lc.prototype.tc=function(a){this.wb&&this.wb(a)};Lc.prototype.argPackAdvance=8;Lc.prototype.readValueFromPointer=bc;Lc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
Lc.prototype.fromWireType=function(a){function b(){return this.Wb?Kc(this.eb.Fb,{hb:this.hd,fb:c,pb:this,lb:a}):Kc(this.eb.Fb,{hb:this,fb:a})}var c=this.Wc(a);if(!c)return this.tc(a),null;var d=Jc(this.eb,c);if(void 0!==d){if(0===d.$a.count.value)return d.$a.fb=c,d.$a.lb=a,d.clone();d=d.clone();this.tc(a);return d}d=this.eb.Uc(c);d=yc[d];if(!d)return b.call(this);d=this.Vb?d.Pc:d.pointerType;var e=Hc(c,this.eb,d.eb);return null===e?b.call(this):this.Wb?Kc(d.eb.Fb,{hb:d,fb:e,pb:this,lb:a}):Kc(d.eb.Fb,
{hb:d,fb:e})};C.getInheritedInstanceCount=function(){return Object.keys(Ic).length};C.getLiveInheritedInstances=function(){var a=[],b;for(b in Ic)Ic.hasOwnProperty(b)&&a.push(Ic[b]);return a};C.flushPendingDeletes=wc;C.setDelayFunction=function(a){uc=a;vc.length&&uc&&uc(wc)};Oc=C.UnboundTypeError=hc("UnboundTypeError");C.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};C.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};
E||(wd(function(a){xd=a;qb()},function(){xd=!1;qb()}),"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||pb());function pe(a,b,c,d){a||(a=this);this.parent=a;this.vb=a.vb;this.Yb=null;this.id=he++;this.name=b;this.mode=c;this.bb={};this.cb={};this.$b=d}
Object.defineProperties(pe.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});fb();ie=Array(4096);we(Z,"/");ye("/tmp");ye("/home");ye("/home/web_user");
(function(){ye("/dev");Vd(259,{read:function(){return 0},write:function(b,c,d,e){return e}});ze("/dev/null",259);Ud(1280,Yd);Ud(1536,Zd);ze("/dev/tty",1280);ze("/dev/tty1",1536);var a=Rd();gb("random",a);gb("urandom",a);ye("/dev/shm");ye("/dev/shm/tmp")})();
(function(){ye("/proc");var a=ye("/proc/self");ye("/proc/self/fd");we({vb:function(){var b=ae(a,"fd",16895,73);b.bb={Kb:function(c,d){var e=ge[+d];if(!e)throw new Y(8);c={parent:null,vb:{Cc:"fake"},bb:{Mb:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();var Ve=[null,function(a,b){if(E)return Ob(1,1,a,b)},Nb,hd,sd,Ge,He,Ie,Je,Ke,Le];function Xd(a,b){var c=Array(Ma(a)+1);a=La(a,c,0,c.length);b&&(c.length=a);return c}
var Xe={g:function(a,b,c,d){I("Assertion failed: "+J(a)+", at: "+[b?J(b):"unknown filename",c,d?J(d):"unknown function"])},ia:function(a,b){Q.pc.push(function(){P.get(a)(b)})},X:function(a,b){Sb||(Sb=!0,Nb());a=new Date(1E3*A()[a>>2]);A()[b>>2]=a.getSeconds();A()[b+4>>2]=a.getMinutes();A()[b+8>>2]=a.getHours();A()[b+12>>2]=a.getDate();A()[b+16>>2]=a.getMonth();A()[b+20>>2]=a.getFullYear()-1900;A()[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1),d=(a.getTime()-c.getTime())/864E5|0;A()[b+28>>
2]=d;A()[b+36>>2]=-(60*a.getTimezoneOffset());d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;A()[b+32>>2]=a;a=A()[Rb()+(a?4:0)>>2];A()[b+40>>2]=a;return b},ca:function(a,b,c,d){if("undefined"===typeof SharedArrayBuffer)return F("Current environment does not support SharedArrayBuffer, pthreads are not available!"),6;if(!a)return F("pthread_create called with a null thread pointer!"),28;var e=[];if(E&&0===e.length)return We(687865856,
a,b,c,d);var f=0,h=0;if(b&&-1!=b){var l=A()[b>>2];l+=81920;f=A()[b+8>>2];h=0!==A()[b+12>>2]}else l=2097152;(b=0==f)?f=de(16,l):(f-=l,Ha(0<f));var m=O(224);Tb(m,224);A()[a>>2]=m;A()[m+8>>2]=m;a=m+148;A()[a>>2]=a;c={Cb:f,Hb:l,fc:b,detached:h,ud:c,Zb:m,Jb:d,Ad:e};return E?(c.Gd="spawnThread",postMessage(c,e),0):Ib(c)},ba:function(a){E||(Q.Kc(),Jb(a));var b=Gb();Atomics.store(B(),b+52>>2,1);Atomics.store(B(),b+56>>2,0);Q.Kc();Atomics.store(B(),b+88>>2,a);Atomics.store(B(),b+0>>2,1);yb(b+0,2147483647);
Db(0,0,0);postMessage({cmd:"exit"})},$:function(a,b){return Xb(a,b)},c:function(a){var b=$b[a];delete $b[a];var c=b.mc,d=b.wb,e=b.wc,f=e.map(function(h){return h.Zc}).concat(e.map(function(h){return h.rd}));kc([a],f,function(h){var l={};e.forEach(function(m,p){var q=h[p],x=m.Xc,y=m.Yc,k=h[p+e.length],t=m.qd,z=m.sd;l[m.Tc]={read:function(D){return q.fromWireType(x(y,D))},write:function(D,H){var N=[];t(z,D,k.toWireType(N,H));ac(N)}}});return[{name:b.name,fromWireType:function(m){var p={},q;for(q in l)p[q]=
l[q].read(m);d(m);return p},toWireType:function(m,p){for(var q in l)if(!(q in p))throw new TypeError('Missing field:  "'+q+'"');var x=c();for(q in l)l[q].write(x,p[q]);null!==m&&m.push(d,x);return x},argPackAdvance:8,readValueFromPointer:bc,rb:d}]})},I:function(){},ea:function(a,b,c,d,e){var f=mc(c);b=S(b);lc(a,{name:b,fromWireType:function(h){return!!h},toWireType:function(h,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(h){if(1===c)var l=g();else if(2===c)l=da();else if(4===c)l=
A();else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[h>>f])},rb:null})},n:function(a,b,c,d,e,f,h,l,m,p,q,x,y){q=S(q);f=V(e,f);l&&(l=V(h,l));p&&(p=V(m,p));y=V(x,y);var k=fc(q);Ac(k,function(){Rc("Cannot construct "+q+" due to unbound types",[d])});kc([a,b,c],d?[d]:[],function(t){t=t[0];if(d){var z=t.eb;var D=z.Fb}else D=xc.prototype;t=gc(k,function(){if(Object.getPrototypeOf(this)!==H)throw new oc("Use 'new' to construct "+q);if(void 0===N.Ab)throw new oc(q+" has no accessible constructor");
var w=N.Ab[arguments.length];if(void 0===w)throw new oc("Tried to invoke ctor of "+q+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(N.Ab).toString()+") parameters instead!");return w.apply(this,arguments)});var H=Object.create(D,{constructor:{value:t}});t.prototype=H;var N=new Bc(q,t,H,y,z,f,l,p);z=new Lc(q,N,!0,!1);D=new Lc(q+"*",N,!1,!1);var qa=new Lc(q+" const*",N,!1,!0);yc[a]={pointerType:D,Pc:qa};Mc(k,t);return[z,D,qa]})},r:function(a,b,c,d,e,f){Ha(0<b);
var h=Sc(b,c);e=V(d,e);kc([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.eb.Ab&&(l.eb.Ab=[]);if(void 0!==l.eb.Ab[b-1])throw new oc("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.eb.Ab[b-1]=function(){Rc("Cannot construct "+l.name+" due to unbound types",h)};kc([],h,function(p){p.splice(1,0,null);l.eb.Ab[b-1]=Uc(m,p,null,
e,f);return[]});return[]})},e:function(a,b,c,d,e,f,h,l){var m=Sc(c,d);b=S(b);f=V(e,f);kc([],[a],function(p){function q(){Rc("Cannot call "+x+" due to unbound types",m)}p=p[0];var x=p.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&p.eb.jd.push(b);var y=p.eb.Fb,k=y[b];void 0===k||void 0===k.jb&&k.className!==p.name&&k.Sb===c-2?(q.Sb=c-2,q.className=p.name,y[b]=q):(zc(y,b,x),y[b].jb[c-2]=q);kc([],m,function(t){t=Uc(x,t,p,f,h);void 0===y[b].jb?(t.Sb=c-2,y[b]=t):y[b].jb[c-2]=t;return[]});
return[]})},da:function(a,b){b=S(b);lc(a,{name:b,fromWireType:function(c){var d=W[c].value;Wc(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:bc,rb:null})},E:function(a,b,c){c=mc(c);b=S(b);lc(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Ec(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Xc(b,c),rb:null})},w:function(a,b,c,d,e,f){var h=
Sc(b,c);a=S(a);e=V(d,e);Ac(a,function(){Rc("Cannot call "+a+" due to unbound types",h)},b-1);kc([],h,function(l){Mc(a,Uc(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},h:function(a,b,c,d,e){function f(p){return p}b=S(b);-1===e&&(e=4294967295);var h=mc(c);if(0===d){var l=32-8*c;f=function(p){return p<<l>>>l}}var m=b.includes("unsigned");lc(a,{name:b,fromWireType:f,toWireType:function(p,q){if("number"!==typeof q&&"boolean"!==typeof q)throw new TypeError('Cannot convert "'+Ec(q)+'" to '+
this.name);if(q<d||q>e)throw new TypeError('Passing a number "'+Ec(q)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?q>>>0:q|0},argPackAdvance:8,readValueFromPointer:Yc(b,h,0!==d),rb:null})},f:function(a,b,c){function d(f){f>>=2;var h=B();return new e(r,h[f+1],h[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=S(c);lc(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{$c:!0})},F:function(a,b){b=S(b);var c="std::string"===b;lc(a,{name:b,fromWireType:function(d){var e=B()[d>>2];if(c)for(var f=d+4,h=0;h<=e;++h){var l=d+4+h;if(h==e||0==u()[l]){f=J(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(h=0;h<e;++h)m[h]=String.fromCharCode(u()[d+4+h]);m=m.join("")}R(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||T("Cannot pass non-string to std::string");var h=(c&&f?function(){return Ma(e)}:function(){return e.length})(),l=O(4+h+1);B()[l>>2]=h;if(c&&f)K(e,l+4,h+1);else if(f)for(f=0;f<h;++f){var m=e.charCodeAt(f);255<m&&(R(l),T("String has UTF-16 code units that do not fit in 8 bits"));u()[l+4+f]=m}else for(f=0;f<h;++f)u()[l+4+f]=e[f];null!==d&&d.push(R,l);return l},argPackAdvance:8,readValueFromPointer:bc,rb:function(d){R(d)}})},u:function(a,b,c){c=S(c);if(2===b){var d=Oa;var e=Pa;
var f=Ra;var h=function(){return v()};var l=1}else 4===b&&(d=Sa,e=Ta,f=Ua,h=function(){return B()},l=2);lc(a,{name:c,fromWireType:function(m){for(var p=B()[m>>2],q=h(),x,y=m+4,k=0;k<=p;++k){var t=m+4+k*b;if(k==p||0==q[t>>l])y=d(y,t-y),void 0===x?x=y:(x+=String.fromCharCode(0),x+=y),y=t+b}R(m);return x},toWireType:function(m,p){"string"!==typeof p&&T("Cannot pass non-string to C++ string type "+c);var q=f(p),x=O(4+q+b);B()[x>>2]=q>>l;e(p,x+4,q+b);null!==m&&m.push(R,x);return x},argPackAdvance:8,readValueFromPointer:bc,
rb:function(m){R(m)}})},d:function(a,b,c,d,e,f){$b[a]={name:S(b),mc:V(c,d),wb:V(e,f),wc:[]}},b:function(a,b,c,d,e,f,h,l,m,p){$b[a].wc.push({Tc:S(b),Zc:c,Xc:V(d,e),Yc:f,rd:h,qd:V(l,m),sd:p})},fa:function(a,b){b=S(b);lc(a,{dd:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},ga:function(a){delete vd[a-1]},U:function(a,b){if(a==b)postMessage({cmd:"processQueuedMainThreadWork"});else if(E)postMessage({targetThread:a,cmd:"processThreadQueue"});else{a=(a=Q.ob[a])&&a.worker;
if(!a)return;a.postMessage({cmd:"processThreadQueue"})}return 1},j:function(a,b,c){a=Zc(a);b=$c(b,"emval::as");var d=[],e=U(d);A()[c>>2]=e;return b.toWireType(d,a)},q:function(a,b,c,d){a=cd[a];b=Zc(b);c=bd(c);a(b,c,null,d)},z:Wc,qa:function(a){if(0===a)return U(dd());a=bd(a);return U(dd()[a])},p:function(a,b){b=fd(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(p){return p.name}).join("_")+"$",e=["retType"],f=[c],h="",l=0;l<a-1;++l)h+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+
l]);d="return function "+fc("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+h+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.dd||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Tc(e).apply(null,f);return ed(a)},na:function(a){a=bd(a);return U(C[a])},
k:function(a,b){a=Zc(a);b=Zc(b);return U(a[b])},J:function(a){4<a&&(W[a].oc+=1)},v:function(a,b,c,d){a=Zc(a);var e=gd[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var h="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)h+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType",
"Module","__emval_register",h+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))($c,C,U);gd[b]=e}return e(a,c,d)},ma:function(){return U([])},sa:function(a){return U(bd(a))},pa:function(){return U({})},ra:function(a){ac(W[a].value);Wc(a)},t:function(a,b,c){a=Zc(a);b=Zc(b);c=Zc(c);a[b]=c},m:function(a,b){a=$c(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},x:hd,y:function(){var a=C.allowedThreads;return a?a:navigator.hardwareConcurrency},D:function(a,b){if(0===
a)a=Date.now();else if(1===a||4===a)a=Mb();else return-1;A()[b>>2]=a/1E3|0;A()[b+4>>2]=a%1E3*1E6|0;return 0},i:function(a,b,c){jd.length=0;var d;for(c>>=2;d=u()[b++];)(d=105>d)&&c&1&&c++,jd.push(d?ja()[c++>>1]:A()[c]),++c;return xb[a].apply(null,jd)},O:Wb,C:function(){},l:Vb,o:yb,s:Mb,ja:function(){return"undefined"!==typeof SharedArrayBuffer},K:function(a,b,c){u().copyWithin(a,b,b+c)},P:function(a,b,c){nd.length=b;c>>=3;for(var d=0;d<b;d++)nd[d]=ja()[c+d];return(0>a?xb[-a-1]:Ve[a]).apply(null,nd)},
L:function(a){var b=u().length;a>>>=0;if(a<=b||838860800<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{n.grow(Math.min(838860800,d)-r.byteLength+65535>>>16);aa(n.buffer);var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Q:function(a,b,c){return pd(a)?qd(a,b,c):sd(a,b,c)},B:function(){},T:function(a,b,c){bb+=1;return setTimeout(function(){--bb;td(function(){P.get(a)(c)})},b)},ha:function(a,b,c,d,e){function f(G){yd(G,
h,p,q,m)}function h(G,Ze){zd(G,Ze.response,function(Qa){--bb;td(function(){t?P.get(t)(Qa):b&&b(Qa)},M)},function(Qa){--bb;td(function(){t?P.get(t)(Qa):b&&b(Qa)},M)})}function l(G){yd(G,x,p,q,m)}function m(G){td(function(){H?P.get(H)(G):e&&e(G)},M)}function p(G){--bb;td(function(){z?P.get(z)(G):c&&c(G)},M)}function q(G){td(function(){D?P.get(D)(G):d&&d(G)},M)}function x(G){--bb;td(function(){t?P.get(t)(G):b&&b(G)},M)}bb+=1;var y=a+112,k=J(y),t=B()[y+36>>2],z=B()[y+40>>2],D=B()[y+44>>2],H=B()[y+48>>
2],N=B()[y+52>>2],qa=!!(N&4),w=!!(N&32),L=!!(N&16),M=!!(N&64);if("EM_IDB_STORE"===k)k=B()[y+84>>2],zd(a,u().slice(k,k+B()[y+88>>2]),x,p);else if("EM_IDB_DELETE"===k)Bd(a,x,p);else if(L){if(w)return 0;yd(a,qa?h:x,p,q,m)}else Ad(a,x,w?p:qa?f:l);return a},aa:function(){throw"unwind";},R:function(a,b){b>>=2;var c=A()[b+6];b={alpha:!!A()[b+0],depth:!!A()[b+1],stencil:!!A()[b+2],antialias:!!A()[b+3],premultipliedAlpha:!!A()[b+4],preserveDrawingBuffer:!!A()[b+5],powerPreference:Jd[c],failIfMajorPerformanceCaveat:!!A()[b+
7],ed:A()[b+8],Rd:A()[b+9],uc:A()[b+10],Sc:A()[b+11],Xd:A()[b+12],Yd:A()[b+13]};a=pd(a);return!a||b.Sc?0:Fd(a,b)},V:Ge,W:He,la:function(a){Jb(a)},_:Ie,Z:Je,H:Ke,Y:Le,oa:function(){var a=self.navigator.userAgent,b=Ma(a)+1,c=O(b);K(a,c,b);return c},M:Me,S:function(a){Q.bd(a)},a:n||C.wasmMemory,ka:function(a){Sb||(Sb=!0,Nb());var b=new Date(A()[a+20>>2]+1900,A()[a+16>>2],A()[a+12>>2],A()[a+8>>2],A()[a+4>>2],A()[a>>2],0),c=A()[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),
6,1)).getTimezoneOffset(),h=e.getTimezoneOffset(),l=Math.min(h,f);0>c?A()[a+32>>2]=Number(f!=h&&l==d):0<c!=(l==d)&&(f=Math.max(h,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));A()[a+24>>2]=b.getDay();c=(b.getTime()-e.getTime())/864E5|0;A()[a+28>>2]=c;A()[a>>2]=b.getSeconds();A()[a+4>>2]=b.getMinutes();A()[a+8>>2]=b.getHours();A()[a+12>>2]=b.getDate();A()[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},A:function(){},G:Se,N:function(a,b,c,d){return Se(a,b,c,d)}};
(function(){function a(e,f){C.asm=e.exports;P=C.asm.ya;$a.unshift(C.asm.ta);Q.qc.push(C.asm.xa);Ea=f;E||qb()}function b(e){a(e.instance,e.module)}function c(e){return ub().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){F("failed to asynchronously prepare wasm: "+f);I(f)})}var d={a:Xe};E||pb();if(C.instantiateWasm)try{return C.instantiateWasm(d,a)}catch(e){return F("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return Da||
"function"!==typeof WebAssembly.instantiateStreaming||rb()||"function"!==typeof fetch?c(b):fetch(sb,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){F("wasm streaming compile failed: "+f);F("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ma);return{}})();C.___wasm_call_ctors=function(){return(C.___wasm_call_ctors=C.asm.ta).apply(null,arguments)};
var R=C._free=function(){return(R=C._free=C.asm.ua).apply(null,arguments)},O=C._malloc=function(){return(O=C._malloc=C.asm.va).apply(null,arguments)},Gb=C._pthread_self=function(){return(Gb=C._pthread_self=C.asm.wa).apply(null,arguments)};C._emscripten_tls_init=function(){return(C._emscripten_tls_init=C.asm.xa).apply(null,arguments)};var Qc=C.___getTypeName=function(){return(Qc=C.___getTypeName=C.asm.za).apply(null,arguments)};
C.___embind_register_native_and_builtin_types=function(){return(C.___embind_register_native_and_builtin_types=C.asm.Aa).apply(null,arguments)};C._emscripten_current_thread_process_queued_calls=function(){return(C._emscripten_current_thread_process_queued_calls=C.asm.Ba).apply(null,arguments)};
var Yb=C._emscripten_main_browser_thread_id=function(){return(Yb=C._emscripten_main_browser_thread_id=C.asm.Ca).apply(null,arguments)},We=C._emscripten_sync_run_in_main_thread_4=function(){return(We=C._emscripten_sync_run_in_main_thread_4=C.asm.Da).apply(null,arguments)},Hb=C._emscripten_main_thread_process_queued_calls=function(){return(Hb=C._emscripten_main_thread_process_queued_calls=C.asm.Ea).apply(null,arguments)},md=C._emscripten_run_in_main_runtime_thread_js=function(){return(md=C._emscripten_run_in_main_runtime_thread_js=
C.asm.Fa).apply(null,arguments)},rd=C.__emscripten_call_on_thread=function(){return(rd=C.__emscripten_call_on_thread=C.asm.Ga).apply(null,arguments)},ud=C.__emscripten_thread_exit=function(){return(ud=C.__emscripten_thread_exit=C.asm.Ha).apply(null,arguments)},Zb=C._pthread_testcancel=function(){return(Zb=C._pthread_testcancel=C.asm.Ia).apply(null,arguments)},Db=C.__emscripten_thread_init=function(){return(Db=C.__emscripten_thread_init=C.asm.Ja).apply(null,arguments)},Ub=C._emscripten_get_global_libc=
function(){return(Ub=C._emscripten_get_global_libc=C.asm.Ka).apply(null,arguments)},Eb=C.___pthread_tsd_run_dtors=function(){return(Eb=C.___pthread_tsd_run_dtors=C.asm.La).apply(null,arguments)},Rb=C.__get_tzname=function(){return(Rb=C.__get_tzname=C.asm.Ma).apply(null,arguments)},Qb=C.__get_daylight=function(){return(Qb=C.__get_daylight=C.asm.Na).apply(null,arguments)},Pb=C.__get_timezone=function(){return(Pb=C.__get_timezone=C.asm.Oa).apply(null,arguments)},kd=C.stackSave=function(){return(kd=C.stackSave=
C.asm.Pa).apply(null,arguments)},Lb=C.stackRestore=function(){return(Lb=C.stackRestore=C.asm.Qa).apply(null,arguments)},ld=C.stackAlloc=function(){return(ld=C.stackAlloc=C.asm.Ra).apply(null,arguments)},Kb=C._emscripten_stack_set_limits=function(){return(Kb=C._emscripten_stack_set_limits=C.asm.Sa).apply(null,arguments)},de=C._memalign=function(){return(de=C._memalign=C.asm.Ta).apply(null,arguments)};C.dynCall_jiji=function(){return(C.dynCall_jiji=C.asm.Ua).apply(null,arguments)};
C.dynCall_ji=function(){return(C.dynCall_ji=C.asm.Va).apply(null,arguments)};C.dynCall_viijii=function(){return(C.dynCall_viijii=C.asm.Wa).apply(null,arguments)};C.dynCall_iiiiij=function(){return(C.dynCall_iiiiij=C.asm.Xa).apply(null,arguments)};C.dynCall_iiiiijj=function(){return(C.dynCall_iiiiijj=C.asm.Ya).apply(null,arguments)};C.dynCall_iiiiiijj=function(){return(C.dynCall_iiiiiijj=C.asm.Za).apply(null,arguments)};
var Fb=C.__emscripten_allow_main_runtime_queued_calls=127788,zb=C.__emscripten_main_thread_futex=691508;C.keepRuntimeAlive=cb;C.PThread=Q;C.PThread=Q;C.wasmMemory=n;C.ExitStatus=Cb;var Ye;function Cb(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ob=function $e(){Ye||af();Ye||(ob=$e)};
function af(){function a(){if(!Ye&&(Ye=!0,C.calledRun=!0,!Fa)){db();la(C);if(C.onRuntimeInitialized)C.onRuntimeInitialized();if(!E){if(C.postRun)for("function"==typeof C.postRun&&(C.postRun=[C.postRun]);C.postRun.length;){var b=C.postRun.shift();ab.unshift(b)}kb(ab)}}}if(!(0<mb))if(E)la(C),db(),postMessage({cmd:"loaded"});else{if(!E){if(C.preRun)for("function"==typeof C.preRun&&(C.preRun=[C.preRun]);C.preRun.length;)lb();kb(Za)}0<mb||(C.setStatus?(C.setStatus("Running..."),setTimeout(function(){setTimeout(function(){C.setStatus("")},
1);a()},1)):a())}}C.run=af;function Jb(a){Ga=a;if(E)throw postMessage({cmd:"exitProcess",returnCode:a}),new Cb(a);cb()||Q.Lc();Ga=a;if(!cb()){Q.Lc();if(C.onExit)C.onExit(a);Fa=!0}ua(a,new Cb(a))}if(C.preInit)for("function"==typeof C.preInit&&(C.preInit=[C.preInit]);0<C.preInit.length;)C.preInit.pop()();E&&(noExitRuntime=!1,Q.cd());af();


  return BlinkInputWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkInputWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkInputWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkInputWasmSDK"] = BlinkInputWasmSDK;
