
var BlinkInputWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkInputWasmSDK) {
  BlinkInputWasmSDK = BlinkInputWasmSDK || {};


var k;k||(k=typeof BlinkInputWasmSDK !== 'undefined' ? BlinkInputWasmSDK : {});var aa,ba;k.ready=new Promise(function(a,b){aa=a;ba=b});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in k)k.hasOwnProperty(da)&&(ca[da]=k[da]);var ea="./this.program";function fa(a,b){throw b;}var ha="object"===typeof window,ja="function"===typeof importScripts,q="",ka;
if(ha||ja)ja?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ja&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var la=k.print||console.log.bind(console),t=k.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(k[da]=ca[da]);ca=null;
k.thisProgram&&(ea=k.thisProgram);k.quit&&(fa=k.quit);var ma;k.wasmBinary&&(ma=k.wasmBinary);var noExitRuntime=k.noExitRuntime||!0;"object"!==typeof WebAssembly&&x("no native wasm support detected");var na,oa=!1,pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?qa(A,a,b):""}
function B(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function ta(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-a&&sa)return sa.decode(A.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ua[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function va(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function wa(a){return 2*a.length}function xa(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ya(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Aa(a){var b=ra(a)+1,c=Ba(b);c&&B(a,J,c,b);return c}var Ca,J,A,ua,E,F,L,Da,Ea;
function Ga(){var a=na.buffer;Ca=a;k.HEAP8=J=new Int8Array(a);k.HEAP16=ua=new Int16Array(a);k.HEAP32=F=new Int32Array(a);k.HEAPU8=A=new Uint8Array(a);k.HEAPU16=E=new Uint16Array(a);k.HEAPU32=L=new Uint32Array(a);k.HEAPF32=Da=new Float32Array(a);k.HEAPF64=Ea=new Float64Array(a)}var M,Ha=[],Ia=[],Ja=[];function Ka(){var a=k.preRun.shift();Ha.unshift(a)}var La=0,Ma=null,Na=null;function Oa(){La++;k.monitorRunDependencies&&k.monitorRunDependencies(La)}
function Pa(){La--;k.monitorRunDependencies&&k.monitorRunDependencies(La);if(0==La&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na)){var a=Na;Na=null;a()}}k.preloadedImages={};k.preloadedAudios={};function x(a){if(k.onAbort)k.onAbort(a);a+="";t(a);oa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Qa(){return N.startsWith("data:application/octet-stream;base64,")}var N;N="BlinkInputWasmSDK.wasm";
if(!Qa()){var Ra=N;N=k.locateFile?k.locateFile(Ra,q):q+Ra}function Sa(){var a=N;try{if(a==N&&ma)return new Uint8Array(ma);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}function Ta(){return ma||!ha&&!ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Sa()}):fetch(N,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+N+"'";return a.arrayBuffer()}).catch(function(){return Sa()})}
var Ua,Va,Wa={126741:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},126877:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},127093:function(a,b){a=z(a);b=z(b);throw Error(a+b);},127203:function(a,b){a=z(a);b=z(b);console.log(a+b)},127301:function(a){throw Error(z(a));},127344:function(){throw Error("Unable to perform that operation while recognizer is in use!");},127427:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},127510:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function Xa(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(k);else{var c=b.mc;"number"===typeof c?void 0===b.ib?M.get(c)():M.get(c)(b.ib):c(void 0===b.ib?null:b.ib)}}}
function Ya(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);F[Za()>>2]=60*f;F[$a()>>2]=Number(b!=e);c=a(c);d=a(d);c=Aa(c);d=Aa(d);e<b?(F[ab()>>2]=c,F[ab()+4>>2]=d):(F[ab()>>2]=d,F[ab()+4>>2]=c)}var bb,cb={};function db(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function eb(a){return this.fromWireType(L[a>>2])}var fb={},gb={},hb={};
function ib(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function jb(a,b){a=ib(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function kb(a){var b=Error,c=jb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var lb=void 0;function mb(a){throw new lb(a);}
function nb(a,b,c){function d(l){l=c(l);l.length!==a.length&&mb("Mismatched type converter count");for(var m=0;m<a.length;++m)O(a[m],l[m])}a.forEach(function(l){hb[l]=b});var e=Array(b.length),f=[],g=0;b.forEach(function(l,m){gb.hasOwnProperty(l)?e[m]=gb[l]:(f.push(l),fb.hasOwnProperty(l)||(fb[l]=[]),fb[l].push(function(){e[m]=gb[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)}
function ob(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var pb=void 0;function P(a){for(var b="";A[a];)b+=pb[A[a++]];return b}var qb=void 0;function Q(a){throw new qb(a);}
function O(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(gb.hasOwnProperty(a)){if(c.Pb)return;Q("Cannot register type '"+d+"' twice")}gb[a]=b;delete hb[a];fb.hasOwnProperty(a)&&(b=fb[a],delete fb[a],b.forEach(function(e){e()}))}function rb(a){Q(a.qa.xa.ua.name+" instance already deleted")}var sb=!1;function tb(){}
function ub(a){--a.count.value;0===a.count.value&&(a.Ba?a.Da.Ja(a.Ba):a.xa.ua.Ja(a.va))}function vb(a){if("undefined"===typeof FinalizationGroup)return vb=function(b){return b},a;sb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.va?ub(c):console.warn("object already deleted: "+c.va)});vb=function(b){sb.register(b,b.qa,b.qa);return b};tb=function(b){sb.unregister(b.qa)};return vb(a)}var wb=void 0,xb=[];
function yb(){for(;xb.length;){var a=xb.pop();a.qa.Na=!1;a["delete"]()}}function zb(){}var Ab={};function Bb(a,b,c){if(void 0===a[b].za){var d=a[b];a[b]=function(){a[b].za.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].za+")!");return a[b].za[arguments.length].apply(this,arguments)};a[b].za=[];a[b].za[d.Xa]=d}}
function Cb(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].za&&void 0!==k[a].za[c])&&Q("Cannot register public name '"+a+"' twice"),Bb(k,a,a),k.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),k[a].za[c]=b):(k[a]=b,void 0!==c&&(k[a].sc=c))}function Db(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Pa=c;this.Ja=d;this.Ea=e;this.Kb=f;this.Wa=g;this.Ib=l;this.Ub=[]}
function Eb(a,b,c){for(;b!==c;)b.Wa||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Wa(a),b=b.Ea;return a}function Fb(a,b){if(null===b)return this.kb&&Q("null is not a valid "+this.name),0;b.qa||Q('Cannot pass "'+Gb(b)+'" as a '+this.name);b.qa.va||Q("Cannot pass deleted object as a pointer of type "+this.name);return Eb(b.qa.va,b.qa.xa.ua,this.ua)}
function Hb(a,b){if(null===b){this.kb&&Q("null is not a valid "+this.name);if(this.$a){var c=this.mb();null!==a&&a.push(this.Ja,c);return c}return 0}b.qa||Q('Cannot pass "'+Gb(b)+'" as a '+this.name);b.qa.va||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.Za&&b.qa.xa.Za&&Q("Cannot convert argument of type "+(b.qa.Da?b.qa.Da.name:b.qa.xa.name)+" to parameter type "+this.name);c=Eb(b.qa.va,b.qa.xa.ua,this.ua);if(this.$a)switch(void 0===b.qa.Ba&&Q("Passing raw pointer to smart pointer is illegal"),
this.ac){case 0:b.qa.Da===this?c=b.qa.Ba:Q("Cannot convert argument of type "+(b.qa.Da?b.qa.Da.name:b.qa.xa.name)+" to parameter type "+this.name);break;case 1:c=b.qa.Ba;break;case 2:if(b.qa.Da===this)c=b.qa.Ba;else{var d=b.clone();c=this.Vb(c,R(function(){d["delete"]()}));null!==a&&a.push(this.Ja,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Ib(a,b){if(null===b)return this.kb&&Q("null is not a valid "+this.name),0;b.qa||Q('Cannot pass "'+Gb(b)+'" as a '+this.name);b.qa.va||Q("Cannot pass deleted object as a pointer of type "+this.name);b.qa.xa.Za&&Q("Cannot convert argument of type "+b.qa.xa.name+" to parameter type "+this.name);return Eb(b.qa.va,b.qa.xa.ua,this.ua)}function Jb(a,b,c){if(b===c)return a;if(void 0===c.Ea)return null;a=Jb(a,b,c.Ea);return null===a?null:c.Ib(a)}var Kb={};
function Lb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.Ea;)b=a.Wa(b),a=a.Ea;return Kb[b]}function Mb(a,b){b.xa&&b.va||mb("makeClassHandle requires ptr and ptrType");!!b.Da!==!!b.Ba&&mb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return vb(Object.create(a,{qa:{value:b}}))}
function S(a,b,c,d){this.name=a;this.ua=b;this.kb=c;this.Za=d;this.$a=!1;this.Ja=this.Vb=this.mb=this.Bb=this.ac=this.Tb=void 0;void 0!==b.Ea?this.toWireType=Hb:(this.toWireType=d?Fb:Ib,this.Fa=null)}function Nb(a,b,c){k.hasOwnProperty(a)||mb("Replacing nonexistant public symbol");void 0!==k[a].za&&void 0!==c?k[a].za[c]=b:(k[a]=b,k[a].Xa=c)}
function Ob(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=k["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=M.get(b).apply(null,c);return d}}function T(a,b){a=P(a);var c=a.includes("j")?Ob(a,b):M.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Pb=void 0;function Qb(a){a=Rb(a);var b=P(a);U(a);return b}
function Sb(a,b){function c(f){e[f]||gb[f]||(hb[f]?hb[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Pb(a+": "+d.map(Qb).join([", "]));}function Tb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Ub(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=jb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Vb(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Fa){l=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+ib(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var v=l?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,db,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);g&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Fa&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].Fa));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Ub(n).apply(null,d)}var Wb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Xb(a){4<a&&0===--V[a].ob&&(V[a]=void 0,Wb.push(a))}
function R(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Wb.length?Wb.pop():V.length;V[b]={ob:1,value:a};return b}}function Gb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Yb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Da[c>>2])};case 3:return function(c){return this.fromWireType(Ea[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Zb(a,b,c){switch(b){case 0:return c?function(d){return J[d]}:function(d){return A[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return E[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function $b(a){a||Q("Cannot use deleted val. handle = "+a);return V[a].value}function ac(a,b){var c=gb[a];void 0===c&&Q(b+" has unknown type "+Qb(a));return c}var bc={};
function cc(a){var b=bc[a];return void 0===b?P(a):b}var dc=[];function ec(){return"object"===typeof globalThis?globalThis:Function("return this")()}function fc(a){var b=dc.length;dc.push(a);return b}function gc(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=ac(F[(b>>2)+d],"parameter "+d);return c}var hc={},ic;ic=function(){return performance.now()};var jc=[],kc=[];function W(a,b){L[a>>2]=b;L[a+4>>2]=b/4294967296|0}var lc;
function mc(a,b,c,d,e){function f(G){var H=0,D=0;G&&(D=u.response?u.response.byteLength:0,H=Ba(D),A.set(new Uint8Array(u.response),H));L[a+12>>2]=H;W(a+16,D)}var g=L[a+8>>2];if(g){var l=z(g),m=a+112,n=z(m);n||(n="GET");var p=L[m+52>>2],v=L[m+56>>2],y=!!L[m+60>>2],h=L[m+68>>2],r=L[m+72>>2];g=L[m+76>>2];var w=L[m+80>>2],C=L[m+84>>2];m=L[m+88>>2];var K=!!(p&1),I=!!(p&2);p=!!(p&64);h=h?z(h):void 0;r=r?z(r):void 0;var ia=w?z(w):void 0,u=new XMLHttpRequest;u.withCredentials=y;u.open(n,l,!p,h,r);p||(u.timeout=
v);u.vc=l;u.responseType="arraybuffer";w&&u.overrideMimeType(ia);if(g)for(;;){n=L[g>>2];if(!n)break;l=L[g+4>>2];if(!l)break;g+=8;n=z(n);l=z(l);u.setRequestHeader(n,l)}kc.push(u);L[a+0>>2]=kc.length;g=C&&m?A.slice(C,C+m):null;u.onload=function(G){f(K&&!I);var H=u.response?u.response.byteLength:0;W(a+24,0);H&&W(a+32,H);E[a+40>>1]=u.readyState;E[a+42>>1]=u.status;u.statusText&&B(u.statusText,A,a+44,64);200<=u.status&&300>u.status?b&&b(a,u,G):c&&c(a,u,G)};u.onerror=function(G){f(K);var H=u.status;W(a+
24,0);W(a+32,u.response?u.response.byteLength:0);E[a+40>>1]=u.readyState;E[a+42>>1]=H;c&&c(a,u,G)};u.ontimeout=function(G){c&&c(a,u,G)};u.onprogress=function(G){var H=K&&I&&u.response?u.response.byteLength:0,D=0;K&&I&&(D=Ba(H),A.set(new Uint8Array(u.response),D));L[a+12>>2]=D;W(a+16,H);W(a+24,G.loaded-H);W(a+32,G.total);E[a+40>>1]=u.readyState;3<=u.readyState&&0===u.status&&0<G.loaded&&(u.status=200);E[a+42>>1]=u.status;u.statusText&&B(u.statusText,A,a+44,64);d&&d(a,u,G);D&&U(D)};u.onreadystatechange=
function(G){E[a+40>>1]=u.readyState;2<=u.readyState&&(E[a+42>>1]=u.status);e&&e(a,u,G)};try{u.send(g)}catch(G){c&&c(a,u,G)}}else c(a,0,"no url specified!")}function nc(a,b){if(!oa)if(b)a();else try{a()}catch(c){if(a=c,!(a instanceof oc||"unwind"===a))throw a&&"object"===typeof a&&a.stack&&t("exception thrown: "+[a,a.stack]),a;}}
function pc(a,b,c,d){var e=lc;if(e){var f=L[a+112+64>>2];f||(f=L[a+8>>2]);var g=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=function(){E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);c(a,0,g)};l.onerror=function(m){E[a+40>>1]=4;E[a+42>>1]=413;B("Payload Too Large",A,a+44,64);d(a,0,m)}}catch(m){d(a,0,m)}}else d(a,0,"IndexedDB not available!")}
function qc(a,b,c){var d=lc;if(d){var e=L[a+112+64>>2];e||(e=L[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(g){if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,m=Ba(l);A.set(new Uint8Array(g),m);L[a+12>>2]=m;W(a+16,l);W(a+24,0);W(a+32,l);E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,g)}else E[a+40>>1]=4,E[a+42>>1]=404,B("Not Found",A,a+44,64),c(a,0,"no data")};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;
B("Not Found",A,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function rc(a,b,c){var d=lc;if(d){var e=L[a+112+64>>2];e||(e=L[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(g){g=g.target.result;L[a+12>>2]=0;W(a+16,0);W(a+24,0);W(a+32,0);E[a+40>>1]=4;E[a+42>>1]=200;B("OK",A,a+44,64);b(a,0,g)};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;B("Not Found",A,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}var sc={};
function tc(){if(!uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in sc)void 0===sc[b]?delete a[b]:a[b]=sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);uc=c}return uc}var uc;
function vc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function wc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=vc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function xc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function yc(a){if("/"===a)return"/";a=wc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function zc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){x("randomDevice")}}
function Ac(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=vc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Bc=[];function Cc(a,b){Bc[a]={input:[],ya:[],Qa:b};Dc(a,Ec)}
var Ec={open:function(a){var b=Bc[a.node.cb];if(!b)throw new X(43);a.Ca=b;a.seekable=!1},close:function(a){a.Ca.Qa.flush(a.Ca)},flush:function(a){a.Ca.Qa.flush(a.Ca)},read:function(a,b,c,d){if(!a.Ca||!a.Ca.Qa.wb)throw new X(60);for(var e=0,f=0;f<d;f++){try{var g=a.Ca.Qa.wb(a.Ca)}catch(l){throw new X(29);}if(void 0===g&&0===e)throw new X(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.Ca||!a.Ca.Qa.lb)throw new X(60);try{for(var e=
0;e<d;e++)a.Ca.Qa.lb(a.Ca,b[c+e])}catch(f){throw new X(29);}d&&(a.node.timestamp=Date.now());return e}},Gc={wb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Fc(b,!0)}return a.input.shift()},lb:function(a,b){null===b||10===b?(la(qa(a.ya,0)),a.ya=[]):0!=b&&a.ya.push(b)},flush:function(a){a.ya&&0<a.ya.length&&
(la(qa(a.ya,0)),a.ya=[])}},Hc={lb:function(a,b){null===b||10===b?(t(qa(a.ya,0)),a.ya=[]):0!=b&&a.ya.push(b)},flush:function(a){a.ya&&0<a.ya.length&&(t(qa(a.ya,0)),a.ya=[])}},Y={Ga:null,Ia:function(){return Y.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new X(63);Y.Ga||(Y.Ga={dir:{node:{Ka:Y.sa.Ka,Ha:Y.sa.Ha,Sa:Y.sa.Sa,ab:Y.sa.ab,Db:Y.sa.Db,Fb:Y.sa.Fb,Eb:Y.sa.Eb,Cb:Y.sa.Cb,eb:Y.sa.eb},stream:{Ma:Y.ta.Ma}},file:{node:{Ka:Y.sa.Ka,Ha:Y.sa.Ha},
stream:{Ma:Y.ta.Ma,read:Y.ta.read,write:Y.ta.write,pb:Y.ta.pb,xb:Y.ta.xb,zb:Y.ta.zb}},link:{node:{Ka:Y.sa.Ka,Ha:Y.sa.Ha,Ua:Y.sa.Ua},stream:{}},qb:{node:{Ka:Y.sa.Ka,Ha:Y.sa.Ha},stream:Ic}});c=Jc(a,b,c,d);16384===(c.mode&61440)?(c.sa=Y.Ga.dir.node,c.ta=Y.Ga.dir.stream,c.ra={}):32768===(c.mode&61440)?(c.sa=Y.Ga.file.node,c.ta=Y.Ga.file.stream,c.wa=0,c.ra=null):40960===(c.mode&61440)?(c.sa=Y.Ga.link.node,c.ta=Y.Ga.link.stream):8192===(c.mode&61440)&&(c.sa=Y.Ga.qb.node,c.ta=Y.Ga.qb.stream);c.timestamp=
Date.now();a&&(a.ra[b]=c,a.timestamp=c.timestamp);return c},nc:function(a){return a.ra?a.ra.subarray?a.ra.subarray(0,a.wa):new Uint8Array(a.ra):new Uint8Array(0)},sb:function(a,b){var c=a.ra?a.ra.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.ra,a.ra=new Uint8Array(b),0<a.wa&&a.ra.set(c.subarray(0,a.wa),0))},Wb:function(a,b){if(a.wa!=b)if(0==b)a.ra=null,a.wa=0;else{var c=a.ra;a.ra=new Uint8Array(b);c&&a.ra.set(c.subarray(0,Math.min(b,a.wa)));a.wa=b}},sa:{Ka:function(a){var b=
{};b.lc=8192===(a.mode&61440)?a.id:1;b.pc=a.id;b.mode=a.mode;b.rc=1;b.uid=0;b.oc=0;b.cb=a.cb;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.wa:40960===(a.mode&61440)?a.link.length:0;b.ic=new Date(a.timestamp);b.qc=new Date(a.timestamp);b.kc=new Date(a.timestamp);b.Gb=4096;b.jc=Math.ceil(b.size/b.Gb);return b},Ha:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Y.Wb(a,b.size)},Sa:function(){throw Kc[44];},ab:function(a,b,c,
d){return Y.createNode(a,b,c,d)},Db:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Lc(b,c)}catch(f){}if(d)for(var e in d.ra)throw new X(55);}delete a.parent.ra[a.name];a.parent.timestamp=Date.now();a.name=c;b.ra[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Fb:function(a,b){delete a.ra[b];a.timestamp=Date.now()},Eb:function(a,b){var c=Lc(a,b),d;for(d in c.ra)throw new X(55);delete a.ra[b];a.timestamp=Date.now()},Cb:function(a){var b=[".",".."],c;for(c in a.ra)a.ra.hasOwnProperty(c)&&b.push(c);
return b},eb:function(a,b,c){a=Y.createNode(a,b,41471,0);a.link=c;return a},Ua:function(a){if(40960!==(a.mode&61440))throw new X(28);return a.link}},ta:{read:function(a,b,c,d,e){var f=a.node.ra;if(e>=a.node.wa)return 0;a=Math.min(a.node.wa-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===J.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ra||a.ra.subarray)){if(f)return a.ra=b.subarray(c,
c+d),a.wa=d;if(0===a.wa&&0===e)return a.ra=b.slice(c,c+d),a.wa=d;if(e+d<=a.wa)return a.ra.set(b.subarray(c,c+d),e),d}Y.sb(a,e+d);if(a.ra.subarray&&b.subarray)a.ra.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.ra[e+f]=b[c+f];a.wa=Math.max(a.wa,e+d);return d},Ma:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.wa);if(0>b)throw new X(28);return b},pb:function(a,b,c){Y.sb(a.node,b+c);a.node.wa=Math.max(a.node.wa,b+c)},xb:function(a,b,c,d,e,f){if(0!==b)throw new X(28);
if(32768!==(a.node.mode&61440))throw new X(43);a=a.node.ra;if(f&2||a.buffer!==Ca){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;c=65536*Math.ceil(c/65536);(f=Mc(65536,c))?(A.fill(0,f,f+c),c=f):c=0;if(!c)throw new X(48);J.set(a,c)}else d=!1,c=a.byteOffset;return{va:c,hc:d}},zb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new X(43);if(e&2)return 0;Y.ta.write(a,b,0,d,c,!1);return 0}}},Nc=null,Oc={},Pc=[],Qc=1,Rc=null,Sc=!0,Tc={},X=null,Kc={};
function Uc(a,b){a=Ac("/",a);b=b||{};if(!a)return{path:"",node:null};var c={vb:!0,nb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.nb)throw new X(32);a=vc(a.split("/").filter(function(g){return!!g}),!1);var e=Nc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Lc(e,a[d]);c=wc(c+"/"+a[d]);e.bb&&(!f||f&&b.vb)&&(e=e.bb.root);if(!f||b.ub)for(f=0;40960===(e.mode&61440);)if(e=Vc(c),c=Ac(xc(c),e),e=Uc(c,{nb:b.nb}).node,40<f++)throw new X(32);}return{path:c,node:e}}
function Wc(a){for(var b;;){if(a===a.parent)return a=a.Ia.yb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Xc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Rc.length}function Lc(a,b){var c;if(c=(c=Yc(a,"x"))?c:a.sa.Sa?0:2)throw new X(c,a);for(c=Rc[Xc(a.id,b)];c;c=c.Sb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.sa.Sa(a,b)}
function Jc(a,b,c,d){a=new Zc(a,b,c,d);b=Xc(a.parent.id,a.name);a.Sb=Rc[b];return Rc[b]=a}var $c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function ad(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Yc(a,b){if(Sc)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function bd(a,b){try{return Lc(a,b),20}catch(c){}return Yc(a,"wx")}
function cd(){var a=4096;for(var b=0;b<=a;b++)if(!Pc[b])return b;throw new X(33);}function dd(a){ed||(ed=function(){},ed.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new ed,c;for(c in a)b[c]=a[c];a=b;b=cd();a.Oa=b;return Pc[b]=a}var Ic={open:function(a){a.ta=Oc[a.node.cb].ta;a.ta.open&&a.ta.open(a)},Ma:function(){throw new X(70);}};function Dc(a,b){Oc[a]={ta:b}}
function fd(a,b){var c="/"===b,d=!b;if(c&&Nc)throw new X(10);if(!c&&!d){var e=Uc(b,{vb:!1});b=e.path;e=e.node;if(e.bb)throw new X(10);if(16384!==(e.mode&61440))throw new X(54);}b={type:a,tc:{},yb:b,Rb:[]};a=a.Ia(b);a.Ia=b;b.root=a;c?Nc=a:e&&(e.bb=b,e.Ia&&e.Ia.Rb.push(b))}function gd(a,b,c){var d=Uc(a,{parent:!0}).node;a=yc(a);if(!a||"."===a||".."===a)throw new X(28);var e=bd(d,a);if(e)throw new X(e);if(!d.sa.ab)throw new X(63);return d.sa.ab(d,a,b,c)}function Z(a){return gd(a,16895,0)}
function hd(a,b,c){"undefined"===typeof c&&(c=b,b=438);gd(a,b|8192,c)}function jd(a,b){if(!Ac(a))throw new X(44);var c=Uc(b,{parent:!0}).node;if(!c)throw new X(44);b=yc(b);var d=bd(c,b);if(d)throw new X(d);if(!c.sa.eb)throw new X(63);c.sa.eb(c,b,a)}function Vc(a){a=Uc(a).node;if(!a)throw new X(44);if(!a.sa.Ua)throw new X(28);return Ac(Wc(a.parent),a.sa.Ua(a))}
function kd(a,b){if(""===a)throw new X(44);if("string"===typeof b){var c=$c[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=wc(a);try{e=Uc(a,{ub:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new X(20);}else e=gd(a,d,0),c=!0;if(!e)throw new X(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new X(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==ad(b)||b&512)?31:Yc(e,ad(b)):44))throw new X(d);if(b&512){d=e;d="string"===typeof d?Uc(d,{ub:!0}).node:d;if(!d.sa.Ha)throw new X(63);if(16384===(d.mode&61440))throw new X(31);if(32768!==(d.mode&61440))throw new X(28);if(c=Yc(d,"w"))throw new X(c);d.sa.Ha(d,{size:0,timestamp:Date.now()})}b&=-131713;e=dd({node:e,path:Wc(e),flags:b,seekable:!0,position:0,ta:e.ta,fc:[],error:!1});e.ta.open&&e.ta.open(e);!k.logReadFiles||b&1||(ld||(ld={}),a in ld||(ld[a]=1,t("FS.trackingDelegate error on read file: "+
a)));try{Tc.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Tc.onOpenFile(a,e))}catch(f){t("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}}function md(a,b,c){if(null===a.Oa)throw new X(8);if(!a.seekable||!a.ta.Ma)throw new X(70);if(0!=c&&1!=c&&2!=c)throw new X(28);a.position=a.ta.Ma(a,b,c);a.fc=[]}
function nd(){X||(X=function(a,b){this.node=b;this.Xb=function(c){this.Ya=c};this.Xb(a);this.message="FS error"},X.prototype=Error(),X.prototype.constructor=X,[44].forEach(function(a){Kc[a]=new X(a);Kc[a].stack="<generic error, no stack>"}))}var od;function pd(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function qd(a,b,c){a=wc("/dev/"+a);var d=pd(!!b,!!c);rd||(rd=64);var e=rd++<<8|0;Dc(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,l,m){for(var n=0,p=0;p<m;p++){try{var v=b()}catch(y){throw new X(29);}if(void 0===v&&0===n)throw new X(6);if(null===v||void 0===v)break;n++;g[l+p]=v}n&&(f.node.timestamp=Date.now());return n},write:function(f,g,l,m){for(var n=0;n<m;n++)try{c(g[l+n])}catch(p){throw new X(29);}m&&(f.node.timestamp=Date.now());return n}});
hd(a,d,e)}var rd,sd={},ed,ld;function td(a){a=Pc[a];if(!a)throw new X(8);return a}function ud(a,b){ud.Ab||(ud.Ab=zc());for(var c=0;c<b;c++)J[a+c>>0]=ud.Ab();return 0}function vd(a){return 0===a%4&&(0!==a%100||0===a%400)}function wd(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var xd=[31,29,31,30,31,30,31,31,30,31,30,31],yd=[31,28,31,30,31,30,31,31,30,31,30,31];
function zd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(vd(a.getFullYear())?xd:yd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Ad(a,b,c,d){function e(h,r,w){for(h="number"===typeof h?h.toString():h||"";h.length<r;)h=w[0]+h;return h}function f(h,r){return e(h,r,"0")}function g(h,r){function w(K){return 0>K?-1:0<K?1:0}var C;0===(C=w(h.getFullYear()-r.getFullYear()))&&0===(C=w(h.getMonth()-r.getMonth()))&&(C=w(h.getDate()-r.getDate()));return C}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){h=zd(new Date(h.Aa+1900,0,1),h.hb);var r=new Date(h.getFullYear()+1,0,4),w=l(new Date(h.getFullYear(),0,4));r=l(r);return 0>=g(w,h)?0>=g(r,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=F[d+40>>2];d={dc:F[d>>2],cc:F[d+4>>2],fb:F[d+8>>2],Va:F[d+12>>2],Ra:F[d+16>>2],Aa:F[d+20>>2],gb:F[d+24>>2],hb:F[d+28>>2],uc:F[d+32>>2],bc:F[d+
36>>2],ec:n?z(n):""};c=z(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
y="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return v[h.gb].substring(0,3)},"%A":function(h){return v[h.gb]},"%b":function(h){return y[h.Ra].substring(0,3)},"%B":function(h){return y[h.Ra]},"%C":function(h){return f((h.Aa+1900)/100|0,2)},"%d":function(h){return f(h.Va,2)},"%e":function(h){return e(h.Va,2," ")},"%g":function(h){return m(h).toString().substring(2)},"%G":function(h){return m(h)},"%H":function(h){return f(h.fb,
2)},"%I":function(h){h=h.fb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.Va+wd(vd(h.Aa+1900)?xd:yd,h.Ra-1),3)},"%m":function(h){return f(h.Ra+1,2)},"%M":function(h){return f(h.cc,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.fb&&12>h.fb?"AM":"PM"},"%S":function(h){return f(h.dc,2)},"%t":function(){return"\t"},"%u":function(h){return h.gb||7},"%U":function(h){var r=new Date(h.Aa+1900,0,1),w=0===r.getDay()?r:zd(r,7-r.getDay());h=new Date(h.Aa+1900,h.Ra,h.Va);return 0>
g(w,h)?f(Math.ceil((31-w.getDate()+(wd(vd(h.getFullYear())?xd:yd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(w,r)?"01":"00"},"%V":function(h){var r=new Date(h.Aa+1901,0,4),w=l(new Date(h.Aa+1900,0,4));r=l(r);var C=zd(new Date(h.Aa+1900,0,1),h.hb);return 0>g(C,w)?"53":0>=g(r,C)?"01":f(Math.ceil((w.getFullYear()<h.Aa+1900?h.hb+32-w.getDate():h.hb+1-w.getDate())/7),2)},"%w":function(h){return h.gb},"%W":function(h){var r=new Date(h.Aa,0,1),w=1===r.getDay()?r:zd(r,0===r.getDay()?1:7-r.getDay()+1);h=
new Date(h.Aa+1900,h.Ra,h.Va);return 0>g(w,h)?f(Math.ceil((31-w.getDate()+(wd(vd(h.getFullYear())?xd:yd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(w,r)?"01":"00"},"%y":function(h){return(h.Aa+1900).toString().substring(2)},"%Y":function(h){return h.Aa+1900},"%z":function(h){h=h.bc;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.ec},"%%":function(){return"%"}};for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));p=Fc(c,
!1);if(p.length>b)return 0;J.set(p,a);return p.length-1}lb=k.InternalError=kb("InternalError");for(var Bd=Array(256),Cd=0;256>Cd;++Cd)Bd[Cd]=String.fromCharCode(Cd);pb=Bd;qb=k.BindingError=kb("BindingError");zb.prototype.isAliasOf=function(a){if(!(this instanceof zb&&a instanceof zb))return!1;var b=this.qa.xa.ua,c=this.qa.va,d=a.qa.xa.ua;for(a=a.qa.va;b.Ea;)c=b.Wa(c),b=b.Ea;for(;d.Ea;)a=d.Wa(a),d=d.Ea;return b===d&&c===a};
zb.prototype.clone=function(){this.qa.va||rb(this);if(this.qa.Ta)return this.qa.count.value+=1,this;var a=vb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.qa;a=a(c.call(b,d,{qa:{value:{count:e.count,Na:e.Na,Ta:e.Ta,va:e.va,xa:e.xa,Ba:e.Ba,Da:e.Da}}}));a.qa.count.value+=1;a.qa.Na=!1;return a};zb.prototype["delete"]=function(){this.qa.va||rb(this);this.qa.Na&&!this.qa.Ta&&Q("Object already scheduled for deletion");tb(this);ub(this.qa);this.qa.Ta||(this.qa.Ba=void 0,this.qa.va=void 0)};
zb.prototype.isDeleted=function(){return!this.qa.va};zb.prototype.deleteLater=function(){this.qa.va||rb(this);this.qa.Na&&!this.qa.Ta&&Q("Object already scheduled for deletion");xb.push(this);1===xb.length&&wb&&wb(yb);this.qa.Na=!0;return this};S.prototype.Lb=function(a){this.Bb&&(a=this.Bb(a));return a};S.prototype.rb=function(a){this.Ja&&this.Ja(a)};S.prototype.argPackAdvance=8;S.prototype.readValueFromPointer=eb;S.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
S.prototype.fromWireType=function(a){function b(){return this.$a?Mb(this.ua.Pa,{xa:this.Tb,va:c,Da:this,Ba:a}):Mb(this.ua.Pa,{xa:this,va:a})}var c=this.Lb(a);if(!c)return this.rb(a),null;var d=Lb(this.ua,c);if(void 0!==d){if(0===d.qa.count.value)return d.qa.va=c,d.qa.Ba=a,d.clone();d=d.clone();this.rb(a);return d}d=this.ua.Kb(c);d=Ab[d];if(!d)return b.call(this);d=this.Za?d.Hb:d.pointerType;var e=Jb(c,this.ua,d.ua);return null===e?b.call(this):this.$a?Mb(d.ua.Pa,{xa:d,va:e,Da:this,Ba:a}):Mb(d.ua.Pa,
{xa:d,va:e})};k.getInheritedInstanceCount=function(){return Object.keys(Kb).length};k.getLiveInheritedInstances=function(){var a=[],b;for(b in Kb)Kb.hasOwnProperty(b)&&a.push(Kb[b]);return a};k.flushPendingDeletes=yb;k.setDelayFunction=function(a){wb=a;xb.length&&wb&&wb(yb)};Pb=k.UnboundTypeError=kb("UnboundTypeError");k.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){lc=a;Pa()},function(){lc=!1;Pa()});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Oa();
function Zc(a,b,c,d){a||(a=this);this.parent=a;this.Ia=a.Ia;this.bb=null;this.id=Qc++;this.name=b;this.mode=c;this.sa={};this.ta={};this.cb=d}Object.defineProperties(Zc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});nd();Rc=Array(4096);fd(Y,"/");Z("/tmp");Z("/home");Z("/home/web_user");
(function(){Z("/dev");Dc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});hd("/dev/null",259);Cc(1280,Gc);Cc(1536,Hc);hd("/dev/tty",1280);hd("/dev/tty1",1536);var a=zc();qd("random",a);qd("urandom",a);Z("/dev/shm");Z("/dev/shm/tmp")})();
(function(){Z("/proc");var a=Z("/proc/self");Z("/proc/self/fd");fd({Ia:function(){var b=Jc(a,"fd",16895,73);b.sa={Sa:function(c,d){var e=Pc[+d];if(!e)throw new X(8);c={parent:null,Ia:{yb:"fake"},sa:{Ua:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function Fc(a,b){var c=Array(ra(a)+1);a=B(a,c,0,c.length);b&&(c.length=a);return c}
var Dd={I:function(a,b){bb||(bb=!0,Ya());a=new Date(1E3*F[a>>2]);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);F[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;F[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;F[b+32>>2]=a;
a=F[ab()+(a?4:0)>>2];F[b+40>>2]=a;return b},b:function(a){var b=cb[a];delete cb[a];var c=b.mb,d=b.Ja,e=b.tb,f=e.map(function(g){return g.Ob}).concat(e.map(function(g){return g.Zb}));nb([a],f,function(g){var l={};e.forEach(function(m,n){var p=g[n],v=m.Mb,y=m.Nb,h=g[n+e.length],r=m.Yb,w=m.$b;l[m.Jb]={read:function(C){return p.fromWireType(v(y,C))},write:function(C,K){var I=[];r(w,C,h.toWireType(I,K));db(I)}}});return[{name:b.name,fromWireType:function(m){var n={},p;for(p in l)n[p]=l[p].read(m);d(m);
return n},toWireType:function(m,n){for(var p in l)if(!(p in n))throw new TypeError('Missing field:  "'+p+'"');var v=c();for(p in l)l[p].write(v,n[p]);null!==m&&m.push(d,v);return v},argPackAdvance:8,readValueFromPointer:eb,Fa:d}]})},B:function(){},N:function(a,b,c,d,e){var f=ob(c);b=P(b);O(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var l=J;else if(2===c)l=ua;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+
b);return this.fromWireType(l[g>>f])},Fa:null})},k:function(a,b,c,d,e,f,g,l,m,n,p,v,y){p=P(p);f=T(e,f);l&&(l=T(g,l));n&&(n=T(m,n));y=T(v,y);var h=ib(p);Cb(h,function(){Sb("Cannot construct "+p+" due to unbound types",[d])});nb([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var w=r.ua;var C=w.Pa}else C=zb.prototype;r=jb(h,function(){if(Object.getPrototypeOf(this)!==K)throw new qb("Use 'new' to construct "+p);if(void 0===I.La)throw new qb(p+" has no accessible constructor");var u=I.La[arguments.length];
if(void 0===u)throw new qb("Tried to invoke ctor of "+p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(I.La).toString()+") parameters instead!");return u.apply(this,arguments)});var K=Object.create(C,{constructor:{value:r}});r.prototype=K;var I=new Db(p,r,K,y,w,f,l,n);w=new S(p,I,!0,!1);C=new S(p+"*",I,!1,!1);var ia=new S(p+" const*",I,!1,!0);Ab[a]={pointerType:C,Hb:ia};Nb(h,r);return[w,C,ia]})},n:function(a,b,c,d,e,f){0<b||x("Assertion failed: undefined");var g=
Tb(b,c);e=T(d,e);nb([],[a],function(l){l=l[0];var m="constructor "+l.name;void 0===l.ua.La&&(l.ua.La=[]);if(void 0!==l.ua.La[b-1])throw new qb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+l.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");l.ua.La[b-1]=function(){Sb("Cannot construct "+l.name+" due to unbound types",g)};nb([],g,function(n){n.splice(1,0,null);l.ua.La[b-1]=Vb(m,n,null,e,
f);return[]});return[]})},d:function(a,b,c,d,e,f,g,l){var m=Tb(c,d);b=P(b);f=T(e,f);nb([],[a],function(n){function p(){Sb("Cannot call "+v+" due to unbound types",m)}n=n[0];var v=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);l&&n.ua.Ub.push(b);var y=n.ua.Pa,h=y[b];void 0===h||void 0===h.za&&h.className!==n.name&&h.Xa===c-2?(p.Xa=c-2,p.className=n.name,y[b]=p):(Bb(y,b,v),y[b].za[c-2]=p);nb([],m,function(r){r=Vb(v,r,n,f,g);void 0===y[b].za?(r.Xa=c-2,y[b]=r):y[b].za[c-2]=r;return[]});return[]})},
M:function(a,b){b=P(b);O(a,{name:b,fromWireType:function(c){var d=V[c].value;Xb(c);return d},toWireType:function(c,d){return R(d)},argPackAdvance:8,readValueFromPointer:eb,Fa:null})},w:function(a,b,c){c=ob(c);b=P(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Gb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Yb(b,c),Fa:null})},r:function(a,b,c,d,e,f){var g=Tb(b,c);
a=P(a);e=T(d,e);Cb(a,function(){Sb("Cannot call "+a+" due to unbound types",g)},b-1);nb([],g,function(l){Nb(a,Vb(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},f:function(a,b,c,d,e){function f(n){return n}b=P(b);-1===e&&(e=4294967295);var g=ob(c);if(0===d){var l=32-8*c;f=function(n){return n<<l>>>l}}var m=b.includes("unsigned");O(a,{name:b,fromWireType:f,toWireType:function(n,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Gb(p)+'" to '+this.name);
if(p<d||p>e)throw new TypeError('Passing a number "'+Gb(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:Zb(b,g,0!==d),Fa:null})},e:function(a,b,c){function d(f){f>>=2;var g=L;return new e(Ca,g[f+1],g[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=P(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{Pb:!0})},x:function(a,b){b=P(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=L[d>>2];if(c)for(var f=d+4,g=0;g<=e;++g){var l=d+4+g;if(g==e||0==A[l]){f=z(f,l-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=l+1}}else{m=Array(e);for(g=0;g<e;++g)m[g]=String.fromCharCode(A[d+4+g]);m=m.join("")}U(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||Q("Cannot pass non-string to std::string");var g=(c&&f?function(){return ra(e)}:function(){return e.length})(),l=Ba(4+g+1);L[l>>2]=g;if(c&&f)B(e,A,l+4,g+1);else if(f)for(f=0;f<g;++f){var m=e.charCodeAt(f);255<m&&(U(l),Q("String has UTF-16 code units that do not fit in 8 bits"));A[l+4+f]=m}else for(f=0;f<g;++f)A[l+4+f]=e[f];null!==d&&d.push(U,l);return l},argPackAdvance:8,readValueFromPointer:eb,Fa:function(d){U(d)}})},p:function(a,b,c){c=P(c);if(2===b){var d=ta;var e=va;var f=
wa;var g=function(){return E};var l=1}else 4===b&&(d=xa,e=ya,f=za,g=function(){return L},l=2);O(a,{name:c,fromWireType:function(m){for(var n=L[m>>2],p=g(),v,y=m+4,h=0;h<=n;++h){var r=m+4+h*b;if(h==n||0==p[r>>l])y=d(y,r-y),void 0===v?v=y:(v+=String.fromCharCode(0),v+=y),y=r+b}U(m);return v},toWireType:function(m,n){"string"!==typeof n&&Q("Cannot pass non-string to C++ string type "+c);var p=f(n),v=Ba(4+p+b);L[v>>2]=p>>l;e(n,v+4,p+b);null!==m&&m.push(U,v);return v},argPackAdvance:8,readValueFromPointer:eb,
Fa:function(m){U(m)}})},c:function(a,b,c,d,e,f){cb[a]={name:P(b),mb:T(c,d),Ja:T(e,f),tb:[]}},a:function(a,b,c,d,e,f,g,l,m,n){cb[a].tb.push({Jb:P(b),Ob:c,Mb:T(d,e),Nb:f,Zb:g,Yb:T(l,m),$b:n})},O:function(a,b){b=P(b);O(a,{Qb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},P:function(a){delete kc[a-1]},h:function(a,b,c){a=$b(a);b=ac(b,"emval::as");var d=[],e=R(d);F[c>>2]=e;return b.toWireType(d,a)},m:function(a,b,c,d){a=dc[a];b=$b(b);c=cc(c);a(b,c,null,d)},t:Xb,X:function(a){if(0===
a)return R(ec());a=cc(a);return R(ec()[a])},l:function(a,b){b=gc(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(n){return n.name}).join("_")+"$",e=["retType"],f=[c],g="",l=0;l<a-1;++l)g+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+ib("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+
g+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Qb||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Ub(e).apply(null,f);return fc(a)},V:function(a){a=cc(a);return R(k[a])},i:function(a,b){a=$b(a);b=$b(b);return R(a[b])},z:function(a){4<a&&(V[a].ob+=1)},q:function(a,b,c,d){a=$b(a);var e=hc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var g="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";
for(f=0;f<b;++f)g+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",g+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(ac,k,R);hc[b]=e}return e(a,c,d)},U:function(){return R([])},Z:function(a){return R(cc(a))},W:function(){return R({})},Y:function(a){db(V[a].value);
Xb(a)},o:function(a,b,c){a=$b(a);b=$b(b);c=$b(c);a[b]=c},j:function(a,b){a=ac(a,"_emval_take_value");a=a.readValueFromPointer(b);return R(a)},s:function(){x()},v:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=ic();else return-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},g:function(a,b,c){jc.length=0;var d;for(c>>=2;d=A[b++];)(d=105>d)&&c&1&&c++,jc.push(d?Ea[c++>>1]:F[c]),++c;return Wa[a].apply(null,jc)},R:function(){return!ja},C:function(a,b,c){A.copyWithin(a,b,b+c)},D:function(a){var b=
A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{na.grow(Math.min(2147483648,d)-Ca.byteLength+65535>>>16);Ga();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Q:function(a,b,c,d,e){function f(D){mc(D,g,n,p,m)}function g(D,Fd){pc(D,Fd.response,function(Fa){nc(function(){r?M.get(r)(Fa):b&&b(Fa)},H)},function(Fa){nc(function(){r?M.get(r)(Fa):b&&b(Fa)},H)})}function l(D){mc(D,v,n,
p,m)}function m(D){nc(function(){K?M.get(K)(D):e&&e(D)},H)}function n(D){nc(function(){w?M.get(w)(D):c&&c(D)},H)}function p(D){nc(function(){C?M.get(C)(D):d&&d(D)},H)}function v(D){nc(function(){r?M.get(r)(D):b&&b(D)},H)}var y=a+112,h=z(y),r=L[y+36>>2],w=L[y+40>>2],C=L[y+44>>2],K=L[y+48>>2],I=L[y+52>>2],ia=!!(I&4),u=!!(I&32),G=!!(I&16),H=!!(I&64);if("EM_IDB_STORE"===h)h=L[y+84>>2],pc(a,A.slice(h,h+L[y+88>>2]),v,n);else if("EM_IDB_DELETE"===h)rc(a,v,n);else if(G){if(u)return 0;mc(a,ia?g:v,n,p,m)}else qc(a,
v,u?n:ia?f:l);return a},G:function(a,b){var c=0;tc().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)J[e++>>0]=d.charCodeAt(f);J[e>>0]=0;c+=d.length+1});return 0},H:function(a,b){var c=tc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},T:function(a){if(!noExitRuntime){if(k.onExit)k.onExit(a);oa=!0}fa(a,new oc(a))},L:function(a){try{var b=td(a);if(null===b.Oa)throw new X(8);b.jb&&(b.jb=null);try{b.ta.close&&b.ta.close(b)}catch(c){throw c;
}finally{Pc[b.Oa]=null}b.Oa=null;return 0}catch(c){return"undefined"!==typeof sd&&c instanceof X||x(c),c.Ya}},K:function(a,b,c,d){try{a:{for(var e=td(a),f=a=0;f<c;f++){var g=F[b+(8*f+4)>>2],l=e,m=F[b+8*f>>2],n=g,p=void 0,v=J;if(0>n||0>p)throw new X(28);if(null===l.Oa)throw new X(8);if(1===(l.flags&2097155))throw new X(8);if(16384===(l.node.mode&61440))throw new X(31);if(!l.ta.read)throw new X(28);var y="undefined"!==typeof p;if(!y)p=l.position;else if(!l.seekable)throw new X(70);var h=l.ta.read(l,
v,m,n,p);y||(l.position+=h);var r=h;if(0>r){var w=-1;break a}a+=r;if(r<g)break}w=a}F[d>>2]=w;return 0}catch(C){return"undefined"!==typeof sd&&C instanceof X||x(C),C.Ya}},A:function(a,b,c,d,e){try{var f=td(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;md(f,a,d);Va=[f.position>>>0,(Ua=f.position,1<=+Math.abs(Ua)?0<Ua?(Math.min(+Math.floor(Ua/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Ua-+(~~Ua>>>0))/4294967296)>>>0:0)];F[e>>2]=Va[0];F[e+4>>2]=Va[1];f.jb&&0===a&&
0===d&&(f.jb=null);return 0}catch(g){return"undefined"!==typeof sd&&g instanceof X||x(g),g.Ya}},J:function(a,b,c,d){try{a:{for(var e=td(a),f=a=0;f<c;f++){var g=e,l=F[b+8*f>>2],m=F[b+(8*f+4)>>2],n=void 0,p=J;if(0>m||0>n)throw new X(28);if(null===g.Oa)throw new X(8);if(0===(g.flags&2097155))throw new X(8);if(16384===(g.node.mode&61440))throw new X(31);if(!g.ta.write)throw new X(28);g.seekable&&g.flags&1024&&md(g,0,2);var v="undefined"!==typeof n;if(!v)n=g.position;else if(!g.seekable)throw new X(70);
var y=g.ta.write(g,p,l,m,n,void 0);v||(g.position+=y);try{if(g.path&&Tc.onWriteToFile)Tc.onWriteToFile(g.path)}catch(w){t("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+w.message)}var h=y;if(0>h){var r=-1;break a}a+=h}r=a}F[d>>2]=r;return 0}catch(w){return"undefined"!==typeof sd&&w instanceof X||x(w),w.Ya}},_:function(){var a=self.navigator.userAgent,b=ra(a)+1,c=Ba(b);B(a,A,c,b);return c},E:ud,S:function(a){bb||(bb=!0,Ya());var b=new Date(F[a+20>>2]+1900,F[a+16>>2],F[a+
12>>2],F[a+8>>2],F[a+4>>2],F[a>>2],0),c=F[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=e.getTimezoneOffset(),l=Math.min(g,f);0>c?F[a+32>>2]=Number(f!=g&&l==d):0<c!=(l==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));F[a+24>>2]=b.getDay();F[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;F[a>>2]=b.getSeconds();F[a+4>>2]=b.getMinutes();F[a+8>>2]=b.getHours();F[a+12>>2]=b.getDate();F[a+16>>2]=b.getMonth();return b.getTime()/
1E3|0},u:function(){},y:Ad,F:function(a,b,c,d){return Ad(a,b,c,d)}};
(function(){function a(e){k.asm=e.exports;na=k.asm.$;Ga();M=k.asm.ja;Ia.unshift(k.asm.aa);Pa()}function b(e){a(e.instance)}function c(e){return Ta().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){t("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:Dd};Oa();if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ma||"function"!==typeof WebAssembly.instantiateStreaming||
Qa()||"function"!==typeof fetch?c(b):fetch(N,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();k.___wasm_call_ctors=function(){return(k.___wasm_call_ctors=k.asm.aa).apply(null,arguments)};
var U=k._free=function(){return(U=k._free=k.asm.ba).apply(null,arguments)},Ba=k._malloc=function(){return(Ba=k._malloc=k.asm.ca).apply(null,arguments)},Rb=k.___getTypeName=function(){return(Rb=k.___getTypeName=k.asm.da).apply(null,arguments)};k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.ea).apply(null,arguments)};
var ab=k.__get_tzname=function(){return(ab=k.__get_tzname=k.asm.fa).apply(null,arguments)},$a=k.__get_daylight=function(){return($a=k.__get_daylight=k.asm.ga).apply(null,arguments)},Za=k.__get_timezone=function(){return(Za=k.__get_timezone=k.asm.ha).apply(null,arguments)},Mc=k._memalign=function(){return(Mc=k._memalign=k.asm.ia).apply(null,arguments)};k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.ka).apply(null,arguments)};k.dynCall_ji=function(){return(k.dynCall_ji=k.asm.la).apply(null,arguments)};
k.dynCall_viijii=function(){return(k.dynCall_viijii=k.asm.ma).apply(null,arguments)};k.dynCall_iiiiij=function(){return(k.dynCall_iiiiij=k.asm.na).apply(null,arguments)};k.dynCall_iiiiijj=function(){return(k.dynCall_iiiiijj=k.asm.oa).apply(null,arguments)};k.dynCall_iiiiiijj=function(){return(k.dynCall_iiiiiijj=k.asm.pa).apply(null,arguments)};var Ed;function oc(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Na=function Gd(){Ed||Hd();Ed||(Na=Gd)};
function Hd(){function a(){if(!Ed&&(Ed=!0,k.calledRun=!0,!oa)){k.noFSInit||od||(od=!0,nd(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?qd("stdin",k.stdin):jd("/dev/tty","/dev/stdin"),k.stdout?qd("stdout",null,k.stdout):jd("/dev/tty","/dev/stdout"),k.stderr?qd("stderr",null,k.stderr):jd("/dev/tty1","/dev/stderr"),kd("/dev/stdin",0),kd("/dev/stdout",1),kd("/dev/stderr",1));Sc=!1;Xa(Ia);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&
(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Ja.unshift(b)}Xa(Ja)}}if(!(0<La)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ka();Xa(Ha);0<La||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}k.run=Hd;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();Hd();


  return BlinkInputWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkInputWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkInputWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkInputWasmSDK"] = BlinkInputWasmSDK;
