
var BlinkInputWasmSDK = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(BlinkInputWasmSDK) {
  BlinkInputWasmSDK = BlinkInputWasmSDK || {};


var k;k||(k=typeof BlinkInputWasmSDK !== 'undefined' ? BlinkInputWasmSDK : {});var aa,ba;k.ready=new Promise(function(a,b){aa=a;ba=b});var crypto={getRandomValues:function(a){for(var b=0;b<a.length;b++)a[b]=256*Math.random()|0}},ca={},da;for(da in k)k.hasOwnProperty(da)&&(ca[da]=k[da]);var ea="./this.program";function fa(a,b){throw b;}var ha=!1,ja=!1;ha="object"===typeof window;ja="function"===typeof importScripts;var q="",ka;
if(ha||ja)ja?q=self.location.href:"undefined"!==typeof document&&document.currentScript&&(q=document.currentScript.src),_scriptDir&&(q=_scriptDir),q=0!==q.indexOf("blob:")?q.substr(0,q.lastIndexOf("/")+1):"",ja&&(ka=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});var la=k.print||console.log.bind(console),t=k.printErr||console.warn.bind(console);for(da in ca)ca.hasOwnProperty(da)&&(k[da]=ca[da]);ca=null;
k.thisProgram&&(ea=k.thisProgram);k.quit&&(fa=k.quit);var ma;k.wasmBinary&&(ma=k.wasmBinary);var noExitRuntime=k.noExitRuntime||!0;"object"!==typeof WebAssembly&&y("no native wasm support detected");var na,oa=!1,pa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function qa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&pa)return pa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function z(a,b){return a?qa(B,a,b):""}
function C(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.charCodeAt(f);if(55296<=g&&57343>=g){var l=a.charCodeAt(++f);g=65536+((g&1023)<<10)|l&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function ra(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var sa="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function ta(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&E[c];)++c;c<<=1;if(32<c-a&&sa)return sa.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=ua[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function va(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)ua[b>>1]=a.charCodeAt(e),b+=2;ua[b>>1]=0;return b-d}function wa(a){return 2*a.length}function xa(a,b){for(var c=0,d="";!(c>=b/4);){var e=F[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function ya(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var g=a.charCodeAt(++e);f=65536+((f&1023)<<10)|g&1023}F[b>>2]=f;b+=4;if(b+4>c)break}F[b>>2]=0;return b-d}function za(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Aa(a){var b=ra(a)+1,c=H(b);c&&C(a,K,c,b);return c}var Ba,K,B,ua,E,F,L,Ca,Da;
function Ea(){var a=na.buffer;Ba=a;k.HEAP8=K=new Int8Array(a);k.HEAP16=ua=new Int16Array(a);k.HEAP32=F=new Int32Array(a);k.HEAPU8=B=new Uint8Array(a);k.HEAPU16=E=new Uint16Array(a);k.HEAPU32=L=new Uint32Array(a);k.HEAPF32=Ca=new Float32Array(a);k.HEAPF64=Da=new Float64Array(a)}var N,Fa=[],Ga=[],Ha=[],Ia=[];Ga.push({Hb:function(){Ja()}});function Ka(){var a=k.preRun.shift();Fa.unshift(a)}var La=0,Ma=null,Na=null;function Oa(){La++;k.monitorRunDependencies&&k.monitorRunDependencies(La)}
function Pa(){La--;k.monitorRunDependencies&&k.monitorRunDependencies(La);if(0==La&&(null!==Ma&&(clearInterval(Ma),Ma=null),Na)){var a=Na;Na=null;a()}}k.preloadedImages={};k.preloadedAudios={};function y(a){if(k.onAbort)k.onAbort(a);a+="";t(a);oa=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function Qa(){var a=Ra;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ra="BlinkInputWasmSDK.wasm";if(!Qa()){var Sa=Ra;Ra=k.locateFile?k.locateFile(Sa,q):q+Sa}function Ta(){var a=Ra;try{if(a==Ra&&ma)return new Uint8Array(ma);if(ka)return ka(a);throw"both async and sync fetching of the wasm failed";}catch(b){y(b)}}
function Ua(){return ma||!ha&&!ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Ta()}):fetch(Ra,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ra+"'";return a.arrayBuffer()}).catch(function(){return Ta()})}
var Va,Wa,Xa={124805:function(a,b){a=z(a);b=z(b);throw Error(a+b);},124915:function(a,b,c,d){a=z(a);b=z(b);c=z(c);d=z(d);throw Error(a+b+c+d);},125131:function(a){a=z(a);throw Error("Failed to reconfigure RecognizerRunner due to following error: "+a);},125267:function(a,b){a=z(a);b=z(b);console.log(a+b)},125365:function(a){throw Error(z(a));},125408:function(){throw Error("Unable to perform that operation while recognizer is in use!");},125491:function(){throw Error("Unable to perform that operation while recognizer is in use!");
},125574:function(){throw Error("Unable to perform that operation while recognizer is in use!");}};function Ya(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(k);else{var c=b.Hb;"number"===typeof c?void 0===b.fb?N.get(c)():N.get(c)(b.fb):c(void 0===b.fb?null:b.fb)}}}
function Za(){function a(g){return(g=g.toTimeString().match(/\(([A-Za-z ]+)\)$/))?g[1]:"GMT"}if(!$a){$a=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),d=new Date(b,6,1);b=c.getTimezoneOffset();var e=d.getTimezoneOffset(),f=Math.max(b,e);F[ab()>>2]=60*f;F[bb()>>2]=Number(b!=e);c=a(c);d=a(d);c=Aa(c);d=Aa(d);e<b?(F[cb()>>2]=c,F[cb()+4>>2]=d):(F[cb()>>2]=d,F[cb()+4>>2]=c)}}var $a,db={};function eb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function fb(a){return this.fromWireType(L[a>>2])}
var gb={},hb={},ib={};function jb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function kb(a,b){a=jb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function lb(a){var b=Error,c=kb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var mb=void 0;function nb(a){throw new mb(a);}
function ob(a,b,c){function d(l){l=c(l);l.length!==a.length&&nb("Mismatched type converter count");for(var n=0;n<a.length;++n)O(a[n],l[n])}a.forEach(function(l){ib[l]=b});var e=Array(b.length),f=[],g=0;b.forEach(function(l,n){hb.hasOwnProperty(l)?e[n]=hb[l]:(f.push(l),gb.hasOwnProperty(l)||(gb[l]=[]),gb[l].push(function(){e[n]=hb[l];++g;g===f.length&&d(e)}))});0===f.length&&d(e)}
function pb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var qb=void 0;function P(a){for(var b="";B[a];)b+=qb[B[a++]];return b}var rb=void 0;function Q(a){throw new rb(a);}
function O(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||Q('type "'+d+'" must have a positive integer typeid pointer');if(hb.hasOwnProperty(a)){if(c.Nb)return;Q("Cannot register type '"+d+"' twice")}hb[a]=b;delete ib[a];gb.hasOwnProperty(a)&&(b=gb[a],delete gb[a],b.forEach(function(e){e()}))}function sb(a){return{count:a.count,Ka:a.Ka,Ra:a.Ra,sa:a.sa,ua:a.ua,ya:a.ya,Aa:a.Aa}}
function tb(a){Q(a.na.ua.ra.name+" instance already deleted")}var ub=!1;function vb(){}function wb(a){--a.count.value;0===a.count.value&&(a.ya?a.Aa.Ga(a.ya):a.ua.ra.Ga(a.sa))}
function xb(a){if("undefined"===typeof FinalizationGroup)return xb=function(b){return b},a;ub=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.sa?wb(c):console.warn("object already deleted: "+c.sa)});xb=function(b){ub.register(b,b.na,b.na);return b};vb=function(b){ub.unregister(b.na)};return xb(a)}var yb=void 0,zb=[];function Ab(){for(;zb.length;){var a=zb.pop();a.na.Ka=!1;a["delete"]()}}function Bb(){}var Cb={};
function Db(a,b,c){if(void 0===a[b].wa){var d=a[b];a[b]=function(){a[b].wa.hasOwnProperty(arguments.length)||Q("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].wa+")!");return a[b].wa[arguments.length].apply(this,arguments)};a[b].wa=[];a[b].wa[d.Va]=d}}
function Eb(a,b,c){k.hasOwnProperty(a)?((void 0===c||void 0!==k[a].wa&&void 0!==k[a].wa[c])&&Q("Cannot register public name '"+a+"' twice"),Db(k,a,a),k.hasOwnProperty(c)&&Q("Cannot register multiple overloads of a function with the same number of arguments ("+c+")!"),k[a].wa[c]=b):(k[a]=b,void 0!==c&&(k[a].pc=c))}function Fb(a,b,c,d,e,f,g,l){this.name=a;this.constructor=b;this.Na=c;this.Ga=d;this.Ba=e;this.Ib=f;this.Ua=g;this.Fb=l;this.Sb=[]}
function Gb(a,b,c){for(;b!==c;)b.Ua||Q("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ua(a),b=b.Ba;return a}function Hb(a,b){if(null===b)return this.hb&&Q("null is not a valid "+this.name),0;b.na||Q('Cannot pass "'+Ib(b)+'" as a '+this.name);b.na.sa||Q("Cannot pass deleted object as a pointer of type "+this.name);return Gb(b.na.sa,b.na.ua.ra,this.ra)}
function Jb(a,b){if(null===b){this.hb&&Q("null is not a valid "+this.name);if(this.Xa){var c=this.jb();null!==a&&a.push(this.Ga,c);return c}return 0}b.na||Q('Cannot pass "'+Ib(b)+'" as a '+this.name);b.na.sa||Q("Cannot pass deleted object as a pointer of type "+this.name);!this.Wa&&b.na.ua.Wa&&Q("Cannot convert argument of type "+(b.na.Aa?b.na.Aa.name:b.na.ua.name)+" to parameter type "+this.name);c=Gb(b.na.sa,b.na.ua.ra,this.ra);if(this.Xa)switch(void 0===b.na.ya&&Q("Passing raw pointer to smart pointer is illegal"),
this.Zb){case 0:b.na.Aa===this?c=b.na.ya:Q("Cannot convert argument of type "+(b.na.Aa?b.na.Aa.name:b.na.ua.name)+" to parameter type "+this.name);break;case 1:c=b.na.ya;break;case 2:if(b.na.Aa===this)c=b.na.ya;else{var d=b.clone();c=this.Tb(c,R(function(){d["delete"]()}));null!==a&&a.push(this.Ga,c)}break;default:Q("Unsupporting sharing policy")}return c}
function Kb(a,b){if(null===b)return this.hb&&Q("null is not a valid "+this.name),0;b.na||Q('Cannot pass "'+Ib(b)+'" as a '+this.name);b.na.sa||Q("Cannot pass deleted object as a pointer of type "+this.name);b.na.ua.Wa&&Q("Cannot convert argument of type "+b.na.ua.name+" to parameter type "+this.name);return Gb(b.na.sa,b.na.ua.ra,this.ra)}function Lb(a,b,c){if(b===c)return a;if(void 0===c.Ba)return null;a=Lb(a,b,c.Ba);return null===a?null:c.Fb(a)}var Mb={};
function Nb(a,b){for(void 0===b&&Q("ptr should not be undefined");a.Ba;)b=a.Ua(b),a=a.Ba;return Mb[b]}function Ob(a,b){b.ua&&b.sa||nb("makeClassHandle requires ptr and ptrType");!!b.Aa!==!!b.ya&&nb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return xb(Object.create(a,{na:{value:b}}))}
function S(a,b,c,d){this.name=a;this.ra=b;this.hb=c;this.Wa=d;this.Xa=!1;this.Ga=this.Tb=this.jb=this.yb=this.Zb=this.Rb=void 0;void 0!==b.Ba?this.toWireType=Jb:(this.toWireType=d?Hb:Kb,this.Ca=null)}function Pb(a,b,c){k.hasOwnProperty(a)||nb("Replacing nonexistant public symbol");void 0!==k[a].wa&&void 0!==c?k[a].wa[c]=b:(k[a]=b,k[a].Va=c)}
function Qb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];-1!=a.indexOf("j")?(d=k["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=N.get(b).apply(null,c);return d}}function T(a,b){a=P(a);var c=-1!=a.indexOf("j")?Qb(a,b):N.get(b);"function"!==typeof c&&Q("unknown function pointer with signature "+a+": "+b);return c}var Rb=void 0;function Sb(a){a=Tb(a);var b=P(a);U(a);return b}
function Ub(a,b){function c(f){e[f]||hb[f]||(ib[f]?ib[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Rb(a+": "+d.map(Sb).join([", "]));}function Vb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[(b>>2)+d]);return c}
function Wb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=kb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Xb(a,b,c,d,e){var f=b.length;2>f&&Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Ca){l=!0;break}var n="void"!==b[0].name,m="",p="";for(c=0;c<f-2;++c)m+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+jb(a)+"("+m+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";l&&(a+="var destructors = [];\n");var v=l?"destructors":"null";m="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[Q,d,e,eb,b[0],b[1]];g&&(a+="var thisWired = classParam.toWireType("+v+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+v+", arg"+c+"); // "+b[c+2].name+"\n",m.push("argType"+c),d.push(b[c+2]);g&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(n?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(l)a+=
"runDestructors(destructors);\n";else for(c=g?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].Ca&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",m.push(f+"_dtor"),d.push(b[c].Ca));n&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");m.push(a+"}\n");return Wb(m).apply(null,d)}var Yb=[],V=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Zb(a){4<a&&0===--V[a].lb&&(V[a]=void 0,Yb.push(a))}
function R(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Yb.length?Yb.pop():V.length;V[b]={lb:1,value:a};return b}}function Ib(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function $b(a,b){switch(b){case 2:return function(c){return this.fromWireType(Ca[c>>2])};case 3:return function(c){return this.fromWireType(Da[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function ac(a,b,c){switch(b){case 0:return c?function(d){return K[d]}:function(d){return B[d]};case 1:return c?function(d){return ua[d>>1]}:function(d){return E[d>>1]};case 2:return c?function(d){return F[d>>2]}:function(d){return L[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function bc(a){a||Q("Cannot use deleted val. handle = "+a);return V[a].value}function cc(a,b){var c=hb[a];void 0===c&&Q(b+" has unknown type "+Sb(a));return c}var dc={};
function ec(a){var b=dc[a];return void 0===b?P(a):b}var fc=[];function gc(){return"object"===typeof globalThis?globalThis:Function("return this")()}function hc(a){var b=fc.length;fc.push(a);return b}function ic(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=cc(F[(b>>2)+d],"parameter "+d);return c}var jc={},kc;kc=function(){return performance.now()};function lc(){return!ja}k._emscripten_is_main_browser_thread=lc;var mc=[];function W(a,b){L[a>>2]=b;L[a+4>>2]=b/4294967296|0}var nc;
function oc(a,b,c,d,e){function f(A){var M=0,J=0;A&&(J=u.response?u.response.byteLength:0,M=H(J),B.set(new Uint8Array(u.response),M));L[a+12>>2]=M;W(a+16,J)}var g=L[a+8>>2];if(g){var l=z(g),n=a+112,m=z(n);m||(m="GET");var p=L[n+52>>2],v=L[n+56>>2],w=!!L[n+60>>2],h=L[n+68>>2],r=L[n+72>>2];g=L[n+76>>2];var x=L[n+80>>2],D=L[n+84>>2];n=L[n+88>>2];var I=!!(p&1),G=!!(p&2);p=!!(p&64);h=h?z(h):void 0;r=r?z(r):void 0;var ia=x?z(x):void 0,u=new XMLHttpRequest;u.withCredentials=w;u.open(m,l,!p,h,r);p||(u.timeout=
v);u.sc=l;u.responseType="arraybuffer";x&&u.overrideMimeType(ia);if(g)for(;;){m=L[g>>2];if(!m)break;l=L[g+4>>2];if(!l)break;g+=8;m=z(m);l=z(l);u.setRequestHeader(m,l)}mc.push(u);L[a+0>>2]=mc.length;g=D&&n?B.slice(D,D+n):null;u.onload=function(A){f(I&&!G);var M=u.response?u.response.byteLength:0;W(a+24,0);M&&W(a+32,M);E[a+40>>1]=u.readyState;E[a+42>>1]=u.status;u.statusText&&C(u.statusText,B,a+44,64);200<=u.status&&300>u.status?b&&b(a,u,A):c&&c(a,u,A)};u.onerror=function(A){f(I);var M=u.status;W(a+
24,0);W(a+32,u.response?u.response.byteLength:0);E[a+40>>1]=u.readyState;E[a+42>>1]=M;c&&c(a,u,A)};u.ontimeout=function(A){c&&c(a,u,A)};u.onprogress=function(A){var M=I&&G&&u.response?u.response.byteLength:0,J=0;I&&G&&(J=H(M),B.set(new Uint8Array(u.response),J));L[a+12>>2]=J;W(a+16,M);W(a+24,A.loaded-M);W(a+32,A.total);E[a+40>>1]=u.readyState;3<=u.readyState&&0===u.status&&0<A.loaded&&(u.status=200);E[a+42>>1]=u.status;u.statusText&&C(u.statusText,B,a+44,64);d&&d(a,u,A);J&&U(J)};u.onreadystatechange=
function(A){E[a+40>>1]=u.readyState;2<=u.readyState&&(E[a+42>>1]=u.status);e&&e(a,u,A)};try{u.send(g)}catch(A){c&&c(a,u,A)}}else c(a,0,"no url specified!")}
function pc(a,b,c,d){var e=nc;if(e){var f=L[a+112+64>>2];f||(f=L[a+8>>2]);var g=z(f);try{var l=e.transaction(["FILES"],"readwrite").objectStore("FILES").put(b,g);l.onsuccess=function(){E[a+40>>1]=4;E[a+42>>1]=200;C("OK",B,a+44,64);c(a,0,g)};l.onerror=function(n){E[a+40>>1]=4;E[a+42>>1]=413;C("Payload Too Large",B,a+44,64);d(a,0,n)}}catch(n){d(a,0,n)}}else d(a,0,"IndexedDB not available!")}
function qc(a,b,c){var d=nc;if(d){var e=L[a+112+64>>2];e||(e=L[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readonly").objectStore("FILES").get(e);f.onsuccess=function(g){if(g.target.result){g=g.target.result;var l=g.byteLength||g.length,n=H(l);B.set(new Uint8Array(g),n);L[a+12>>2]=n;W(a+16,l);W(a+24,0);W(a+32,l);E[a+40>>1]=4;E[a+42>>1]=200;C("OK",B,a+44,64);b(a,0,g)}else E[a+40>>1]=4,E[a+42>>1]=404,C("Not Found",B,a+44,64),c(a,0,"no data")};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;
C("Not Found",B,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}
function rc(a,b,c){var d=nc;if(d){var e=L[a+112+64>>2];e||(e=L[a+8>>2]);e=z(e);try{var f=d.transaction(["FILES"],"readwrite").objectStore("FILES").delete(e);f.onsuccess=function(g){g=g.target.result;L[a+12>>2]=0;W(a+16,0);W(a+24,0);W(a+32,0);E[a+40>>1]=4;E[a+42>>1]=200;C("OK",B,a+44,64);b(a,0,g)};f.onerror=function(g){E[a+40>>1]=4;E[a+42>>1]=404;C("Not Found",B,a+44,64);c(a,0,g)}}catch(g){c(a,0,g)}}else c(a,0,"IndexedDB not available!")}var sc={};
function tc(){if(!uc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in sc)a[b]=sc[b];var c=[];for(b in a)c.push(b+"="+a[b]);uc=c}return uc}var uc;
function vc(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function wc(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=vc(a.split("/").filter(function(d){return!!d}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function xc(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function yc(a){if("/"===a)return"/";a=wc(a);a=a.replace(/\/$/,"");var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function zc(){if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);return function(){crypto.getRandomValues(a);return a[0]}}return function(){y("randomDevice")}}
function Ac(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=vc(a.split("/").filter(function(d){return!!d}),!b).join("/");return(b?"/":"")+a||"."}var Bc=[];function Cc(a,b){Bc[a]={input:[],va:[],Oa:b};Dc(a,Ec)}
var Ec={open:function(a){var b=Bc[a.node.$a];if(!b)throw new X(43);a.za=b;a.seekable=!1},close:function(a){a.za.Oa.flush(a.za)},flush:function(a){a.za.Oa.flush(a.za)},read:function(a,b,c,d){if(!a.za||!a.za.Oa.tb)throw new X(60);for(var e=0,f=0;f<d;f++){try{var g=a.za.Oa.tb(a.za)}catch(l){throw new X(29);}if(void 0===g&&0===e)throw new X(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.za||!a.za.Oa.ib)throw new X(60);try{for(var e=
0;e<d;e++)a.za.Oa.ib(a.za,b[c+e])}catch(f){throw new X(29);}d&&(a.node.timestamp=Date.now());return e}},Gc={tb:function(a){if(!a.input.length){var b=null;"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=Fc(b,!0)}return a.input.shift()},ib:function(a,b){null===b||10===b?(la(qa(a.va,0)),a.va=[]):0!=b&&a.va.push(b)},flush:function(a){a.va&&0<a.va.length&&
(la(qa(a.va,0)),a.va=[])}},Hc={ib:function(a,b){null===b||10===b?(t(qa(a.va,0)),a.va=[]):0!=b&&a.va.push(b)},flush:function(a){a.va&&0<a.va.length&&(t(qa(a.va,0)),a.va=[])}},Y={Da:null,Fa:function(){return Y.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new X(63);Y.Da||(Y.Da={dir:{node:{Ha:Y.pa.Ha,Ea:Y.pa.Ea,Qa:Y.pa.Qa,Ya:Y.pa.Ya,Ab:Y.pa.Ab,Cb:Y.pa.Cb,Bb:Y.pa.Bb,zb:Y.pa.zb,ab:Y.pa.ab},stream:{Ja:Y.qa.Ja}},file:{node:{Ha:Y.pa.Ha,Ea:Y.pa.Ea},
stream:{Ja:Y.qa.Ja,read:Y.qa.read,write:Y.qa.write,mb:Y.qa.mb,ub:Y.qa.ub,wb:Y.qa.wb}},link:{node:{Ha:Y.pa.Ha,Ea:Y.pa.Ea,Sa:Y.pa.Sa},stream:{}},nb:{node:{Ha:Y.pa.Ha,Ea:Y.pa.Ea},stream:Ic}});c=Jc(a,b,c,d);16384===(c.mode&61440)?(c.pa=Y.Da.dir.node,c.qa=Y.Da.dir.stream,c.oa={}):32768===(c.mode&61440)?(c.pa=Y.Da.file.node,c.qa=Y.Da.file.stream,c.ta=0,c.oa=null):40960===(c.mode&61440)?(c.pa=Y.Da.link.node,c.qa=Y.Da.link.stream):8192===(c.mode&61440)&&(c.pa=Y.Da.nb.node,c.qa=Y.Da.nb.stream);c.timestamp=
Date.now();a&&(a.oa[b]=c,a.timestamp=c.timestamp);return c},kc:function(a){return a.oa?a.oa.subarray?a.oa.subarray(0,a.ta):new Uint8Array(a.oa):new Uint8Array(0)},pb:function(a,b){var c=a.oa?a.oa.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)>>>0),0!=c&&(b=Math.max(b,256)),c=a.oa,a.oa=new Uint8Array(b),0<a.ta&&a.oa.set(c.subarray(0,a.ta),0))},Ub:function(a,b){if(a.ta!=b)if(0==b)a.oa=null,a.ta=0;else{var c=a.oa;a.oa=new Uint8Array(b);c&&a.oa.set(c.subarray(0,Math.min(b,a.ta)));a.ta=b}},pa:{Ha:function(a){var b=
{};b.jc=8192===(a.mode&61440)?a.id:1;b.mc=a.id;b.mode=a.mode;b.oc=1;b.uid=0;b.lc=0;b.$a=a.$a;b.size=16384===(a.mode&61440)?4096:32768===(a.mode&61440)?a.ta:40960===(a.mode&61440)?a.link.length:0;b.fc=new Date(a.timestamp);b.nc=new Date(a.timestamp);b.ic=new Date(a.timestamp);b.Db=4096;b.hc=Math.ceil(b.size/b.Db);return b},Ea:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&Y.Ub(a,b.size)},Qa:function(){throw Kc[44];},Ya:function(a,b,c,
d){return Y.createNode(a,b,c,d)},Ab:function(a,b,c){if(16384===(a.mode&61440)){try{var d=Lc(b,c)}catch(f){}if(d)for(var e in d.oa)throw new X(55);}delete a.parent.oa[a.name];a.parent.timestamp=Date.now();a.name=c;b.oa[c]=a;b.timestamp=a.parent.timestamp;a.parent=b},Cb:function(a,b){delete a.oa[b];a.timestamp=Date.now()},Bb:function(a,b){var c=Lc(a,b),d;for(d in c.oa)throw new X(55);delete a.oa[b];a.timestamp=Date.now()},zb:function(a){var b=[".",".."],c;for(c in a.oa)a.oa.hasOwnProperty(c)&&b.push(c);
return b},ab:function(a,b,c){a=Y.createNode(a,b,41471,0);a.link=c;return a},Sa:function(a){if(40960!==(a.mode&61440))throw new X(28);return a.link}},qa:{read:function(a,b,c,d,e){var f=a.node.oa;if(e>=a.node.ta)return 0;a=Math.min(a.node.ta-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===K.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.oa||a.oa.subarray)){if(f)return a.oa=b.subarray(c,
c+d),a.ta=d;if(0===a.ta&&0===e)return a.oa=b.slice(c,c+d),a.ta=d;if(e+d<=a.ta)return a.oa.set(b.subarray(c,c+d),e),d}Y.pb(a,e+d);if(a.oa.subarray&&b.subarray)a.oa.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.oa[e+f]=b[c+f];a.ta=Math.max(a.ta,e+d);return d},Ja:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ta);if(0>b)throw new X(28);return b},mb:function(a,b,c){Y.pb(a.node,b+c);a.node.ta=Math.max(a.node.ta,b+c)},ub:function(a,b,c,d,e,f){if(0!==b)throw new X(28);
if(32768!==(a.node.mode&61440))throw new X(43);a=a.node.oa;if(f&2||a.buffer!==Ba){if(0<d||d+c<a.length)a=a.subarray?a.subarray(d,d+c):Array.prototype.slice.call(a,d,d+c);d=!0;f=16384*Math.ceil(c/16384);for(b=H(f);c<f;)K[b+c++]=0;c=b;if(!c)throw new X(48);K.set(a,c)}else d=!1,c=a.byteOffset;return{sa:c,ec:d}},wb:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new X(43);if(e&2)return 0;Y.qa.write(a,b,0,d,c,!1);return 0}}},Mc=null,Nc={},Oc=[],Pc=1,Qc=null,Rc=!0,Sc={},X=null,Kc={};
function Tc(a,b){a=Ac("/",a);b=b||{};if(!a)return{path:"",node:null};var c={sb:!0,kb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.kb)throw new X(32);a=vc(a.split("/").filter(function(g){return!!g}),!1);var e=Mc;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=Lc(e,a[d]);c=wc(c+"/"+a[d]);e.Za&&(!f||f&&b.sb)&&(e=e.Za.root);if(!f||b.rb)for(f=0;40960===(e.mode&61440);)if(e=Uc(c),c=Ac(xc(c),e),e=Tc(c,{kb:b.kb}).node,40<f++)throw new X(32);}return{path:c,node:e}}
function Vc(a){for(var b;;){if(a===a.parent)return a=a.Fa.vb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Wc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Qc.length}function Lc(a,b){var c;if(c=(c=Xc(a,"x"))?c:a.pa.Qa?0:2)throw new X(c,a);for(c=Qc[Wc(a.id,b)];c;c=c.Qb){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.pa.Qa(a,b)}
function Jc(a,b,c,d){a=new Yc(a,b,c,d);b=Wc(a.parent.id,a.name);a.Qb=Qc[b];return Qc[b]=a}var Zc={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090};function $c(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Xc(a,b){if(Rc)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}function ad(a,b){try{return Lc(a,b),20}catch(c){}return Xc(a,"wx")}
function bd(){var a=4096;for(var b=0;b<=a;b++)if(!Oc[b])return b;throw new X(33);}function cd(a){dd||(dd=function(){},dd.prototype={object:{get:function(){return this.node},set:function(d){this.node=d}}});var b=new dd,c;for(c in a)b[c]=a[c];a=b;b=bd();a.Ma=b;return Oc[b]=a}var Ic={open:function(a){a.qa=Nc[a.node.$a].qa;a.qa.open&&a.qa.open(a)},Ja:function(){throw new X(70);}};function Dc(a,b){Nc[a]={qa:b}}
function ed(a,b){var c="/"===b,d=!b;if(c&&Mc)throw new X(10);if(!c&&!d){var e=Tc(b,{sb:!1});b=e.path;e=e.node;if(e.Za)throw new X(10);if(16384!==(e.mode&61440))throw new X(54);}b={type:a,qc:{},vb:b,Pb:[]};a=a.Fa(b);a.Fa=b;b.root=a;c?Mc=a:e&&(e.Za=b,e.Fa&&e.Fa.Pb.push(b))}function fd(a,b,c){var d=Tc(a,{parent:!0}).node;a=yc(a);if(!a||"."===a||".."===a)throw new X(28);var e=ad(d,a);if(e)throw new X(e);if(!d.pa.Ya)throw new X(63);return d.pa.Ya(d,a,b,c)}function Z(a){return fd(a,16895,0)}
function gd(a,b,c){"undefined"===typeof c&&(c=b,b=438);fd(a,b|8192,c)}function hd(a,b){if(!Ac(a))throw new X(44);var c=Tc(b,{parent:!0}).node;if(!c)throw new X(44);b=yc(b);var d=ad(c,b);if(d)throw new X(d);if(!c.pa.ab)throw new X(63);c.pa.ab(c,b,a)}function Uc(a){a=Tc(a).node;if(!a)throw new X(44);if(!a.pa.Sa)throw new X(28);return Ac(Vc(a.parent),a.pa.Sa(a))}
function id(a,b){if(""===a)throw new X(44);if("string"===typeof b){var c=Zc[b];if("undefined"===typeof c)throw Error("Unknown file open mode: "+b);b=c}var d=b&64?("undefined"===typeof d?438:d)&4095|32768:0;if("object"===typeof a)var e=a;else{a=wc(a);try{e=Tc(a,{rb:!(b&131072)}).node}catch(f){}}c=!1;if(b&64)if(e){if(b&128)throw new X(20);}else e=fd(a,d,0),c=!0;if(!e)throw new X(44);8192===(e.mode&61440)&&(b&=-513);if(b&65536&&16384!==(e.mode&61440))throw new X(54);if(!c&&(d=e?40960===(e.mode&61440)?
32:16384===(e.mode&61440)&&("r"!==$c(b)||b&512)?31:Xc(e,$c(b)):44))throw new X(d);if(b&512){d=e;d="string"===typeof d?Tc(d,{rb:!0}).node:d;if(!d.pa.Ea)throw new X(63);if(16384===(d.mode&61440))throw new X(31);if(32768!==(d.mode&61440))throw new X(28);if(c=Xc(d,"w"))throw new X(c);d.pa.Ea(d,{size:0,timestamp:Date.now()})}b&=-131713;e=cd({node:e,path:Vc(e),flags:b,seekable:!0,position:0,qa:e.qa,dc:[],error:!1});e.qa.open&&e.qa.open(e);!k.logReadFiles||b&1||(jd||(jd={}),a in jd||(jd[a]=1,t("FS.trackingDelegate error on read file: "+
a)));try{Sc.onOpenFile&&(e=0,1!==(b&2097155)&&(e|=1),0!==(b&2097155)&&(e|=2),Sc.onOpenFile(a,e))}catch(f){t("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+f.message)}}function kd(a,b,c){if(null===a.Ma)throw new X(8);if(!a.seekable||!a.qa.Ja)throw new X(70);if(0!=c&&1!=c&&2!=c)throw new X(28);a.position=a.qa.Ja(a,b,c);a.dc=[]}
function ld(){X||(X=function(a,b){this.node=b;this.Vb=function(c){this.La=c};this.Vb(a);this.message="FS error"},X.prototype=Error(),X.prototype.constructor=X,[44].forEach(function(a){Kc[a]=new X(a);Kc[a].stack="<generic error, no stack>"}))}var md;function nd(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}
function od(a,b,c){a=wc("/dev/"+a);var d=nd(!!b,!!c);pd||(pd=64);var e=pd++<<8|0;Dc(e,{open:function(f){f.seekable=!1},close:function(){c&&c.buffer&&c.buffer.length&&c(10)},read:function(f,g,l,n){for(var m=0,p=0;p<n;p++){try{var v=b()}catch(w){throw new X(29);}if(void 0===v&&0===m)throw new X(6);if(null===v||void 0===v)break;m++;g[l+p]=v}m&&(f.node.timestamp=Date.now());return m},write:function(f,g,l,n){for(var m=0;m<n;m++)try{c(g[l+m])}catch(p){throw new X(29);}n&&(f.node.timestamp=Date.now());return m}});
gd(a,d,e)}var pd,qd={},dd,jd;function rd(a){a=Oc[a];if(!a)throw new X(8);return a}function sd(a,b){sd.xb||(sd.xb=zc());for(var c=0;c<b;c++)K[a+c>>0]=sd.xb();return 0}function td(a){return 0===a%4&&(0!==a%100||0===a%400)}function ud(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var vd=[31,29,31,30,31,30,31,31,30,31,30,31],wd=[31,28,31,30,31,30,31,31,30,31,30,31];
function xd(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(td(a.getFullYear())?vd:wd)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function yd(a,b,c,d){function e(h,r,x){for(h="number"===typeof h?h.toString():h||"";h.length<r;)h=x[0]+h;return h}function f(h,r){return e(h,r,"0")}function g(h,r){function x(I){return 0>I?-1:0<I?1:0}var D;0===(D=x(h.getFullYear()-r.getFullYear()))&&0===(D=x(h.getMonth()-r.getMonth()))&&(D=x(h.getDate()-r.getDate()));return D}function l(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function n(h){h=xd(new Date(h.xa+1900,0,1),h.eb);var r=new Date(h.getFullYear()+1,0,4),x=l(new Date(h.getFullYear(),0,4));r=l(r);return 0>=g(x,h)?0>=g(r,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var m=F[d+40>>2];d={bc:F[d>>2],ac:F[d+4>>2],bb:F[d+8>>2],Ta:F[d+12>>2],Pa:F[d+16>>2],xa:F[d+20>>2],cb:F[d+24>>2],eb:F[d+28>>2],rc:F[d+32>>2],$b:F[d+
36>>2],cc:m?z(m):""};c=z(c);m={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in m)c=c.replace(new RegExp(p,"g"),m[p]);var v="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
w="January February March April May June July August September October November December".split(" ");m={"%a":function(h){return v[h.cb].substring(0,3)},"%A":function(h){return v[h.cb]},"%b":function(h){return w[h.Pa].substring(0,3)},"%B":function(h){return w[h.Pa]},"%C":function(h){return f((h.xa+1900)/100|0,2)},"%d":function(h){return f(h.Ta,2)},"%e":function(h){return e(h.Ta,2," ")},"%g":function(h){return n(h).toString().substring(2)},"%G":function(h){return n(h)},"%H":function(h){return f(h.bb,
2)},"%I":function(h){h=h.bb;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.Ta+ud(td(h.xa+1900)?vd:wd,h.Pa-1),3)},"%m":function(h){return f(h.Pa+1,2)},"%M":function(h){return f(h.ac,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.bb&&12>h.bb?"AM":"PM"},"%S":function(h){return f(h.bc,2)},"%t":function(){return"\t"},"%u":function(h){return h.cb||7},"%U":function(h){var r=new Date(h.xa+1900,0,1),x=0===r.getDay()?r:xd(r,7-r.getDay());h=new Date(h.xa+1900,h.Pa,h.Ta);return 0>
g(x,h)?f(Math.ceil((31-x.getDate()+(ud(td(h.getFullYear())?vd:wd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(x,r)?"01":"00"},"%V":function(h){var r=new Date(h.xa+1901,0,4),x=l(new Date(h.xa+1900,0,4));r=l(r);var D=xd(new Date(h.xa+1900,0,1),h.eb);return 0>g(D,x)?"53":0>=g(r,D)?"01":f(Math.ceil((x.getFullYear()<h.xa+1900?h.eb+32-x.getDate():h.eb+1-x.getDate())/7),2)},"%w":function(h){return h.cb},"%W":function(h){var r=new Date(h.xa,0,1),x=1===r.getDay()?r:xd(r,0===r.getDay()?1:7-r.getDay()+1);h=
new Date(h.xa+1900,h.Pa,h.Ta);return 0>g(x,h)?f(Math.ceil((31-x.getDate()+(ud(td(h.getFullYear())?vd:wd,h.getMonth()-1)-31)+h.getDate())/7),2):0===g(x,r)?"01":"00"},"%y":function(h){return(h.xa+1900).toString().substring(2)},"%Y":function(h){return h.xa+1900},"%z":function(h){h=h.$b;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.cc},"%%":function(){return"%"}};for(p in m)0<=c.indexOf(p)&&(c=c.replace(new RegExp(p,"g"),m[p](d)));p=
Fc(c,!1);if(p.length>b)return 0;K.set(p,a);return p.length-1}var zd=[];mb=k.InternalError=lb("InternalError");for(var Ad=Array(256),Bd=0;256>Bd;++Bd)Ad[Bd]=String.fromCharCode(Bd);qb=Ad;rb=k.BindingError=lb("BindingError");Bb.prototype.isAliasOf=function(a){if(!(this instanceof Bb&&a instanceof Bb))return!1;var b=this.na.ua.ra,c=this.na.sa,d=a.na.ua.ra;for(a=a.na.sa;b.Ba;)c=b.Ua(c),b=b.Ba;for(;d.Ba;)a=d.Ua(a),d=d.Ba;return b===d&&c===a};
Bb.prototype.clone=function(){this.na.sa||tb(this);if(this.na.Ra)return this.na.count.value+=1,this;var a=xb(Object.create(Object.getPrototypeOf(this),{na:{value:sb(this.na)}}));a.na.count.value+=1;a.na.Ka=!1;return a};Bb.prototype["delete"]=function(){this.na.sa||tb(this);this.na.Ka&&!this.na.Ra&&Q("Object already scheduled for deletion");vb(this);wb(this.na);this.na.Ra||(this.na.ya=void 0,this.na.sa=void 0)};Bb.prototype.isDeleted=function(){return!this.na.sa};
Bb.prototype.deleteLater=function(){this.na.sa||tb(this);this.na.Ka&&!this.na.Ra&&Q("Object already scheduled for deletion");zb.push(this);1===zb.length&&yb&&yb(Ab);this.na.Ka=!0;return this};S.prototype.Jb=function(a){this.yb&&(a=this.yb(a));return a};S.prototype.ob=function(a){this.Ga&&this.Ga(a)};S.prototype.argPackAdvance=8;S.prototype.readValueFromPointer=fb;S.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
S.prototype.fromWireType=function(a){function b(){return this.Xa?Ob(this.ra.Na,{ua:this.Rb,sa:c,Aa:this,ya:a}):Ob(this.ra.Na,{ua:this,sa:a})}var c=this.Jb(a);if(!c)return this.ob(a),null;var d=Nb(this.ra,c);if(void 0!==d){if(0===d.na.count.value)return d.na.sa=c,d.na.ya=a,d.clone();d=d.clone();this.ob(a);return d}d=this.ra.Ib(c);d=Cb[d];if(!d)return b.call(this);d=this.Wa?d.Eb:d.pointerType;var e=Lb(c,this.ra,d.ra);return null===e?b.call(this):this.Xa?Ob(d.ra.Na,{ua:d,sa:e,Aa:this,ya:a}):Ob(d.ra.Na,
{ua:d,sa:e})};k.getInheritedInstanceCount=function(){return Object.keys(Mb).length};k.getLiveInheritedInstances=function(){var a=[],b;for(b in Mb)Mb.hasOwnProperty(b)&&a.push(Mb[b]);return a};k.flushPendingDeletes=Ab;k.setDelayFunction=function(a){yb=a;zb.length&&yb&&yb(Ab)};Rb=k.UnboundTypeError=lb("UnboundTypeError");k.count_emval_handles=function(){for(var a=0,b=5;b<V.length;++b)void 0!==V[b]&&++a;return a};k.get_first_emval=function(){for(var a=5;a<V.length;++a)if(void 0!==V[a])return V[a];return null};
(function(a,b){try{var c=indexedDB.open("emscripten_filesystem",1)}catch(d){b(d);return}c.onupgradeneeded=function(d){d=d.target.result;d.objectStoreNames.contains("FILES")&&d.deleteObjectStore("FILES");d.createObjectStore("FILES")};c.onsuccess=function(d){a(d.target.result)};c.onerror=function(d){b(d)}})(function(a){nc=a;Pa()},function(){nc=!1;Pa()});"undefined"!==typeof ENVIRONMENT_IS_FETCH_WORKER&&ENVIRONMENT_IS_FETCH_WORKER||Oa();
function Yc(a,b,c,d){a||(a=this);this.parent=a;this.Fa=a.Fa;this.Za=null;this.id=Pc++;this.name=b;this.mode=c;this.pa={};this.qa={};this.$a=d}Object.defineProperties(Yc.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}}});ld();Qc=Array(4096);ed(Y,"/");Z("/tmp");Z("/home");Z("/home/web_user");
(function(){Z("/dev");Dc(259,{read:function(){return 0},write:function(b,c,d,e){return e}});gd("/dev/null",259);Cc(1280,Gc);Cc(1536,Hc);gd("/dev/tty",1280);gd("/dev/tty1",1536);var a=zc();od("random",a);od("urandom",a);Z("/dev/shm");Z("/dev/shm/tmp")})();
(function(){Z("/proc");var a=Z("/proc/self");Z("/proc/self/fd");ed({Fa:function(){var b=Jc(a,"fd",16895,73);b.pa={Qa:function(c,d){var e=Oc[+d];if(!e)throw new X(8);c={parent:null,Fa:{vb:"fake"},pa:{Sa:function(){return e.path}}};return c.parent=c}};return b}},"/proc/self/fd")})();function Fc(a,b){var c=Array(ra(a)+1);a=C(a,c,0,c.length);b&&(c.length=a);return c}
var Dd={I:function(a,b){Za();a=new Date(1E3*F[a>>2]);F[b>>2]=a.getSeconds();F[b+4>>2]=a.getMinutes();F[b+8>>2]=a.getHours();F[b+12>>2]=a.getDate();F[b+16>>2]=a.getMonth();F[b+20>>2]=a.getFullYear()-1900;F[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);F[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;F[b+36>>2]=-(60*a.getTimezoneOffset());var d=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(d!=c&&a.getTimezoneOffset()==Math.min(c,d))|0;F[b+32>>2]=a;a=F[cb()+(a?
4:0)>>2];F[b+40>>2]=a;return b},b:function(a){var b=db[a];delete db[a];var c=b.jb,d=b.Ga,e=b.qb,f=e.map(function(g){return g.Mb}).concat(e.map(function(g){return g.Xb}));ob([a],f,function(g){var l={};e.forEach(function(n,m){var p=g[m],v=n.Kb,w=n.Lb,h=g[m+e.length],r=n.Wb,x=n.Yb;l[n.Gb]={read:function(D){return p.fromWireType(v(w,D))},write:function(D,I){var G=[];r(x,D,h.toWireType(G,I));eb(G)}}});return[{name:b.name,fromWireType:function(n){var m={},p;for(p in l)m[p]=l[p].read(n);d(n);return m},toWireType:function(n,
m){for(var p in l)if(!(p in m))throw new TypeError('Missing field:  "'+p+'"');var v=c();for(p in l)l[p].write(v,m[p]);null!==n&&n.push(d,v);return v},argPackAdvance:8,readValueFromPointer:fb,Ca:d}]})},P:function(a,b,c,d,e){var f=pb(c);b=P(b);O(a,{name:b,fromWireType:function(g){return!!g},toWireType:function(g,l){return l?d:e},argPackAdvance:8,readValueFromPointer:function(g){if(1===c)var l=K;else if(2===c)l=ua;else if(4===c)l=F;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(l[g>>
f])},Ca:null})},k:function(a,b,c,d,e,f,g,l,n,m,p,v,w){p=P(p);f=T(e,f);l&&(l=T(g,l));m&&(m=T(n,m));w=T(v,w);var h=jb(p);Eb(h,function(){Ub("Cannot construct "+p+" due to unbound types",[d])});ob([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var x=r.ra;var D=x.Na}else D=Bb.prototype;r=kb(h,function(){if(Object.getPrototypeOf(this)!==I)throw new rb("Use 'new' to construct "+p);if(void 0===G.Ia)throw new rb(p+" has no accessible constructor");var u=G.Ia[arguments.length];if(void 0===u)throw new rb("Tried to invoke ctor of "+
p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(G.Ia).toString()+") parameters instead!");return u.apply(this,arguments)});var I=Object.create(D,{constructor:{value:r}});r.prototype=I;var G=new Fb(p,r,I,w,x,f,l,m);x=new S(p,G,!0,!1);D=new S(p+"*",G,!1,!1);var ia=new S(p+" const*",G,!1,!0);Cb[a]={pointerType:D,Eb:ia};Pb(h,r);return[x,D,ia]})},l:function(a,b,c,d,e,f){0<b||y("Assertion failed: undefined");var g=Vb(b,c);e=T(d,e);var l=[f],n=[];ob([],[a],function(m){m=
m[0];var p="constructor "+m.name;void 0===m.ra.Ia&&(m.ra.Ia=[]);if(void 0!==m.ra.Ia[b-1])throw new rb("Cannot register multiple constructors with identical number of parameters ("+(b-1)+") for class '"+m.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");m.ra.Ia[b-1]=function(){Ub("Cannot construct "+m.name+" due to unbound types",g)};ob([],g,function(v){m.ra.Ia[b-1]=function(){arguments.length!==b-1&&Q(p+" called with "+arguments.length+" arguments, expected "+
(b-1));n.length=0;l.length=b;for(var w=1;w<b;++w)l[w]=v[w].toWireType(n,arguments[w-1]);w=e.apply(null,l);eb(n);return v[0].fromWireType(w)};return[]});return[]})},d:function(a,b,c,d,e,f,g,l){var n=Vb(c,d);b=P(b);f=T(e,f);ob([],[a],function(m){function p(){Ub("Cannot call "+v+" due to unbound types",n)}m=m[0];var v=m.name+"."+b;l&&m.ra.Sb.push(b);var w=m.ra.Na,h=w[b];void 0===h||void 0===h.wa&&h.className!==m.name&&h.Va===c-2?(p.Va=c-2,p.className=m.name,w[b]=p):(Db(w,b,v),w[b].wa[c-2]=p);ob([],n,
function(r){r=Xb(v,r,m,f,g);void 0===w[b].wa?(r.Va=c-2,w[b]=r):w[b].wa[c-2]=r;return[]});return[]})},O:function(a,b){b=P(b);O(a,{name:b,fromWireType:function(c){var d=V[c].value;Zb(c);return d},toWireType:function(c,d){return R(d)},argPackAdvance:8,readValueFromPointer:fb,Ca:null})},v:function(a,b,c){c=pb(c);b=P(b);O(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+Ib(e)+'" to '+this.name);return e},
argPackAdvance:8,readValueFromPointer:$b(b,c),Ca:null})},r:function(a,b,c,d,e,f){var g=Vb(b,c);a=P(a);e=T(d,e);Eb(a,function(){Ub("Cannot call "+a+" due to unbound types",g)},b-1);ob([],g,function(l){Pb(a,Xb(a,[l[0],null].concat(l.slice(1)),null,e,f),b-1);return[]})},f:function(a,b,c,d,e){function f(m){return m}b=P(b);-1===e&&(e=4294967295);var g=pb(c);if(0===d){var l=32-8*c;f=function(m){return m<<l>>>l}}var n=-1!=b.indexOf("unsigned");O(a,{name:b,fromWireType:f,toWireType:function(m,p){if("number"!==
typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+Ib(p)+'" to '+this.name);if(p<d||p>e)throw new TypeError('Passing a number "'+Ib(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return n?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:ac(b,g,0!==d),Ca:null})},e:function(a,b,c){function d(f){f>>=2;var g=L;return new e(Ba,g[f+1],g[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array][b];c=P(c);O(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{Nb:!0})},w:function(a,b){b=P(b);var c="std::string"===b;O(a,{name:b,fromWireType:function(d){var e=L[d>>2];if(c)for(var f=d+4,g=0;g<=e;++g){var l=d+4+g;if(g==e||0==B[l]){f=z(f,l-f);if(void 0===n)var n=f;else n+=String.fromCharCode(0),n+=f;f=l+1}}else{n=Array(e);for(g=0;g<e;++g)n[g]=String.fromCharCode(B[d+4+g]);n=n.join("")}U(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));
var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||Q("Cannot pass non-string to std::string");var g=(c&&f?function(){return ra(e)}:function(){return e.length})(),l=H(4+g+1);L[l>>2]=g;if(c&&f)C(e,B,l+4,g+1);else if(f)for(f=0;f<g;++f){var n=e.charCodeAt(f);255<n&&(U(l),Q("String has UTF-16 code units that do not fit in 8 bits"));B[l+4+f]=n}else for(f=0;f<g;++f)B[l+4+f]=e[f];null!==d&&d.push(U,l);return l},argPackAdvance:8,readValueFromPointer:fb,
Ca:function(d){U(d)}})},p:function(a,b,c){c=P(c);if(2===b){var d=ta;var e=va;var f=wa;var g=function(){return E};var l=1}else 4===b&&(d=xa,e=ya,f=za,g=function(){return L},l=2);O(a,{name:c,fromWireType:function(n){for(var m=L[n>>2],p=g(),v,w=n+4,h=0;h<=m;++h){var r=n+4+h*b;if(h==m||0==p[r>>l])w=d(w,r-w),void 0===v?v=w:(v+=String.fromCharCode(0),v+=w),w=r+b}U(n);return v},toWireType:function(n,m){"string"!==typeof m&&Q("Cannot pass non-string to C++ string type "+c);var p=f(m),v=H(4+p+b);L[v>>2]=p>>
l;e(m,v+4,p+b);null!==n&&n.push(U,v);return v},argPackAdvance:8,readValueFromPointer:fb,Ca:function(n){U(n)}})},c:function(a,b,c,d,e,f){db[a]={name:P(b),jb:T(c,d),Ga:T(e,f),qb:[]}},a:function(a,b,c,d,e,f,g,l,n,m){db[a].qb.push({Gb:P(b),Mb:c,Kb:T(d,e),Lb:f,Xb:g,Wb:T(l,n),Yb:m})},Q:function(a,b){b=P(b);O(a,{Ob:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},L:function(a){delete mc[a-1]},i:function(a,b,c){a=bc(a);b=cc(b,"emval::as");var d=[],e=R(d);F[c>>2]=e;return b.toWireType(d,
a)},n:function(a,b,c,d){a=fc[a];b=bc(b);c=ec(c);a(b,c,null,d)},s:Zb,V:function(a){if(0===a)return R(gc());a=ec(a);return R(gc()[a])},m:function(a,b){b=ic(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(m){return m.name}).join("_")+"$",e=["retType"],f=[c],g="",l=0;l<a-1;++l)g+=(0!==l?", ":"")+"arg"+l,e.push("argType"+l),f.push(b[1+l]);d="return function "+jb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var n=0;for(l=0;l<a-1;++l)d+="    var arg"+l+" = argType"+l+".readValueFromPointer(args"+
(n?"+"+n:"")+");\n",n+=b[l+1].argPackAdvance;d+="    var rv = handle[name]("+g+");\n";for(l=0;l<a-1;++l)b[l+1].deleteObject&&(d+="    argType"+l+".deleteObject(arg"+l+");\n");c.Ob||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Wb(e).apply(null,f);return hc(a)},Y:function(a){a=ec(a);return R(k[a])},j:function(a,b){a=bc(a);b=bc(b);return R(a[b])},z:function(a){4<a&&(V[a].lb+=1)},q:function(a,b,c,d){a=bc(a);var e=jc[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+
"arg"+f;var g="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)g+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module","__emval_register",g+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(cc,k,R);jc[b]=e}return e(a,c,d)},T:function(){return R([])},
X:function(a){return R(ec(a))},U:function(){return R({})},W:function(a){eb(V[a].value);Zb(a)},o:function(a,b,c){a=bc(a);b=bc(b);c=bc(c);a[b]=c},h:function(a,b){a=cc(a,"_emval_take_value");a=a.readValueFromPointer(b);return R(a)},y:function(){y()},t:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=kc();else return-1;F[b>>2]=a/1E3|0;F[b+4>>2]=a%1E3*1E6|0;return 0},g:function(a,b,c){zd.length=0;var d;for(c>>=2;d=B[b++];)(d=105>d)&&c&1&&c++,zd.push(d?Da[c++>>1]:F[c]),++c;return Xa[a].apply(null,
zd)},N:lc,C:function(a,b,c){B.copyWithin(a,b,b+c)},D:function(a){var b=B.length;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-d%65536);a:{try{na.grow(Math.min(2147483648,d)-Ba.byteLength+65535>>>16);Ea();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},M:function(a,b,c,d,e){function f(A){oc(A,g,m,p,n)}function g(A,M){pc(A,M.response,function(J){r?N.get(r)(J):b&&b(J)},function(J){r?N.get(r)(J):b&&b(J)})}function l(A){oc(A,
v,m,p,n)}function n(A){I?N.get(I)(A):e&&e(A)}function m(A){x?N.get(x)(A):c&&c(A)}function p(A){D?N.get(D)(A):d&&d(A)}function v(A){r?N.get(r)(A):b&&b(A)}noExitRuntime=!0;var w=a+112,h=z(w),r=L[w+36>>2],x=L[w+40>>2],D=L[w+44>>2],I=L[w+48>>2],G=L[w+52>>2],ia=!!(G&4),u=!!(G&32);G=!!(G&16);if("EM_IDB_STORE"===h)h=L[w+84>>2],pc(a,B.slice(h,h+L[w+88>>2]),v,m);else if("EM_IDB_DELETE"===h)rc(a,v,m);else if(G){if(u)return 0;oc(a,ia?g:v,m,p,n)}else qc(a,v,u?m:ia?f:l);return a},G:function(a,b){try{var c=0;tc().forEach(function(d,
e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)K[e++>>0]=d.charCodeAt(f);K[e>>0]=0;c+=d.length+1});return 0}catch(d){return"undefined"!==typeof qd&&d instanceof X||y(d),d.La}},H:function(a,b){try{var c=tc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0}catch(e){return"undefined"!==typeof qd&&e instanceof X||y(e),e.La}},S:function(a){if(!noExitRuntime){if(k.onExit)k.onExit(a);oa=!0}fa(a,new Cd(a))},K:function(a){try{var b=rd(a);if(null===b.Ma)throw new X(8);
b.gb&&(b.gb=null);try{b.qa.close&&b.qa.close(b)}catch(c){throw c;}finally{Oc[b.Ma]=null}b.Ma=null;return 0}catch(c){return"undefined"!==typeof qd&&c instanceof X||y(c),c.La}},J:function(a,b,c,d){try{a:{for(var e=rd(a),f=a=0;f<c;f++){var g=F[b+(8*f+4)>>2],l=e,n=F[b+8*f>>2],m=g,p=void 0,v=K;if(0>m||0>p)throw new X(28);if(null===l.Ma)throw new X(8);if(1===(l.flags&2097155))throw new X(8);if(16384===(l.node.mode&61440))throw new X(31);if(!l.qa.read)throw new X(28);var w="undefined"!==typeof p;if(!w)p=
l.position;else if(!l.seekable)throw new X(70);var h=l.qa.read(l,v,n,m,p);w||(l.position+=h);var r=h;if(0>r){var x=-1;break a}a+=r;if(r<g)break}x=a}F[d>>2]=x;return 0}catch(D){return"undefined"!==typeof qd&&D instanceof X||y(D),D.La}},A:function(a,b,c,d,e){try{var f=rd(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=a)return-61;kd(f,a,d);Wa=[f.position>>>0,(Va=f.position,1<=+Math.abs(Va)?0<Va?(Math.min(+Math.floor(Va/4294967296),4294967295)|0)>>>0:~~+Math.ceil((Va-+(~~Va>>>0))/
4294967296)>>>0:0)];F[e>>2]=Wa[0];F[e+4>>2]=Wa[1];f.gb&&0===a&&0===d&&(f.gb=null);return 0}catch(g){return"undefined"!==typeof qd&&g instanceof X||y(g),g.La}},u:function(a,b,c,d){try{a:{for(var e=rd(a),f=a=0;f<c;f++){var g=e,l=F[b+8*f>>2],n=F[b+(8*f+4)>>2],m=void 0,p=K;if(0>n||0>m)throw new X(28);if(null===g.Ma)throw new X(8);if(0===(g.flags&2097155))throw new X(8);if(16384===(g.node.mode&61440))throw new X(31);if(!g.qa.write)throw new X(28);g.seekable&&g.flags&1024&&kd(g,0,2);var v="undefined"!==
typeof m;if(!v)m=g.position;else if(!g.seekable)throw new X(70);var w=g.qa.write(g,p,l,n,m,void 0);v||(g.position+=w);try{if(g.path&&Sc.onWriteToFile)Sc.onWriteToFile(g.path)}catch(x){t("FS.trackingDelegate['onWriteToFile']('"+g.path+"') threw an exception: "+x.message)}var h=w;if(0>h){var r=-1;break a}a+=h}r=a}F[d>>2]=r;return 0}catch(x){return"undefined"!==typeof qd&&x instanceof X||y(x),x.La}},Z:function(){var a=self.navigator.userAgent,b=ra(a)+1,c=H(b);C(a,B,c,b);return c},E:sd,R:function(a){Za();
var b=new Date(F[a+20>>2]+1900,F[a+16>>2],F[a+12>>2],F[a+8>>2],F[a+4>>2],F[a>>2],0),c=F[a+32>>2],d=b.getTimezoneOffset(),e=new Date(b.getFullYear(),0,1),f=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),g=e.getTimezoneOffset(),l=Math.min(g,f);0>c?F[a+32>>2]=Number(f!=g&&l==d):0<c!=(l==d)&&(f=Math.max(g,f),b.setTime(b.getTime()+6E4*((0<c?l:f)-d)));F[a+24>>2]=b.getDay();F[a+28>>2]=(b.getTime()-e.getTime())/864E5|0;F[a>>2]=b.getSeconds();F[a+4>>2]=b.getMinutes();F[a+8>>2]=b.getHours();F[a+12>>2]=
b.getDate();F[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},B:function(){},x:yd,F:function(a,b,c,d){return yd(a,b,c,d)}};
(function(){function a(e){k.asm=e.exports;na=k.asm._;Ea();N=k.asm.ha;Pa()}function b(e){a(e.instance)}function c(e){return Ua().then(function(f){return WebAssembly.instantiate(f,d)}).then(e,function(f){t("failed to asynchronously prepare wasm: "+f);y(f)})}var d={a:Dd};Oa();if(k.instantiateWasm)try{return k.instantiateWasm(d,a)}catch(e){return t("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ma||"function"!==typeof WebAssembly.instantiateStreaming||Qa()||"function"!==
typeof fetch?c(b):fetch(Ra,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){t("wasm streaming compile failed: "+f);t("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
var Ja=k.___wasm_call_ctors=function(){return(Ja=k.___wasm_call_ctors=k.asm.$).apply(null,arguments)},U=k._free=function(){return(U=k._free=k.asm.aa).apply(null,arguments)},H=k._malloc=function(){return(H=k._malloc=k.asm.ba).apply(null,arguments)},Tb=k.___getTypeName=function(){return(Tb=k.___getTypeName=k.asm.ca).apply(null,arguments)};k.___embind_register_native_and_builtin_types=function(){return(k.___embind_register_native_and_builtin_types=k.asm.da).apply(null,arguments)};
var cb=k.__get_tzname=function(){return(cb=k.__get_tzname=k.asm.ea).apply(null,arguments)},bb=k.__get_daylight=function(){return(bb=k.__get_daylight=k.asm.fa).apply(null,arguments)},ab=k.__get_timezone=function(){return(ab=k.__get_timezone=k.asm.ga).apply(null,arguments)};k.dynCall_jiji=function(){return(k.dynCall_jiji=k.asm.ia).apply(null,arguments)};k.dynCall_viijii=function(){return(k.dynCall_viijii=k.asm.ja).apply(null,arguments)};
k.dynCall_iiiiiijj=function(){return(k.dynCall_iiiiiijj=k.asm.ka).apply(null,arguments)};k.dynCall_iiiiij=function(){return(k.dynCall_iiiiij=k.asm.la).apply(null,arguments)};k.dynCall_iiiiijj=function(){return(k.dynCall_iiiiijj=k.asm.ma).apply(null,arguments)};var Ed;function Cd(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Na=function Fd(){Ed||Gd();Ed||(Na=Fd)};
function Gd(){function a(){if(!Ed&&(Ed=!0,k.calledRun=!0,!oa)){k.noFSInit||md||(md=!0,ld(),k.stdin=k.stdin,k.stdout=k.stdout,k.stderr=k.stderr,k.stdin?od("stdin",k.stdin):hd("/dev/tty","/dev/stdin"),k.stdout?od("stdout",null,k.stdout):hd("/dev/tty","/dev/stdout"),k.stderr?od("stderr",null,k.stderr):hd("/dev/tty1","/dev/stderr"),id("/dev/stdin",0),id("/dev/stdout",1),id("/dev/stderr",1));Ya(Ga);Rc=!1;Ya(Ha);aa(k);if(k.onRuntimeInitialized)k.onRuntimeInitialized();if(k.postRun)for("function"==typeof k.postRun&&
(k.postRun=[k.postRun]);k.postRun.length;){var b=k.postRun.shift();Ia.unshift(b)}Ya(Ia)}}if(!(0<La)){if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ka();Ya(Fa);0<La||(k.setStatus?(k.setStatus("Running..."),setTimeout(function(){setTimeout(function(){k.setStatus("")},1);a()},1)):a())}}k.run=Gd;if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.pop()();Gd();


  return BlinkInputWasmSDK.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = BlinkInputWasmSDK;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return BlinkInputWasmSDK; });
else if (typeof exports === 'object')
  exports["BlinkInputWasmSDK"] = BlinkInputWasmSDK;
